### PR TITLE
Kill processes in cgroup even if process Wait fails

### LINKED ISSUE #2632: Process leak if cgroup init process shares process namespace
The cgroup init process wait function uses Cmd.Wait from os/exec. That Wait function can return a non-nil error if the init process does not complete successfully say if it exits with a non-zero exit code or is terminated.

If the cgroup's init process shares process namespace, all the other processes, if any, in the cgroup will not be killed, resulting in a process leak.

From libcontainer/process_linux.go:
```go
func (p *initProcess) wait() (*os.ProcessState, error) {
	err := p.cmd.Wait()
	if err != nil {
		return p.cmd.ProcessState, err
	}
	// we should kill all processes in cgroup when init is died if we use host PID namespace
	if p.sharePidns {
		signalAllProcesses(p.manager, unix.SIGKILL)
	}
	return p.cmd.ProcessState, nil
}
```

### PR DESCRIPTION
**Pull request by chaitanyabandi**
If the cgroup's init process doesn't complete successfully, Wait returns a
non-nil error. We should still kill all the processes in the cgroup in that
case, if process namespace is shared. Otherwise, it may result in process leak.

Fixes #2632

Signed-off-by: Chaitanya Bandi <kbandi@cs.stonybrook.edu>

### CODE REVIEW

**Comment by kolyshkin** [comment]
@chaitanyabandi thanks! I suppose you have a repro... care to add a test case?

**Comment by chaitanyabandi** [comment]
> @chaitanyabandi thanks! I suppose you have a repro... care to add a test case?

Added a test in libcontainer/integration. Thanks for the feedback.

**Comment by chaitanyabandi** [comment]
@mrunalp , @kolyshkin PTAL, thank you.

File: libcontainer/integration/exec_test.go [hunk 1]
```diff
@@ -1660,6 +1661,70 @@ func TestPIDHost(t *testing.T) {
...
+
+	pidns := "/proc/1/ns/pid"
+
+	config := newTemplateConfig(rootfs)
+	config.Namespaces.Add(configs.NEWPID, pidns)
+	container, err := newContainerWithName("test", config)
+	ok(t, err)
+	defer func() {
+		err := container.Destroy()
+		ok(t, err)
```
Comment (kolyshkin) [inline libcontainer/integration/exec_test.go:1681]: You can't make any checks in defer, as the results of those will be discarded.

So, I guess, just
```go
defer container.Destroy()
```

File: libcontainer/integration/exec_test.go [hunk 2]
```diff
@@ -1660,6 +1661,70 @@ func TestPIDHost(t *testing.T) {
...
+	}()
+
+	// Run a container with two long-running processes.
+	stdinR1, stdinW1, err := os.Pipe()
+	ok(t, err)
+	process1 := &libcontainer.Process{
+		Cwd:   "/",
+		Args:  []string{"cat"},
```
Comment (kolyshkin) [inline libcontainer/integration/exec_test.go:1689]: Easier to do with something like `sleep 100`, this way you don't need those pipes.

File: libcontainer/integration/exec_test.go (hunk 1 above)
Comment (chaitanyabandi) [reply libcontainer/integration/exec_test.go:1681]: Using defer container.Destroy() caused the go linter to fail saying the return value of Destroy() was ignored. Hence I added the check. Should that linter error be ignored?

File: libcontainer/integration/exec_test.go (hunk 2 above)
Comment (chaitanyabandi) [reply libcontainer/integration/exec_test.go:1689]: I agree. Will post another change.

File: libcontainer/integration/exec_test.go [hunk 3]
```diff
@@ -1660,6 +1661,70 @@ func TestPIDHost(t *testing.T) {
...
+	ok(t, err)
+	_, err = process1.Wait()
+	if err == nil {
+		t.Fatal("expected Wait to indicate failure")
+	}
+
+	// The non-init process must've been killed.
+	err = process2.Signal(syscall.Signal(0))
+	if err == nil || err.Error() != "no such process" {
+		t.Fatalf("expected process to have been killed: %q", err)
```
Comment (kolyshkin) [inline libcontainer/integration/exec_test.go:1724]:
```suggestion
		t.Fatalf("expected process to have been killed: %v", err)
```
As otherwise when it fails it prints
```
    exec_test.go:1721: expected process to have been killed: %!q(<nil>)
```

**Comment by kolyshkin** [comment]
Looks good except a few nits, and I have checked the test case works (i.e. fails without the fix).

File: libcontainer/integration/exec_test.go [hunk 4]
```diff
@@ -1660,6 +1661,57 @@ func TestPIDHost(t *testing.T) {
...
+	defer remove(rootfs)
+
+	pidns := "/proc/1/ns/pid"
+
+	// Run a container with two long-running processes.
+	config := newTemplateConfig(rootfs)
+	config.Namespaces.Add(configs.NEWPID, pidns)
+	container, err := newContainerWithName("test", config)
+	ok(t, err)
+	defer container.Destroy()
```
Comment (kolyshkin) [inline libcontainer/integration/exec_test.go:1680]: I think
```suggestion
	defer _ = container.Destroy()
```

**Review by mrunalp — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM
