### PR TITLE
libct/nsenter: become root after joining userns

### LINKED ISSUE #4466: containerd's `TestPodUserNS` fails with runc v1.2 (succeeds with crun) on SELinux distro: `setxattr /[...]/dev/mqueue: operation not permitted`
On Fedora 40 and Rocky Linux 9, containerd's [`TestPodUserNS`](https://github.com/containerd/containerd/blob/bc3ce87c8475e67572ab14b96501acefb9799307/integration/pod_userns_linux_test.go#L129-L305) fails with the following change on top of the main branch of containerd (containerd/containerd@bc3ce87c8475e67572ab14b96501acefb9799307):
```diff
diff --git a/script/setup/runc-version b/script/setup/runc-version
index 6a99dbb7fd74..79127d85a49f 100644
--- a/script/setup/runc-version
+++ b/script/setup/runc-version
@@ -1 +1 @@
-v1.1.14
+v1.2.0
```

Failure:

```
    default: === RUN   TestPodUserNS
    default: === RUN   TestPodUserNS/userns_uid_mapping
    default:     pod_userns_linux_test.go:246: Create a sandbox with userns
    default: E1022 10:38:44.240499   45870 remote_runtime.go:132] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox "ed8348b9215a10dba3ef48191f37dfa41c7a4648bbdf7fba9365fdf8a4c1ed4e": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/ed8348b9215a10dba3ef48191f37dfa41c7a4648bbdf7fba9365fdf8a4c1ed4e/rootfs/dev/mqueue: operation not permitted
    default:     pod_userns_linux_test.go:251: Unexpected RunPodSandbox error: rpc error: code = Unknown desc = failed to start sandbox "ed8348b9215a10dba3ef48191f37dfa41c7a4648bbdf7fba9365fdf8a4c1ed4e": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/ed8348b9215a10dba3ef48191f37dfa41c7a4648bbdf7fba9365fdf8a4c1ed4e/rootfs/dev/mqueue: operation not permitted
    default: === RUN   TestPodUserNS/userns_gid_mapping
    default:     pod_userns_linux_test.go:246: Create a sandbox with userns
    default:     pod_userns_linux_test.go:251: Unexpected RunPodSandbox error: rpc error: code = Unknown desc = failed to start sandbox "d89053afdbbc20f3b11b2eae107e3d70213b21f473707dd5baa762d1a317aa3c": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/d89053afdbbc20f3b11b2eae107e3d70213b21f473707dd5baa762d1a317aa3c/rootfs/dev/mqueue: operation not permitted
    default: === RUN   TestPodUserNS/rootfs_permissions
    default:     pod_userns_linux_test.go:246: Create a sandbox with userns
    default: E1022 10:38:44.623562   45870 remote_runtime.go:132] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox "d89053afdbbc20f3b11b2eae107e3d70213b21f473707dd5baa762d1a317aa3c": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/d89053afdbbc20f3b11b2eae107e3d70213b21f473707dd5baa762d1a317aa3c/rootfs/dev/mqueue: operation not permitted
    default:     pod_userns_linux_test.go:251: Unexpected RunPodSandbox error: rpc error: code = Unknown desc = failed to start sandbox "83bda990b49619f5e98b41dd6fa5c6178264677bd3a2735debb66fb114ce0859": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/83bda990b49619f5e98b41dd6fa5c6178264677bd3a2735debb66fb114ce0859/rootfs/dev/mqueue: operation not permitted
    default: === RUN   TestPodUserNS/volumes_permissions
    default: E1022 10:38:44.971328   45870 remote_runtime.go:132] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox "83bda990b49619f5e98b41dd6fa5c6178264677bd3a2735debb66fb114ce0859": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/83bda990b49619f5e98b41dd6fa5c6178264677bd3a2735debb66fb114ce0859/rootfs/dev/mqueue: operation not permitted
    default:     pod_userns_linux_test.go:246: Create a sandbox with userns
    default:     pod_userns_linux_test.go:251: Unexpected RunPodSandbox error: rpc error: code = Unknown desc = failed to start sandbox "e579723f7f6ece7cc7e6c5294fa73308777f15baacd3f0f317225c0911b9c01b": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/e579723f7f6ece7cc7e6c5294fa73308777f15baacd3f0f317225c0911b9c01b/rootfs/dev/mqueue: operation not permitted
    default: === RUN   TestPodUserNS/fails_with_several_mappings
    default:     pod_userns_linux_test.go:246: Create a sandbox with userns
    default: E1022 10:38:45.379638   45870 remote_runtime.go:132] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox "e579723f7f6ece7cc7e6c5294fa73308777f15baacd3f0f317225c0911b9c01b": failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "mqueue" to rootfs at "/dev/mqueue": setxattr /run/containerd-test/io.containerd.runtime.v2.task/k8s.io/e579723f7f6ece7cc7e6c5294fa73308777f15baacd3f0f317225c0911b9c01b/rootfs/dev/mqueue: operation not permitted
    default: E1022 10:38:45.401499   45870 remote_runtime.go:132] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create network namespace for sandbox "461d0d64ea29a2c2b36262ad005d0ebaed8f1ea1d969f6944b575165caebc8a2": required only one uid mapping, but got 2 uid mapping(s)
    default: --- FAIL: TestPodUserNS (1.51s)
    default:     --- FAIL: TestPodUserNS/userns_uid_mapping (0.35s)
    default:     --- FAIL: TestPodUserNS/userns_gid_mapping (0.38s)
    default:     --- FAIL: TestPodUserNS/rootfs_permissions (0.35s)
    default:     --- FAIL: TestPodUserNS/volumes_permissions (0.41s)
    default:     --- PASS: TestPodUserNS/fails_with_several_mappings (0.02s)
```
https://github.com/containerd/containerd/actions/runs/11457221604/job/31880030218?pr=10877

This failure does not happen after reverting:
- https://github.com/containerd/containerd/pull/10741
https://github.com/containerd/containerd/pull/10607

However, as the same test has been passing for crun without reverting them, probably this issue has to be rather fixed on runc's side.

### PR DESCRIPTION
**Pull request by lifubang**
Containerd pre-creates userns and netns before calling runc, which
results in the current code not working when SELinux is enabled,
resulting in the following error:

> runc create failed: unable to start container process: error during
container init: error mounting "mqueue" to rootfs at "/dev/mqueue":
setxattr /path/to/rootfs/dev/mqueue: operation not permitted

The solution is to become root in the user namespace right after
we join it.

Fixes #4466.

Co-authored-by: Wei Fu <fuweid89@gmail.com>
Co-authored-by: Kir Kolyshkin <kolyshkin@gmail.com>
Co-authored-by: Aleksa Sarai <cyphar@cyphar.com>
Signed-off-by: lifubang <lifubang@acmcoder.com>

### CODE REVIEW

**Review by rata — COMMENTED** [review]
@lifubang nice finding! I haven't checked the code yet. But here are some general comments.

This seems to be what crun does too! Here it skips the userns: https://github.com/containers/crun/blob/2381713dd61e012eaf15458030eae627acd3c1c2/src/libcrun/linux.c#L3808. And then it joins it: https://github.com/containers/crun/blob/2381713dd61e012eaf15458030eae627acd3c1c2/src/libcrun/linux.c#L4615-L4617

However, crun is also handling a case where the container needs to join a PID namespace: https://github.com/containers/crun/blob/2381713dd61e012eaf15458030eae627acd3c1c2/src/libcrun/linux.c#L4562-L4568. I guess we need to do the same?

I'm unsure why we need to join the userns afterwards, though. Do you know why it is needed? Skimming through the man 7 user_namespaces I didn't see any mention

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: libcontainer/nsenter/nsexec.c [hunk 1]
```diff
@@ -501,6 +506,12 @@ void join_namespaces(char *nslist)
 		struct namespace_t *ns = &namespaces[i];
 		int flag = nsflag(ns->type);
 
+		if (flag == CLONE_NEWUSER) {
```
Comment (fuweid) [inline libcontainer/nsenter/nsexec.c:509]: I try to use `retsnoop` to check and found this in v6.5 kernel

```
21:47:54.401485 -> 21:47:54.401526 TID/PID 69055/69055 (runc:[2:INIT]/runc:[2:INIT]):

FUNCTION CALLS                                         RESULT    DURATION
----------------------------------------------------   --------  --------
→ __x64_sys_setxattr
    → path_setxattr
        → setxattr
            → do_setxattr
                → vfs_setxattr
                    → security_inode_setxattr
                        → selinux_inode_setxattr
                            ↔ inode_owner_or_capable   [false]    1.100us
                        ← selinux_inode_setxattr       [-EPERM]   2.700us
                    ← security_inode_setxattr          [-EPERM]   8.900us
                ← vfs_setxattr                         [-EPERM]  15.300us
            ← do_setxattr                              [-EPERM]  21.400us
        ← setxattr                                     [-EPERM]  24.000us
    ← path_setxattr                                    [-EPERM]  29.500us
← __x64_sys_setxattr                                   [-EPERM]  31.700us
```

https://github.com/torvalds/linux/blob/2dde18cd1d8fac735875f2e4987f11817cc0bc2c/security/selinux/hooks.c#L3151

Is it related to idmap here?

File: libcontainer/nsenter/nsexec.c [hunk 2]
```diff
@@ -907,7 +922,13 @@ void nsexec(void)
 					if (prctl(PR_SET_DUMPABLE, 0, 0, 0, 0) < 0)
 						bail("failed to re-set process as non-dumpable");
 				}
-
+			}
+			if (userns_fd > -1 && !config.is_rootless_euid) {
+				if (setns(userns_fd, CLONE_NEWUSER) < 0) {
+					bail("failed to join user namespace");
+				}
```
[the remark this answers is not in the document]
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:928]: Obviously yes, thanks.

**Comment by lifubang** [comment]
> nice finding!

Thanks, the thinking is from your clearly comments: https://github.com/opencontainers/runc/issues/4466#issuecomment-2431656059

> I'm unsure why we need to join the userns afterwards, though. Do you know why it is needed? Skimming through the man 7 user_namespaces I didn't see any mention

I think it just like the what we do for clone new user ns, we should join namespaces before unshare new user ns, or else there may be some namespaces waiting join are not owned by the user namespace.

> I guess we need to do the same?

After I see the crun code, I think it's not needed here, it's about hook run, I don't see which hook should be running when we are joining/unsharing namespaces. But maybe I'm wrong, I think if there is a bug to ref this, it will be more clear. Anyway, I think we can deal with it in a separate PR once we need it.

File: libcontainer/nsenter/nsexec.c (hunk 1 above)
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:508]: Maybe the net ns path created in containerd is not owned by the user ns?

Comment (fuweid) [reply libcontainer/nsenter/nsexec.c:508]: the path is about rootfs/dev/mqueue instead of net ns.
The net ns is created by new user ns.

The patch works on my local. But it's still mystery to me.

Comment (fuweid) [reply libcontainer/nsenter/nsexec.c:508]: Based on your patch, the change works on my local as well.

```diff
diff --git a/libcontainer/nsenter/nsexec.c b/libcontainer/nsenter/nsexec.c
index 74e15b96..350a17fe 100644
--- a/libcontainer/nsenter/nsexec.c
+++ b/libcontainer/nsenter/nsexec.c
@@ -505,6 +505,11 @@ void join_namespaces(char *nslist)
                if (setns(ns->fd, flag) < 0)
                        bail("failed to setns into %s namespace", ns->type);

+               if (flag == CLONE_NEWUSER) {
+                       if (setresuid(0, 0, 0) < 0)
+                               bail("failed to become root in user namespace");
+               }
+
                close(ns->fd);
        }
```

Comment (fuweid) [reply libcontainer/nsenter/nsexec.c:508]: Based on result of `inode_owner_or_capable` in linux, it looks like we use wrong fsuid to create `/dev/`, which isn't align with user mapping.

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:508]: So, the core reason is the second one in my comit msg?
2. Should also become root in the namespace, if we have joined a user ns
path like what we do in unsharing a new user ns.

Comment (fuweid) [reply libcontainer/nsenter/nsexec.c:508]: > So, the core reason is the second one in my comit msg?

Your comment is correct! Yes!

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:508]: > Based on your patch, the change works on my local as well.

But It can't work on my fedora 40.

Comment (kolyshkin) [reply libcontainer/nsenter/nsexec.c:508]: I am trying this in https://github.com/containerd/containerd/pull/10893 and will try locally, too.

Comment (fuweid) [reply libcontainer/nsenter/nsexec.c:508]: @lifubang I'm using Ubuntu 22'04 with 6.5 kernel. Would you mind to use retsnoop to show the stack trace ? Thanks

Comment (kolyshkin) [reply libcontainer/nsenter/nsexec.c:508]: Works for me locally in Fedora 40 Vagrant with SELinux enabled 

```
[root@localhost containerd]# runc --version
runc version 1.2.0+dev
commit: v1.0.0-1706-g7169f2d9
spec: 1.2.0
go: go1.23.2
libseccomp: 2.5.5
[root@localhost containerd]# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
[root@localhost containerd]# CONTAINERD_RUNTIME=io.containerd.runc.v2 FOCUS=TestPodUserNS ./script/test/cri-integration.sh
....
--- PASS: TestPodUserNS (5.24s)
    --- PASS: TestPodUserNS/volumes_permissions (1.32s)
    --- PASS: TestPodUserNS/fails_with_several_mappings (0.01s)
    --- PASS: TestPodUserNS/userns_uid_mapping (1.34s)
    --- PASS: TestPodUserNS/userns_gid_mapping (1.31s)
    --- PASS: TestPodUserNS/rootfs_permissions (1.25s)
PASS
```

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:508]: Oh, yes, it can work, I put the code in the wrong place.
So, we should change this PR to let the change as little as possible?

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c]: Changed.
Thanks all of you @fuweid, @kolyshkin, and @AkihiroSuda for test.

**Comment by cyphar** [comment]
Out of interest, does this patch also work?

```diff
diff --git a/libcontainer/nsenter/nsexec.c b/libcontainer/nsenter/nsexec.c
index 74e15b96d5fe..62a31c14e50d 100644
--- a/libcontainer/nsenter/nsexec.c
+++ b/libcontainer/nsenter/nsexec.c
@@ -444,9 +444,9 @@ void nl_free(struct nlconfig_t *config)
        free(config->data);
 }

-void join_namespaces(char *nslist)
+int join_namespaces(char *nslist)
 {
-       int num = 0, i;
+       int num = 0, joined_mask = 0, i;
        char *saveptr = NULL;
        char *namespace = strtok_r(nslist, ",", &saveptr);
        struct namespace_t {
@@ -505,10 +505,12 @@ void join_namespaces(char *nslist)
                if (setns(ns->fd, flag) < 0)
                        bail("failed to setns into %s namespace", ns->type);

+               joined_mask |= flag;
                close(ns->fd);
        }

        free(namespaces);
+       return joined_mask;
 }

 static inline int sane_kill(pid_t pid, int signum)
@@ -829,6 +831,7 @@ void nsexec(void)
        case STAGE_CHILD:{
                        pid_t stage2_pid = -1;
                        enum sync_t s;
+                       int joined_mask = 0;

                        /* For debugging. */
                        current_stage = STAGE_CHILD;
@@ -849,7 +852,7 @@ void nsexec(void)
                         * using cmsg(3) but that's just annoying.
                         */
                        if (config.namespaces)
-                               join_namespaces(config.namespaces);
+                               joined_mask = join_namespaces(config.namespaces);

                        /*
                         * Deal with user namespaces first. They are quite special, as they
@@ -907,8 +910,13 @@ void nsexec(void)
                                        if (prctl(PR_SET_DUMPABLE, 0, 0, 0, 0) < 0)
                                                bail("failed to re-set process as non-dumpable");
                                }
+                       }

-                               /* Become root in the namespace proper. */
+                       /*
+                        * If we swapped user namespaces at all, become root in the
+                        * namespace proper.
+                        */
+                       if ((joined_mask | config.cloneflags) & CLONE_NEWUSER) {
                                if (setresuid(0, 0, 0) < 0)
                                        bail("failed to become root in user namespace");
                        }
```

This makes it somewhat clearer that the bug was that we forgot to `setresuid` in the `CLONE_NEWUSER` case and unifies the logic.

I don't think we need to do `setresuid` immediately after joining because namespace joining is based on capabilities and you inherit the right capabilities when you join -- but maybe `setresuid` immediately after is clearer... Hmmm...

Also we need to adjust `join_namespaces` in a future patch to try to join the namespaces twice (to match `nsenter` -- see #4390) and the `joined_mask` is going to useful for that. But that's not too important.

File: libcontainer/nsenter/nsexec.c [hunk 3]
```diff
@@ -505,6 +505,12 @@ void join_namespaces(char *nslist)
 		if (setns(ns->fd, flag) < 0)
 			bail("failed to setns into %s namespace", ns->type);
 
+		/* See https://github.com/opencontainers/runc/issues/4466. */
```
Comment (cyphar) [inline libcontainer/nsenter/nsexec.c:508]: This actually isn't specific to that issue, the actual issue is that we forgot to do `setresuid` in this case. A more descriptive comment like

```suggestion
		/*
		 * If we change user namespaces, make sure we switch to root in the
		 * namespace (this matches the logic for unshare(CLONE_NEWUSER)). Lots
		 * of things can break if we aren't the right user. See
		 * <https://github.com/opencontainers/runc/issues/4466> for one
		 * example.
		 */
```

would be nice.

**Comment by lifubang** [comment]
> I don't think we need to do `setresuid` immediately after joining because namespace joining is based on capabilities and you inherit the right capabilities when you join -- but maybe `setresuid` immediately after is clearer... Hmmm...

SGTM, I'll try it later.

**Comment by lifubang** [comment]
> > I don't think we need to do `setresuid` immediately after joining because namespace joining is based on capabilities and you inherit the right capabilities when you join -- but maybe `setresuid` immediately after is clearer... Hmmm...
> 
> SGTM, I'll try it later.

Unfortunately, it can't fix this issue.

**Comment by kolyshkin** [comment]
It would be nice to have a test case. I'll try to come up with one tomorrow. We test on Fedora (not sure about selinux though) so we may be able to repro it.

**Comment by cyphar** [comment]
Yeah, I think doing `setresuid` immediately is probably a better solution anyway... Sorry for the noise.

**Comment by lifubang** [comment]
> It would be nice to have a test case.

Has add one test, I can confirm that this test is similar to #4466, it will be fail without this patch.

**Review by cyphar — APPROVED** [review]
LGTM. Thanks @lifubang!

**Comment by cyphar** [comment]
I'm quite surprised we never saw this issue before -- AFAICS this bug (not setting the uid/gid after joining) has existed for a long time (when I did the somewhat-large 2016 rewrite of `nsexec.c` I copied the old logic that had this bug as well).

I guess we didn't see it because it is very specific to `mqueue` (`mqueue` has a per-namespace superblock that is allocated at `CLONE_NEWIPC` time, and so the user you are at the time you do the unshare is critical) but I would've expected it to pop up before.

**Comment by fuweid** [comment]
Thank you @lifubang !

**Comment by kolyshkin** [comment]
> I guess we didn't see it because it is very specific to `mqueue` (`mqueue` has a per-namespace superblock that is allocated at `CLONE_NEWIPC` time, and so the credentials you have when you do `unshare(CLONE_NEWIPC)` influence a bunch of attributes of the mount) but I would've expected it to pop up before. Since this is only an issue with newer SELinux-heavy distros, maybe there was a config change or kernel change that caused this behaviour to become a problem? Odd.

For some reason, runc 1.1.15 works fine (this bug was discovered in https://github.com/containerd/containerd/pull/10877 which at the time was a mere runc bump to 1.2.0, and traced to 2 recent containerd commits listed in #4466 description).

I took a look at the diff between nexec.c in release-1.1 and main, but couldn't think of what could have caused the issue.

> (Or alternatively, RedHat now prefers crun and so they don't test with runc anymore?)

AFAICS, runc is still being tested and used actively
