### PR TITLE
cgroup2: fix conversion

### LINKED ISSUE #2243: cgroup2: cpu.max is broken in non-systemd mode
non-systemd mode (cpu.max is broken, memory.max is expected)
```console
$ sudo podman --cgroup-manager=cgroupfs run --rm --runtime=/usr/local/sbin/runc \
  --cpus 0.42 --memory 42m alpine \
  sh -exc "cat /sys/fs/cgroup/cpu.max && cat /sys/fs/cgroup/memory.max"
+ cat /sys/fs/cgroup/cpu.max
max 100000
+ cat /sys/fs/cgroup/memory.max
44040192

```

systemd mode (expected)
```console
$ sudo podman --cgroup-manager=systemd run --rm --runtime=/usr/local/sbin/runc \
  --cpus 0.42 --memory 42m alpine \
  sh -exc "cat /sys/fs/cgroup/cpu.max && cat /sys/fs/cgroup/memory.max"
+ cat /sys/fs/cgroup/cpu.max
42000 100000
+ cat /sys/fs/cgroup/memory.max
44040192
```

runc: 3b7e32febafcdd3c510d85dd24f0d477c3da6230
podman: containers/libpod@275e9b855dd0a384a283174912c08f3f097101b5

### LINKED ISSUE #2244: [regression 2213] cgroup2: numerical result out of range\\\\nfailed to write \\\\\\\"70369281052672\\\\\\\" to \\\\\\\"/sys/fs/cgroup/docker/36e5a611e225f5f94b343c384c688adcd957624fddb11eb74945b3efcdc56362/cpu.weight
The first execution of `docker run` (without `--cpu-shares`) succeeds, but the second execution fails because runc tries to write 70369281052672 to ` /sys/fs/cgroup/docker/$cid/cpu.weight`, which exceeds ~` /sys/fs/cgroup/docker/cpu.weight`=100~ maximum value 10000.

```console
$ docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container ini
t caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"error while setting cgroup v2: [write /sys/fs/cgroup/docker/36e5a611e
225f5f94b343c384c688adcd957624fddb11eb74945b3efcdc56362/cpu.weight: numerical result out of range\\\\nfailed to write \\\\\\\"70369281052672\\\\\\\" to \\\\\
\\"/sys/fs/cgroup/docker/36e5a611e225f5f94b343c384c688adcd957624fddb11eb74945b3efcdc56362/cpu.weight\\\\\\\"\\\\ngithub.com/opencontainers/runc/libcontainer/
cgroups/fscommon.WriteFile\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/fscommon.go:21\\\\ngithub.com/opencont
ainers/runc/libcontainer/cgroups/fs2.setCpu\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/cgroups/fs2/cpu.go:18\\\\ngithub.com/o
pencontainers/runc/libcontainer/cgroups/fs2.(*manager).Set\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/cgroups/fs2/fs2.go:187\
\\\ngithub.com/opencontainers/runc/libcontainer.(*initProcess).start.func3\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/process
_linux.go:414\\\\ngithub.com/opencontainers/runc/libcontainer.parseSync\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/sync.go:99
\\\\ngithub.com/opencontainers/runc/libcontainer.(*initProcess).start\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/process_linu
x.go:372\\\\ngithub.com/opencontainers/runc/libcontainer.(*linuxContainer).start\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/libcontainer/c
ontainer_linux.go:344\\\\ngithub.com/opencontainers/runc/libcontainer.(*linuxContainer).Start\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/l
ibcontainer/container_linux.go:241\\\\nmain.(*runner).run\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/utils_linux.go:320\\\\nmain.startCont
ainer\\\\n\\\\t/home/suda/gopath/src/github.com/opencontainers/runc/utils_linux.go:452\\\\nmain.glob..func2\\\\n\\\\t/home/suda/gopath/src/github.com/opencon
tainers/runc/create.go:65\\\\ngithub.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction\\\\n\\\\t/home/suda/gopath/src/github.com/opencontaine
rs/runc/vendor/github.com/urfave/cli/app.go:490\\\\ngithub.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run\\\\n\\\\t/home/suda/gopath/src/gi
thub.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:210\\\\ngithub.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run\\\\n\\\\t
/home/suda/gopath/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:255\\\\nmain.main\\\\n\\\\t/home/suda/gopath/src/github.com/opencont
ainers/runc/main.go:145\\\\nruntime.main\\\\n\\\\t/usr/local/go/src/runtime/proc.go:203\\\\nruntime.goexit\\\\n\\\\t/usr/local/go/src/runtime/asm_amd64.s:137
3]\\\"\"": unknown.

$ cat /sys/fs/cgroup/docker/cpu.weight
100
```

Regression in 7c439cc6f617eb234bbc1754ab0b21041a9be87e (#2213) .

### PR DESCRIPTION
**Pull request by AkihiroSuda**
* TestConvertCPUSharesToCgroupV2Value(0) was returning 70369281052672, while the correct value is 0
* ConvertBlkIOToCgroupV2Value(0) was returning 32, while the correct value is 0
* ConvertBlkIOToCgroupV2Value(1000) was returning 4, while the correct value is 10000
* CpuMax wasn't converted at all

Fix #2244
Fix #2243
Follow-up to #2212 #2213

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
@mrunalp PTAL?

File: libcontainer/cgroups/utils.go [hunk 1]
```diff
@@ -601,5 +604,22 @@ func ConvertBlkIOToCgroupV2Value(blkIoWeight uint16) uint64 {
...
 	return (1 + ((cpuShares-2)*9999)/262142)
 }
+
+// ConvertCPUQuotaCPUPeriodToCgroupV2Value generates cpu.max string.
+func ConvertCPUQuotaCPUPeriodToCgroupV2Value(quota int64, period uint64) string {
+	if quota <= 0 && period == 0 {
+		return ""
+	}
+	if period == 0 {
+		period = 100000
```
Comment (thaJeztah) [inline libcontainer/cgroups/utils.go]: (just a comment as I was glancing over the changes); would it be a good idea to define `const`'s for these magic values? (there's some other values above as well)

Comment (AkihiroSuda) [reply libcontainer/cgroups/utils.go]: I think just adding comments is fine. Not really reusable as `const` values.

Comment (AkihiroSuda) [reply libcontainer/cgroups/utils.go]: added code comment for explanation

**Comment by mrunalp** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
I assume Michael's LGTM is still effective after the force-push. (I only added comment lines.)

Merging.
