### PR TITLE
Consoles, consoles, consoles.

### LINKED ISSUE #814: Console path resolution is done in host mount namespace
[I realised this while trying to get the test suite to run for #774.]

The main issue is that we set up the console in the parent's mount namespace. This breaks quite a few things. In addition, `--console` resolution done in the parent causes things like `su` to not work in containers (because glibc is broken). If you have a `config.json` like this:

```
{
    "ociVersion": "0.6.0-dev",
    "platform": {
        "os": "linux",
        "arch": "amd64"
    },
    "process": {
        "terminal": true,
        "user": {},
        "args": [
            "sh"
        ],
        "env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "TERM=xterm"
        ],
        "cwd": "/",
        "capabilities": [
            "CAP_AUDIT_WRITE",
            "CAP_KILL",
            "CAP_NET_BIND_SERVICE"
        ],
        "rlimits": [
            {
                "type": "RLIMIT_NOFILE",
                "hard": 1024,
                "soft": 1024
            }
        ],
        "noNewPrivileges": true
    },
    "root": {
        "path": "rootfs",
        "readonly": true
    },
    "hostname": "runc",
    "mounts": [
        {
            "destination": "/proc",
            "type": "proc",
            "source": "proc"
        },
        {
            "destination": "/dev",
            "type": "tmpfs",
            "source": "tmpfs",
            "options": [
                "nosuid",
                "strictatime",
                "mode=755",
                "size=65536k"
            ]
        },
        {
            "destination": "/dev/pts",
            "type": "devpts",
            "source": "devpts",
            "options": [
                "nosuid",
                "noexec",
                "newinstance",
                "ptmxmode=0666",
                "mode=0620"
            ]
        },
        {
            "destination": "/dev/shm",
            "type": "tmpfs",
            "source": "shm",
            "options": [
                "nosuid",
                "noexec",
                "nodev",
                "mode=1777",
                "size=65536k"
            ]
        },
        {
            "destination": "/dev/mqueue",
            "type": "mqueue",
            "source": "mqueue",
            "options": [
                "nosuid",
                "noexec",
                "nodev"
            ]
        },
        {
            "destination": "/sys",
            "type": "none",
            "source": "/sys",
            "options": [
                "rbind",
                "nosuid",
                "noexec",
                "nodev",
                "ro"
            ]
        }
    ],
    "hooks": {},
    "linux": {
        "uidMappings": [
            {
                "hostID": 1000,
                "containerID": 0,
                "size": 1
            }
        ],
        "gidMappings": [
            {
                "hostID": 100,
                "containerID": 0,
                "size": 1
            }
        ],
        "namespaces": [
            {
                "type": "pid"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            },
            {
                "type": "mount"
            },
            {
                "type": "user"
            }
        ],
        "maskedPaths": [
            "/proc/kcore",
            "/proc/latency_stats",
            "/proc/timer_stats",
            "/proc/sched_debug"
        ],
        "readonlyPaths": [
            "/proc/asound",
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ]
    }
}
```

/cc @crosbymichael

### PR DESCRIPTION
**Pull request by cyphar**
This is the big console rewrite. For some design information, see [this](https://gist.github.com/cyphar/8c6b9db84fc1f2cc2d037ef07942ca83). TODO list:
- [x] Implement the console masterfd passing.
- [x] Rewrite parts of `tty.go` to work with the new setup.
- [x] Remove `--console` and add `--console-socket`.
  - [x] Need to figure out a sane protocol for sending things to `--console-socket`.
  - [x] Write a small implementation of a `--console-socket` consumer as a sanity check [can be done in a separate PR].
- [x] Figure out how to make the test suite behave.
  - [x] `TestExecInTTY`.
  - [x] bats `integration`.
- [x] Need to figure out why runC is blocking on `recvfd()`.

Fixes #814, #910, docker/docker#11462, docker/docker#8755 and countless other issues.
~~Depends on #975, #977.~~
docker/docker#9212 and similar issues are **not** fixed by this patchset, as we still need to consider how to handle `/dev/console` in certain cases.

Signed-off-by: Aleksa Sarai asarai@suse.de

### CODE REVIEW

**Comment by cyphar** [comment]
Alright @opencontainers/runc-maintainers, this code is starting to get ready. I have some questions that we should address:

1. Currently `detach && !process.terminal` will result in runC duping its own stdio over the container's stdio. This results in quite a few odd things happening (such as your terminal becoming unusable due to `read(2)` races). Is there a reason we do this instead of doing something like duping `/dev/null` over the container's stdio? The OCI spec doesn't really specify anything about what we should do here and IMO duping the **current terminal**'s stdio isn't really a very logical thing to do (not least of all because it's possible to use that to carry out terminal attacks against the session the process was started in).

2. Does it make any sense to allow `--console-socket` without `detach`? Personally I don't see what a user would expect runC to do in such a case (and thus have currently disabled it). The same question goes for `--console-socket` and `!process.terminal`.

3. For the protocol of `--console-socket`, what should we send and how should we send it? Personally I would prefer that we send things using `iov` in the message packet to ensure that nothing fishy goes on (and also to not require you to read things in a particular way so you can get the fd). What we should send is another question -- should we just send `container.ID()` or the whole state JSON?

4. Can someone _please_ help me fix the tests? They're broken and I've not been able to get them to work (it doesn't help that I'm not sure why they worked in the first place -- what does `--console /dev/pts/ptmx` even mean given the old console implementation). The more worrying failing test is the `ExecInTTY` test (which is really meant to be testing the new API and it isn't working ... gulp).

**Comment by cyphar** [comment]
`ExecInTTY` passes on my local machine now. I'm confused why it's failing in Jenkins...

**Comment by mrunalp** [comment]
From my quick testing, there are some issues. runc run works sometimes and just hangs other times. Could be a race. I'll review the code.

**Comment by mrunalp** [comment]
>    Currently detach && !process.terminal will result in runC duping its own stdio over the container's stdio. This results in quite a few odd things happening (such as your terminal becoming unusable due to read(2) races). Is there a reason we do this instead of doing something like duping /dev/null over the container's stdio? The OCI spec doesn't really specify anything about what we should do here and IMO duping the current terminal's stdio isn't really a very logical thing to do (not least of all because it's possible to use that to carry out terminal attacks against the session the process was started in).

This has been the docker default where we don't need to allocate a tty but just use the parent tty. I don't have strong opinions either way but changing this to dup /dev/null would mean that users would now be expected to set terminal to true when they didn't have to in the past. One more useful thing that we could do is allow setting the stdio to some FDs instead which would simplify logging from containers. 

>    Does it make any sense to allow --console-socket without detach? Personally I don't see what a user would expect runC to do in such a case (and thus have currently disabled it). The same question goes for --console-socket and !process.terminal.

I don't see a reason either.

>    For the protocol of --console-socket, what should we send and how should we send it? Personally I would prefer that we send things using iov in the message packet to ensure that nothing fishy goes on (and also to not require you to read things in a particular way so you can get the fd). What we should send is another question -- should we just send container.ID() or the whole state JSON?

How about we just send the minimal required which is just the fd and the container ID (for logging)?

 >   Can someone please help me fix the tests? They're broken and I've not been able to get them to work (it doesn't help that I'm not sure why they worked in the first place -- what does --console /dev/pts/ptmx even mean given the old console implementation). The more worrying failing test is the ExecInTTY test (which is really meant to be testing the new API and it isn't working ... gulp).

I don't see how we can do the tests easily in bash. At minimum we will need a binary that calls create, receives the FD over the socket and copies data back and forth between master fd and stdio. Next would be to call start (from a fork/thread). Maybe this could be the example binary that illustrates the new API. 


>  Does anyone have an issue with me adding contrib/cmd/recvtty? IMO we need to have a PoC which actually works with the --console-socket API. Maybe @crosbymichael can add his old console handling code to the PoC so people know how to have a proper terminal setup (though it'll probably be a clone of the runC code).

I think using this binary for tests should work well as an example. 

>    Should we make --console-socket a slightly more generic interface? Something like --events where we send different file descriptors down the socket to provide information to higher level orchestrators? We wouldn't have to implement anything other than consoles, but if we ever wanted to have this kind of functionality we should probably consider future-proofing this interface now.

On the fence for this. Maybe defer to post 1.0.

**Comment by cyphar** [comment]
> From my quick testing, there are some issues. runc run works sometimes and just hangs other times. Could be a race. I'll review the code.

That's /very/ odd, since it doesn't happen on my machine. But that probably explains why Jenkins is still timing out even though I fixed the logic issue. Maybe there's some disk access that's killing the synchronisation between the processes? AFAIK the ordering of `sendmsg` and `recvmsg` doesn't matter because they'll always block until the other end is ready.

**Comment by wking** [comment]
On Tue, Sep 06, 2016 at 02:36:37PM -0700, Mrunal Patel wrote:
> > Currently detach && !process.terminal will result in runC duping
> > its own stdio over the container's stdio. This results in quite a
> > few odd things happening (such as your terminal becoming unusable
> > due to read(2) races). Is there a reason we do this instead of
> > doing something like duping /dev/null over the container's stdio?
> > The OCI spec doesn't really specify anything about what we should
> > do here and IMO duping the current terminal's stdio isn't really a
> > very logical thing to do (not least of all because it's possible
> > to use that to carry out terminal attacks against the session the
> > process was started in).
>
> This has been the docker default where we don't need to allocate a
> tty but just use the parent tty. I don't have strong opinions either
> way but changing this to dup /dev/null would mean that users would
> now be expected to set terminal to true when they didn't have to in
> the past.

When detach is true?  I can see dupling the runtime stdio over the
container stdio when !detach && !process.terminal (e.g. if you're
using the host mount namespace or for some other reason would be using
the host devpts inside the container anyway); it saves the cost of a
new terminal.  But if you're going to detach (presumably so you can
use your original terminal for something else), I don't see the point.

> > For the protocol of --console-socket, what should we send and how
> > should we send it?…
>
> How about we just send the minimal required which is just the fd and
> the container ID (for logging)?

And also (per the future-proofing point 6 [1]), some sort of “here's
the pseudoterminal master” token.  I think you want some way to
version the socket messages from the beginning, and putting a
message-type string in a consistent place is an easy way to do that.

[1]: https://github.com/opencontainers/runc/pull/1018#issuecomment-244761714

**Comment by cyphar** [comment]
@mrunalp Alright, I can reproduce the stalling if I use `strace`. It looks like it might be some sort of race condition triggered by some timing issue (it's blocking on a read though). Attached is the strace logs. Oddly enough, if you kill *just* the `strace` process the command becomes un-stalled. Weird.

**Comment by cyphar** [comment]
Alright, after staring at strace logs and `/proc/<pid>/task/*/status` for a couple of hours I think I know what's going on. In the strace logs, the following call is what we stall on (in the `runc init` process):

```
[pid  3753] execve("/usr/bin/ls", ["ls", "-la", "/proc/self/fd/"], [/* 3 vars */] <unfinished ...>
```

Now, the semantics of `execve` are "fun" for multithreaded processes. Basically, only single-threaded processes are capable of undergoing an `execve`. So when you do an `execve`, the kernel is meant to kill every other task in the threadgroup. But that's not happening. Why? Because **for some reason** all of the other tasks in this thread group appear to be zombies. This only happens sometimes and I'm not really sure why:

```
% grep -i state /proc/<pid>/task/*/status
State:  D (disk sleep)
State:  Z (zombie)
State:  Z (zombie)
State:  Z (zombie)
State:  Z (zombie)
State:  Z (zombie)
```

But this only happens when you hit the console changes, so clearly something changed in the process management that caused this. I'll have to look into it some more.

**Comment by cyphar** [comment]
Dammit, I just realised that this also happens on master...

**Comment by cyphar** [comment]
Alright. It looks like the above is a **red herring**, `strace` and `runc` don't seem to play well together before this PR. So now I have to debug this issue without `strace`... Brilliant.

**Comment by mrunalp** [comment]
@cyphar One thing that could be causing issue is the socketpair using SOCK_STREAM. We could try using SOCK_SEQPACKET instead. (We might even need two different pairs).

**Comment by mrunalp** [comment]
@cyphar Here is the strace:
```
[pid 26445] 15:52:16 recvmsg(5,  <unfinished ...>
[pid 26444] 15:52:16 futex(0xc42006a110, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 26443] 15:52:16 futex(0xb16b00, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 26442] 15:52:16 futex(0xc420034910, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 26441] 15:52:16 restart_syscall(<... resuming interrupted futex ...> <unfinished ...>
[pid 26440] 15:52:16 futex(0xafc070, FUTEX_WAIT, 0, NULL
```

I am pretty certain now that the data is consumed by an earlier receive. We should probably look into another socketpair with SOCK_SEQPACKET for passing the fd.

**Comment by cyphar** [comment]
@mrunalp Sigh, yeah I was worried it was something like that. The question is whether we _need_ to use two socketpairs. I'd prefer to not have to have two parent pipes...

**Comment by cyphar** [comment]
@mrunalp Actually, it's not a `recv*` which is gobbling up the out-of-band message. It's the synchronisation read (note the `B` at the end of the JSON payload, that is the `iov` I'm sending which is `0x42`):

```
[pid  7981] write(3, "{\"type\":\"procConsole\"}", 22) = 22
[pid  7981] sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="B", iov_len=1}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[6]}], msg_controllen=24, msg_flags=0}, 0 <unfinished ...>
[pid  7982] <... select resumed> )      = 0 (Timeout)
[pid  7981] <... sendmsg resumed> )     = 1
[pid  7982] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7981] read(3,  <unfinished ...>
[pid  7977] <... write resumed> )       = 21
[pid  7974] <... select resumed> )      = 0 (Timeout)
[pid  7977] read(5,  <unfinished ...>
[pid  7982] <... select resumed> )      = 0 (Timeout)
[pid  7974] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7982] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7977] <... read resumed> "{\"type\":\"procConsole\"}B", 512) = 23
[pid  7982] <... select resumed> )      = 0 (Timeout)
[pid  7982] futex(0xc820021108, FUTEX_WAKE, 1) = 1
[pid  7986] <... futex resumed> )       = 0
[pid  7982] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid  7986] futex(0xc820021108, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid  7982] <... select resumed> )      = 0 (Timeout)
[pid  7977] recvmsg(5,  <unfinished ...>
[pid  7982] futex(0xc9cc10, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid  7974] <... select resumed> )      = 0 (Timeout)
[pid  7974] select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
```

So to fix this I can add a two-way synchronisation before sending the console fd. No need to add another pipe (which would just make the code even uglier).

**Comment by cyphar** [comment]
@mrunalp I've fixed it with this commit. PTAL.

```
commit 86f76c33d818d929be75afc9a1c12a8e374d42ae
Author: Aleksa Sarai <asarai@suse.de>
Date:   Thu Sep 8 20:27:09 2016 +1000

    [squashme] console: use two-stage synchronisation
    
    This ensures that when the syscalls are reordered in a suboptimal way,
    an out-of-place read() on the parentPipe will not gobble the ancilliary
    information.
    
    Signed-off-by: Aleksa Sarai <asarai@suse.de>
```

**Comment by mrunalp** [comment]
@cyphar Makes sense :+1: I'll try this out later today.

**Comment by mrunalp** [comment]
This works fine for me with runc run/runc exec :clap:

**Comment by cyphar** [comment]
Awesome. Now I just need to fix the `bats` stuff, and properly formalise the API for sending the master pty to the `--console-socket`. Currently `cgo` is being annoying (`C.CString` is breaking things). :smile:

**Comment by mrunalp** [comment]
I can help with testing that as I am writing code for that integration in a monitoring agent.

**Comment by cyphar** [comment]
If you can help me figure out why 9ae946330e372ddad2086205f4187a6385239964 is currently segfaulting, I''ll buy you a drink when we eventually meet f2f. :P

**Comment by mrunalp** [comment]
Can't get to it before tomorrow 🙁
Do you have the line where it is set faulting?

**Comment by cyphar** [comment]
`gdb` tells me it's fauling on this line:

```
if (!fdptr || *fdptr < 0)
```

Basically, it looks like `fdptr` is `0x10` (the address, not the dereferenced value). Which I don't understand. Maybe I'm misusing the API?

File: libcontainer/utils/cmsg.c [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+	msg.msg_control = u.buf;
+	msg.msg_controllen = sizeof(u.buf);
+
+	cmsg = CMSG_FIRSTHDR(&msg);
+	cmsg->cmsg_level = SOL_SOCKET;
+	cmsg->cmsg_type = SCM_RIGHTS;
+	cmsg->cmsg_len = CMSG_LEN(sizeof(int));
+
+	fdptr = (int *) CMSG_DATA(cmsg);
+	memcpy(fdptr, &file.fd, sizeof(int));
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: I think you want this to be:

    *fdptr = file.fd;

File: libcontainer/utils/cmsg.c [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+		struct cmsghdr align;
+	} u;
+
+	/*
+	 * We need to send some other data along with ancilliary data, otherwise
+	 * the other side won't recieve any data. This is very well-hidden in the
+	 * documentation.
+	 */
+	iov[0].iov_base = file.tag;
+	iov[0].iov_len = strlen(file.tag) + 1;
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: Sending a tag along with the file descriptor is a good idea for avoiding confusion (“here comes the pseudoterminal master”, `<fd>`).  But I didn't bother setting `msg.msg_iov` or `msg.msg_iovlen` in ccon (short of initializing `msg = {0}`), and I haven't had a problem without them.  The `SCM_RIGHTS` example in cmsg(3) doesn't bother with the `iov` fields either (although it doesn't explicitly call `sendmsg`).  Can you link to the docs you reference from your comment?

File: libcontainer/utils/cmsg.c (hunk 1 above)
Comment (wking) [inline libcontainer/utils/cmsg.c]: Never mind, both of those are equivalent.

File: libcontainer/utils/cmsg.c [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+	cmsg->cmsg_len = CMSG_LEN(sizeof(int));
+
+	fdptr = (int *) CMSG_DATA(cmsg);
+	memcpy(fdptr, &file.fd, sizeof(int));
+
+	ret = sendmsg(sockfd, &msg, 0);
+	if (ret < 0)
+		return ret;
+
+	return 0;
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: No need for `ret` unless you want to do something else in this function.  As it stands, just return `sendmsg`.

File: libcontainer/utils/cmsg.c [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+
+	/*
+	 * We need to "recieve" the non-ancilliary data even though we don't plan
+	 * to use it at all. Otherwise, things won't work as expected.
+	 */
+	iov[0].iov_base = file.tag;
+	iov[0].iov_len = TAG_BUFFER;
+
+	msg.msg_name = NULL;
+	msg.msg_namelen = 0;
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: No need to bother with these two, since you initialized `msg = {0}`.  But it doesn't hurt to have them here either.

File: libcontainer/utils/cmsg.c [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+	int *fdptr;
+	int olderrno;
+
+	union {
+		char buf[CMSG_SPACE(sizeof(file.fd))];
+		struct cmsghdr align;
+	} u;
+
+	/* Allocate a buffer. */
+	file.tag = malloc(TAG_BUFFER);
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: Check if `file.tag` is `NULL`.

File: libcontainer/utils/cmsg.c [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+	msg.msg_iov = iov;
+	msg.msg_iovlen = 1;
+	msg.msg_control = u.buf;
+	msg.msg_controllen = sizeof(u.buf);
+
+	ssize_t ret = recvmsg(sockfd, &msg, 0);
+	if (ret < 0)
+		goto err;
+
+	cmsg = CMSG_FIRSTHDR(&msg);
```
Comment (wking) [inline libcontainer/utils/cmsg.c]: The `IP_TTL` example in cmsg(3) checks checks if `cmsg` is `NULL` after getting it back from `CMSG_FIRSTHDR`.

**Comment by wking** [comment]
On Thu, Sep 08, 2016 at 08:20:11PM -0700, Aleksa Sarai wrote:
> `gdb` tells me it's fauling on this line:
> 
> ```
> if (!fdptr || *fdptr < 0)
> ```
>
> Basically, it looks like `fdptr` is `0x10` (the address, not the
> dereferenced value). Which I don't understand. Maybe I'm misusing
> the API?

I haven't looked at the Go stuff (too complicated ;).  But the C looks
good to me.  And with this stub test code [1] it works:

  $ gcc -o cmsg cmsg.c && ./cmsg 
  sent: 5 'hi'
  received: 6 'hi'
  read:
  NAME=Gentoo
  …
  BUG_REPORT_URL="https://bugs.gentoo.org/"

So not sure what your segfault is about.

[1]: diff --git a/libcontainer/utils/cmsg.c b/libcontainer/utils/cmsg.c
     index 28ef397..5b5a3fd 100644
     --- a/libcontainer/utils/cmsg.c
     +++ b/libcontainer/utils/cmsg.c
     @@ -19,7 +19,9 @@
      #include <stdlib.h>
      #include <string.h>
      #include <sys/socket.h>
     +#include <sys/stat.h>
      #include <sys/types.h>
     +#include <fcntl.h>
      #include <unistd.h>
      
      #include "cmsg.h"
     @@ -145,3 +147,43 @@ err:
        errno = olderrno;
        return (struct file_t){0};
      }
     +
     +int main()
     +{
     +  int sockets[2];
     +  struct file_t file1, file2;
     +  file1.tag = "hi";
     +
     +  if (socketpair(AF_UNIX, SOCK_SEQPACKET, 0, sockets) == -1) {
     +    perror("socketpair");
     +    return 1;
     +  }
     +
     +  file1.fd = open("/etc/os-release", O_RDONLY);
     +  if (file1.fd < 0) {
     +    perror("open");
     +    return 1;
     +  }
     +
     +  if (sendfd(sockets[0], file1) < 0) {
     +    fprintf(stderr, "sendfd\n");
     +    return 1;
     +  }
     +
     +  printf("sent: %d '%s'\n", file1.fd, file1.tag);
     +
     +  file2 = recvfd(sockets[1]);
     +  if (file2.tag == NULL) {
     +    fprintf(stderr, "recvfd\n");
     +    return 1;
     +  }
     +
     +  printf("received: %d '%s'\n", file2.fd, file2.tag);
     +  if (read(file2.fd, file2.tag, TAG_BUFFER) < 0) {
     +    perror("read");
     +    return 1;
     +  }
     +
     +  printf("read:\n%s", file2.tag);
     +  return 0;
     +}

**Comment by cyphar** [comment]
@wking The cgo changes are a WIP at the moment. :P

**Comment by cyphar** [comment]
@wking Thanks, I'm going to look at this later today.

**Comment by mrunalp** [comment]
After applying the NULL checks, I am seeing:
```
interface conversion: interface {} is *utils._Ctype_char, not unsafe.Pointer
```

**Comment by wking** [comment]
On Fri, Sep 09, 2016 at 11:41:54AM -0700, Mrunal Patel wrote:
> After applying the NULL checks, I am seeing:
> ```
> interface conversion: interface {} is *utils._Ctype_char, not
> unsafe.Pointer
> ```

Sounds like you need to do some pointer manipulation to convert
between a Go string and a char* [1].

[1]: https://golang.org/cmd/cgo/#hdr-Passing_pointers

**Comment by cyphar** [comment]
*angry noises*. Alright, I'll play around with cgo a bit more.

**Comment by mrunalp** [comment]
Okay, I have it working! :) Cleaning up the patch and posting.

**Comment by mrunalp** [comment]
I have added a commit here https://github.com/opencontainers/runc/commit/ed05c1e02410e967ea69cca7818117e08fcd62f0

**Comment by cyphar** [comment]
:heart: But note that you don't need to do a NULL check on `free` (`free(NULL)` is a guaranteed noop).

**Comment by mrunalp** [comment]
@cyphar old habit from working on platforms where that wasn't always true :) Feel free to clean it up and merge it with your changes as you see fit.

File: libcontainer/utils/cmsg.c (hunk 2 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.c]: It's because we use `SOCK_STREAM`. You have to read the `NOTES` section in `unix(7)`.

File: libcontainer/utils/cmsg.c (hunk 1 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.c]: `memcpy` is the superior assignment method. :P

File: libcontainer/utils/cmsg.c (hunk 3 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.c]: I can't remember what I was planning to do here that turns out wasn't necessary. I'll pass by this on the final cleanup.

File: libcontainer/utils/cmsg.c (hunk 4 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.c]: Explicit > implicit. Especially when it comes to unix sockets (from my experience).

**Comment by cyphar** [comment]
Alright. @mrunalp everything except `bats` now works. Time to figure out what's causing that. I've also now added `libcontainer.TerminalInfo` which is basically storing the information about the container which is sent with the auxilliary data (it's JSON). I still need to make it dynamic, but this should work for now.

File: libcontainer/utils/cmsg.c (hunk 2 above)
Comment (wking) [inline libcontainer/utils/cmsg.c]: On Fri, Sep 09, 2016 at 02:24:06PM -0700, Aleksa Sarai wrote:
> > +	/*
> > +	 * We need to send some other data along with ancilliary data, otherwise
> > +	 * the other side won't recieve any data. This is very well-hidden in the
> > +	 * documentation.
> > +	 */
> > +	iov[0].iov_base = file.tag;
> > +	iov[0].iov_len = strlen(file.tag) + 1;
>
> It's because we use `SOCK_STREAM`. You have to read the `NOTES`
> section in `unix(7)`.

Ah:

 To pass file descriptors or credentials over a SOCK_STREAM, you need to
 send  or  receive  at  least  one byte of nonancillary data in the same
 sendmsg(2) or recvmsg(2) call.

**Comment by mrunalp** [comment]
@cyphar Sweet. I'll try to take a look at bats later today or Monday.

**Comment by cyphar** [comment]
Note: `start_hello` *does work* if you run just those tests manually from a shell. As expected, it's the damn `-d` code that's failing. *sigh*

**Comment by cyphar** [comment]
Alright, the reason why `bats` is stalling is because this call (which I wrangled through the `bats` source to find -- it is very hard to debug `bats` because it keeps calling new instances of bash that don't respect `set -x`):

```
output=$(sudo ./runc run -d <whatever>)
```

I'm now trying to figure out why on earth that worked before. My guess is that it was related to whatever magic `--console /dev/pts/ptmx` did (and presumably I'll need to emulate that). My guess is that `--console` was actually causing `/proc/self/fd/{0..2}` to point to `/dev/null` which means that reading will exit immediately.

I'm going to go with implementing `detach && !config.Terminal` as "dup null over fds" because nothing else makes sense here.

**Comment by cyphar** [comment]
It also turns out that I can rebase this branch onto master (not requiring the nsenter PRs). I'm going to force-push that rebased branch soon because there's no point blocking this on the nsenter rewrite (though I'll have to deal with some rebasing on the nsenter PR side).

**Comment by mrunalp** [comment]
Agree with the dup null.

**Comment by cyphar** [comment]
@mrunalp Actually, I managed to make `bats` and the integration work using recvtty. You can't dup `/dev/null` because `sh` doesn't like having `/dev/null` duped over the stdio. But it all works now. :D

**Comment by cyphar** [comment]
Alright @opencontainers/runc-maintainers this is good for proper review now. The only big thing left is for us to discuss `TerminalInfo` and what should be inside it. Everything works, and I've squashed all the commits.

:tada:

**Comment by cyphar** [comment]
Alright @opencontainers/runc-maintainers this is good for proper review now. The only big thing left is for us to discuss `TerminalInfo` and what should be inside it. Everything works, and I've squashed all the commits.

:tada:

**Comment by mrunalp** [comment]
@cyphar Nice 💯 

> @mrunalp Actually, I managed to make bats and the integration work using recvtty. You can't dup /dev/null because sh doesn't like having /dev/null duped over the stdio. But it all works now.

Yeah, shells do require a tty attached. The case where detach is true and terminal is false, we could dup null. If someone is trying to start a shell, they should be required to set terminal to true.

**Comment by cyphar** [comment]
> The case where detach is true and terminal is false, we could dup null. If someone is trying to start a shell, they should be required to set terminal to true.

We can deal with this in a later PR IMO. There's enough code changes here as-is, we can discuss it later (also it's useful to have a reimplementation have similar semantics, so that people can find bugs in the implementation easier).

**Comment by cyphar** [comment]
I've removed all the `[wip]` tags. This is ready for review and merging. PTAL so that we can go ahead with 1.0-rc2. /cc @opencontainers/runc-maintainers

**Comment by mrunalp** [comment]
> We can deal with this in a later PR IMO. There's enough code changes here as-is, we can discuss it later (also it's useful to have a reimplementation have similar semantics, so that people can find bugs in the implementation easier).

Yeah, sure, we can do it in a follow up. Also, it will need more design as we probably would want to address allowing fds as well for better logging support.

**Comment by mrunalp** [comment]
There seems to be an issue with SELinux.
cc: @rhatdan 

```
13270 lsetxattr("/dev/pts/0", "security.selinux", "system_u:system_r:svirt_lxc_net_t:s0:c1,c2", 42, 0) = -1 EOPNOTSUPP (Operation not supported)
```

**Comment by rhatdan** [comment]
Is /dev/pts/0 device already mounted with a context mount?

**Comment by mrunalp** [comment]
@rhatdan This is what I see when I don't set process/mount label in config.json

```
[root@dhcp-16-164 fedora]# runc run 1234
bash-4.3# ls -lZ /dev/pts/
total 0
crw-------. 1 root root unconfined_u:object_r:user_devpts_t:s0 136, 0 Sep 12 17:44 0
crw-rw-rw-. 1 root root unconfined_u:object_r:user_devpts_t:s0   5, 2 Sep 12 17:44 ptmx
bash-4.3# 
```

**Comment by rhatdan** [comment]
Well luckily this is allowed.
```
sesearch -A -s svirt_lxc_net_t -t user_devpts_t
Found 4 semantic av rules:
   allow svirt_sandbox_domain file_type : dir { getattr search open } ; 
   allow svirt_sandbox_domain user_devpts_t : chr_file { ioctl read write getattr lock append } ; 
   allow svirt_sandbox_domain file_type : filesystem getattr ; 
   allow svirt_lxc_net_t user_devpts_t : chr_file { ioctl read write getattr lock append open } ; 
```
 The container should not be changing the label of the device, since this the tty the user owns.  I think we want the label we have.

**Comment by mrunalp** [comment]
@rhatdan IIUC, we shouldn't apply the Selinux label to /dev/pts/0 ?

**Comment by mrunalp** [comment]
@rhatdan okay, we can change the code to not apply the label. Thanks!

**Comment by rhatdan** [comment]
Did it apply it before or is this recent?  This is the TTY of the terminal that the user is executing runc from correct?

**Comment by mrunalp** [comment]
@rhatdan The pty pair is now created inside the container's mount namespace with this PR. Previously we were creating the pair outside and bind mounting the slave to /dev/console (on which I see the container mount label). This PR will fix the exec tty issue and also improve security as we are no longer using external pty slave.

**Comment by mrunalp** [comment]
@rhatdan Without this PR, when we start a script to open a new pty pair in the container, I see that /dev/pts/0 gets the container mount label.

```
sh-4.3# script         
Script started, file is typescript
sh-4.3# ls -lZ /dev/pts/
total 0
crw--w----. 1 root tty  system_u:object_r:svirt_sandbox_file_t:s0:c1,c2 136, 0 Sep 12 18:07 0
crw-rw-rw-. 1 root root system_u:object_r:svirt_sandbox_file_t:s0:c1,c2   5, 2 Sep 12 18:07 ptmx
```

**Comment by mrunalp** [comment]
@cyphar One more thing I noticed is that the group for /dev/pts/0 is `root` now whereas it was `tty` earlier (when it was spawned using script for e.g.). It looks like it is expected to be `tty`

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 11:21:51AM -0700, Mrunal Patel wrote:
> @cyphar One more thing I noticed is that the group for /dev/pts/0 is
> `root` now whereas it was `tty` earlier (when it was spawned using
> script for e.g.). It looks like it is expected to be `tty`

This is one of the things that grantpt(3) [1] is supposed to do for
you when it considers it appropriate (e.g. not when there is no tty
group ;).

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/grantpt.html

**Comment by mrunalp** [comment]
@wking Hmm, I do see that there is `tty` group in both busybox and fedora root filesystems that I tested with. Not sure if we should be setting it ourselves if grantpt doesn't do it. Some apps may fail if it isn't set to `root.tty`.

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 11:38:44AM -0700, Mrunal Patel wrote:
> @wking Hmm, I do see that there is `tty` group in both busybox and
> fedora root filesystems that I tested with. Not sure if we should be
> setting it ourselves if grantpt doesn't do it.

Is runC calling grantpt(3)?  I can't turn it up with grep.  Neither
the POSIX spec nor the Linux man page for grantpt specify the target
group.  I think the idea is that it does what it thinks is reasonable
to grant you permission without you having to worry about these pesky
details ;).

> Some apps may fail if it isn't set to `root.tty`. 

I'd expact this is “if they don't have sufficient access to the
pseudoterminal slave” and not “if the group is not literally ‘tty’”.
For example, containers created by unprivileged users only get a
single user/group mapping, so your choices for a group would be ‘root’
(or whatever you chose to call the single mapped group) and ‘nobody’.

**Comment by rhatdan** [comment]
@mrunalp so it looks like the tty is labeled correctly for use inside the container without attempting to change the label.

**Comment by mrunalp** [comment]
Read some more about this: grantpt isn't necessary on Linux but it is indeed responsible to change the ownership that we can do ourselves in the Go code.

**Comment by cyphar** [comment]
@mrunalp It's important to note that we will have to not use `grantpt` in the rootless container case (or in any case where you aren't mapping enough user IDs for you to have a `tty` group).

**Comment by mrunalp** [comment]
Yeah can't rely on the mappings.

**Comment by cyphar** [comment]
>  @cyphar One more thing I noticed is that the group for /dev/pts/0 is root now whereas it was tty earlier (when it was spawned using script for e.g.). It looks like it is expected to be tty

There's a valid question about whether we should be the ones handling this. For example, when you mount `/dev/pts` using `gid=5` it's pretty clear that you want the owner of everything inside `/dev/pts` to be `gid=5` (we don't handle this correctly right now, but let's ignore that). But this is not clear if you remove that entry (and it's even less clear in the context of user namespaces where `tty` is not mapped).

In addition, the way we used to create console also had the exact same issue:
```
% sudo runc run test
total 0
dr-x------    2 root     root             0 Sep 13 05:21 .
dr-xr-xr-x    9 root     root             0 Sep 13 05:21 ..
lrwx------    1 root     root            64 Sep 13 05:21 0 -> /4
lrwx------    1 root     root            64 Sep 13 05:21 1 -> /4
lrwx------    1 root     root            64 Sep 13 05:21 2 -> /4
ls: /proc/self/fd/3: cannot read link: No such file or directory
lr-x------    1 root     root            64 Sep 13 05:21 3
```

Where now it looks like:

```
% sudo ./runc run test
total 0
dr-x------    2 root     root             0 Sep 13 05:22 .
dr-xr-xr-x    9 root     root             0 Sep 13 05:22 ..
lrwx------    1 root     root            64 Sep 13 05:22 0 -> /dev/pts/0
lrwx------    1 root     root            64 Sep 13 05:22 1 -> /dev/pts/0
lrwx------    1 root     root            64 Sep 13 05:22 2 -> /dev/pts/0
ls: /proc/self/fd/3: cannot read link: No such file or directory
lr-x------    1 root     root            64 Sep 13 05:22 3
```

**Comment by cyphar** [comment]
Also, regarding the SELinux stuff, my guess is that the reason that `script` has the right SELinux label but this code doesn't is because `script` is running after the container has gone through setup -- this console code runs earlier.

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 09:38:01PM -0700, Aleksa Sarai wrote:
> @mrunalp It's important to note that we will have to not use
> `grantpt` in the rootless container case (or in any case where you
> aren't mapping enough user IDs for you to have a `tty` group).

That's not quite right.  It's import to not try and change the group
to `tty` if that group doesn't exist or is nobody.  But POSIX
explicitly says “unspecified group ID” [1] (so it does not require
‘tty’) and glibc's implementation considers the no-tty case (see the
tty_gid setup around [2]).

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/grantpt.html
[2]: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/grantpt.c;h=8bbab4afba4c9d1e47c89a0149ac1f507544a7f2;hb=fdfc9260b61d3d72541f18104d24c7bcb0ce5ca2#l138

**Comment by cyphar** [comment]
> That's not quite right. It's import to not try and change the group to `tty` if that group doesn't exist or is nobody. But POSIX explicitly says “unspecified group ID” [1] (so it does not require ‘tty’) and glibc's implementation considers the no-tty case (see the tty_gid setup around [2]).

We can just use libcontainer/user to implement it. But glibc doesn't have to deal with the case where there is an `/etc/passwd` entry for `tty` but that user is not mapped into the container (so `chown` will fail). I can just change the code so that it will *attempt* to change the owner and ignore failures. This however touches on the "should `consoleSetup` be run before or after the post-mount hooks are fired". If we run it before, then the hooks can tweak the console (but then we can't be sure that /etc/passwd is what we wanted). Should we make a second `consoleTweak` function which just changes the owner after the post-mount hooks?

**Comment by wking** [comment]
On Tue, Sep 13, 2016 at 01:01:29PM -0700, Aleksa Sarai wrote:
> But glibc doesn't have to deal with the case where there is an
> `/etc/passwd` entry for `tty` but that user is not mapped into the
> container (so `chown` will fail).

ccon just ignores EPERM from grantpt.  But you could also raise the
error, since containers should not be defining a ‘tty’ group if they
are not mapping it.  Ignoring the EPERM just lets sloppy containers
slip through.

> I can just change the code so that it will *attempt* to change the
> owner and ignore failures. This however touches on the "should
> `consoleSetup` be run before or after the post-mount hooks are
> fired".

I think it's pretty clear that console setup should happen *after*
mount setup.  Console setup isn't really part of the container, and
the only reason to include it in ‘create’ (instead of pushing it to
‘start’) is that it makes cleaner checkpoints of
created-but-not-started containers if you've already dropped your old
stdio based on out-of-container devices.  Ccon (which handles all of
this in ‘start’ because it optionally accepts the ‘process’ JSON at
that time) handles this after the pre-start hooks just before exec'ing
the user-specified function [1].

[1]: https://github.com/wking/ccon/tree/v0.4.0#lifecycle

**Comment by mrunalp** [comment]
@cyphar Fix for SELinux https://github.com/opencontainers/runc/commit/f86ae7a58038813ab685f29e6136cf836d15ee8e 
(Tested working on Fedora 24).

**Comment by mrunalp** [comment]
@rhatdan It already had the correct label as you pointed out.

```
[root@dhcp-16-164 fedora]# runc run 1234
sh-4.3# ls -lZ /dev/pts/
total 0
crw-------. 1 root root system_u:object_r:svirt_sandbox_file_t:s0:c1,c2 136, 0 Sep 13 22:12 0
crw-rw-rw-. 1 root root system_u:object_r:svirt_sandbox_file_t:s0:c1,c2   5, 2 Sep 13 22:12 ptmx
sh-4.3# 
```

**Comment by cyphar** [comment]
@wking 

>ccon just ignores EPERM from grantpt. But you could also raise the error, since containers should not be defining a ‘tty’ group if they are not mapping it. Ignoring the EPERM just lets sloppy containers slip through.

Where "sloppy containers" means any rootless container with a standard rootfs? Or a standard user namespaced container with an `/etc/passwd` from somewhere else? IMO in runC we put **way** too much emphasis on what the value inside `/etc/passwd` for a container rootfs is -- this would be an additional example of that. I think I'm going to go with ignoring EPERM (maybe emitting a warning), since it will make it more frustrating for people to use rootless containers. And ultimately, it doesn't _really_ matter.

However, the question of whether or not a `gid=X` flag for the `/dev/pts` mount should override the `/etc/passwd` setup has not been answered yet. Since a user can explicitly state a `gid=X` flag then maybe we should be obeying that *over* anything else (also, why on earth doesn't `gid=X` do anything with `/dev/pts` -- why the hell are we doing this manually anyway)?

**Comment by cyphar** [comment]
@mrunalp I've cherry-picked your change into this branch -- thanks. :smile:

**Comment by wking** [comment]
On Tue, Sep 13, 2016 at 05:48:03PM -0700, Aleksa Sarai wrote:
> > ccon just ignores EPERM from grantpt. But you could also raise the
> > error, since containers should not be defining a ‘tty’ group if
> > they are not mapping it. Ignoring the EPERM just lets sloppy
> > containers slip through.
>
> Where "sloppy containers" means any rootless container with a
> standard rootfs?

Yeah.  If you're setting up a container that only maps a single
user/group and you have more than one entry in /etc/passwd or
/etc/group you're doing it wrong.  So I'm fine erroring out on the
EPERM.  Of course, it's not that big a deal, which is why I'm also ok
with (and ccon does) ignoring the EPERM.

> IMO in runC we put **way** too much emphasis on what the value
> inside `/etc/passwd` for a container rootfs is -- this would be an
> additional example of that.

Where else do you expect to get the number for the tty group if you
don't use /etc/group or getent?

> I think I'm going to go with ignoring EPERM (maybe emitting a
> warning), since it will make it more frustrating for people to use
> rootless containers.

This is fine with me.

> However, the question of whether or not a `gid=X` flag for the
> `/dev/pts` mount should override the `/etc/passwd` setup has not
> been answered yet. Since a user can explicitly state a `gid=X` flag
> then maybe we should be obeying that *over* anything else (also, why
> on earth doesn't `gid=X` do anything with `/dev/pts` -- why the hell
> are we doing this manually anyway)?

From mount(8):

  Mount options for devpts
    …
    uid=value and gid=value
      This sets the owner or the group of newly created PTYs to the
      specified values.  When nothing is specified, they will be set
      to the UID and GID of the creating process.  For example, if
      there is a tty group with GID 5, then gid=5 will cause newly
      created PTYs to belong to the tty group.

So whoever mounts the new devpts should be setting the owner/group of
the new ptmx to control who can create new pseudoterminals.  And they
should be setting uid/gid mount options to control who can access the
slaves.  This is the same as the difference between the mode and
ptxmode options, except there are no ptxuid/ptxgid analogs.

**Comment by cyphar** [comment]
> Yeah. If you're setting up a container that only maps a single user/group and you have more than one entry in /etc/passwd or /etc/group you're doing it wrong. So I'm fine erroring out on the EPERM. Of course, it's not that big a deal, which is why I'm also ok with (and ccon does) ignoring the EPERM.

I disagree. The rootfs is not the source of truth for the container, the `config.json` file is.

> From mount(8): Mount options for devpts … uid=value and gid=value This sets the owner or the group of newly created PTYs to the specified values. When nothing is specified, they will be set to the UID and GID of the creating process. For example, if there is a tty group with GID 5, then gid=5 will cause newly created PTYs to belong to the tty group. So whoever mounts the new devpts should be setting the owner/group of the new ptmx to control who can create new pseudoterminals. And they should be setting uid/gid mount options to control who can access the slaves. This is the same as the difference between the mode and ptxmode options, except there are no ptxuid/ptxgid analogs.

I realised that the reason this happens is because the old console code manually changes the owner of the console after creating it (this always happened). I can fix it so we don't do that but presumably @crosbymichael had a reason for doing that?

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 12:40:38AM -0700, Aleksa Sarai wrote:
> > Yeah. If you're setting up a container that only maps a single
> > user/group and you have more than one entry in /etc/passwd or
> > /etc/group you're doing it wrong. So I'm fine erroring out on the
> > EPERM. Of course, it's not that big a deal, which is why I'm also
> > ok with (and ccon does) ignoring the EPERM.
>
> I disagree. The rootfs is not the source of truth for the container,
> the `config.json` file is.

config.json references the rootfs (and any mounts over it).  What
source-of-truth distinction are you trying to draw between the two?
Anything that the rootfs is saying, the config is vouching for (by
referencing that rootfs).

**Comment by cyphar** [comment]
I'll be honest, the main reason I don't want to make us fail because of `/etc/passwd` (or `/etc/group`) is because I want rootless containers to work with regular images -- and I see no legitimate reason why we would make such a trivial roadblock for users.

The reason (IMO) why we use `uid` and `gid` instead of `userSpec` to specify the user a container process will run as is to avoid this problem. Similarly, why are we going to force users to modify their rootfs just so they can change a configuration option in `config.json`? How is that not user-hostile?

**Comment by cyphar** [comment]
> 
> config.json references the rootfs (and any mounts over it). What source-of-truth distinction are you trying to draw between the two?

From what I understand, you're saying that "we should fail to start a container if `/etc/passwd` contains entries that are not mappable for the `config.json` mappings." This is **you** stating that the rootfs is a more important source of truth than the `config.json`. I don't understand the reason for the limitation -- it's so incredibly arbitrary (and we already have an entry in `config.json` that tells us everything we need to know -- what is the `gid=X` that we're mounting `devpts` with). So I say that we abandon this "let's implement `grantpt`" discussion and just let the `config.json` tell us what to do (and the kernel can handle itself). Deal?

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 01:34:16AM -0700, Aleksa Sarai wrote:
> I'll be honest, the main reason I don't want to make us fail because
> of `/etc/passwd` (or `/etc/group`) is because I want rootless
> containers to work with regular images -- and I see no legitimate
> reason why we would make such a trivial roadblock for users.

Sure.  I'm fine both ways [1], and ccon (where I don't have to build
consensus around design decisions) ignores the EPERM [2].

> The reason (IMO) why we use `uid` and `gid` instead of `userSpec` to
> specify the user a container process will run as is to avoid this
> problem.

This seems orthogonal to whether you ignore EPERM or not.  And there
is a difference between reading /etc/group before you call setgid and
reading it during grantpt or similar.  The former opens the door to
permission escalation because it's happening before you drop into the
possibly-less-privileged group, while the latter can happen entirely
after you're containerized (with the same permissions as the
user-specified code will have).

> Similarly, why are we going to force users to modify their rootfs
> just so they can change a configuration option in `config.json`? How
> is that not user-hostile?

Again, I don't see a need to error out on grantpt EPERM.  Configs that
trigger that EPERM are still sloppy, but it doesn't need to be fatal
sloppiness.  On the other hand, there is also a benefit to erroring
out on EPERM, because it drives home the fact that there is only one
mapped group inside the container's user namespace.  If a user is
intending to use multiple groups for *other* purposes, it can be nice
to fail fast with a clear error message to expose that assumption.  So
benefits and drawbacks either way, and I don't have a strong opinion
on which way is better.

[1]: https://github.com/opencontainers/runc/pull/1018#issuecomment-246907818
[2]: https://github.com/opencontainers/runc/pull/1018#issuecomment-246822625

**Comment by cyphar** [comment]
> On the other hand, there is also a benefit to erroring out on EPERM, because it drives home the fact that there is only one mapped group inside the container's user namespace.

My new method (just letting `gid=X` handle it) has the benefit that the mount will fail if a user tries to set the `gid` argument. But instead of being an issue with `/etc/passwd`, it's a legitimate issue (the kernel will actually refuse to mount the filesystem).

**Comment by cyphar** [comment]
@mrunalp @wking There, commit 5caf3898aedfd6d1a32d25b3849258d8488b9e90 should fix the issue. I should probably add a test for this...

**Comment by wking** [comment]
On Wed, Sep 14, 2016 at 01:38:27AM -0700, Aleksa Sarai wrote:
> > config.json references the rootfs (and any mounts over it). What
> > source-of-truth distinction are you trying to draw between the
> > two?
>
> From what I understand, you're saying that "we should fail to start
> a container if `/etc/passwd` contains entries that are not mappable
> for the `config.json` mappings."

I'm suggesting we just call grantpt (e.g. as provided by glibc) and
that we error (or not) on any EPERM it returns [1].  Erroring if there
are unmapped entries in /etc/passwd or /etc/group is possible (and a
logical position if you're taking the fail-fast route [1]), but I'd
rather entirely avoid touching those files directly.

> I don't understand the reason for the limitation -- it's so
> incredibly arbitrary…

The reason is that the kernel only lets you map a single user, so all
entries besides the first are meaningless.  Ignoring meaningless
things is a sensible approach (they are unlikely to effect the
container function) and erroring on meaningless things is another
sensible approach (they likely point out holes in the config author's
understanding).  I don't have a strong opinion, and you seem in favor
of ignoring the EPERM, so let's do that ;).

> (and we already have an entry in `config.json` that tells us
> everything we need to know -- what is the `gid=X` that we're
> mounting `devpts` with)

Agreed.  If the user can setup their devpts with mode, uid, and gid to
do everything grantpt does, as long as they don't mind hardcoding the
UID (grantpt uses the real UID of the calling process [3]).  For
unprivileged user namespaces, there's only going to be one valid UID,
so there is no important distinction.  But I don't see any harm in
calling grantpt and unlockpt as recommended by pts(4) and pty(7) and
leaving it to the stdlib authors to figure out what to do (if
anything) for us ;).

[1]: https://github.com/opencontainers/runc/pull/1018#issuecomment-246947037
[2]: https://github.com/opencontainers/runc/pull/1018#issuecomment-246907818
[3]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/grantpt.html

File: libcontainer/console_linux.go [hunk 7]
```diff
@@ -13,7 +12,7 @@ import (
 // NewConsole returns an initalized console that can be used within a container by copying bytes
 // from the master side to the slave that is attached as the tty for the container's init process.
 func NewConsole(uid, gid int) (Console, error) {
-	master, err := os.OpenFile("/dev/ptmx", syscall.O_RDWR|syscall.O_NOCTTY|syscall.O_CLOEXEC, 0)
+	master, err := os.OpenFile("/dev/pts/ptmx", syscall.O_RDWR|syscall.O_NOCTTY|syscall.O_CLOEXEC, 0)
```
Comment (wking) [inline libcontainer/console_linux.go]: `pts(4)`, `pty(7)`, `posix_openpt(3)`, and the [runtime-spec][1] etc. all talk about `/dev/ptmx` for the UNIX 98 master clone device.  I think you should leave this path alone here, and (wherever runC sets up those default devices) [use a symlink][2] to the [required devpts mount][3].  If runC doesn't handle the default devices/mounts yet, you should still be able to leave this path alone and rely on however the path was working until now ;).

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc1/config-linux.md#devices
[2]: https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
[3]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc1/config-linux.md#default-file-systems

Comment (cyphar) [inline libcontainer/console_linux.go]: Fair enough. This change came from some testing I was doing (in the host, `/dev/ptmx` and `/dev/pts/ptmx` have different semantics which made me suspicious of the legacy path). Ultimately, it doesn't _really_ matter since in most cases we're setting up the `/dev/ptmx` symlink anyway.

File: Makefile [hunk 8]
```diff
@@ -1,7 +1,8 @@
-.PHONY: dbuild man \
+.PHONY: all dbuild man \
```
Comment (mikebrow) [inline Makefile]: Should your new target "shell" also be in the .PHONY list?

File: contrib/cmd/recvtty/recvtty.go [hunk 9]
```diff
@@ -0,0 +1,248 @@
...
+// and will be populated by the Makefile
+var gitCommit = ""
+
+const (
+	usage = `Open Container Initiative contrib/cmd/recvtty
+
+recvtty is a reference implementation of a consumer of runC's --console-socket
+API. It has two main modes of operation:
+
+  * single: Only permit one terminal to be sent to the socket, which is
```
Comment (mikebrow) [inline contrib/cmd/recvtty/recvtty.go]: From the code below it looks like single is the default.  Should probably say that here.

File: contrib/cmd/recvtty/recvtty.go [hunk 10]
```diff
@@ -0,0 +1,248 @@
...
+	then hooked up to the stdio of the recvtty process. This is useful
+	for rudimentary shell management of a container.
+
+  * null: Permit as many terminals to be sent to the socket, but they
+	are read to /dev/null. This is used for testing, and imitates the
+	old runC API's --console=/dev/pts/ptmx hack which would allow for a
+	similar trick. Essentially this is useful if you want to create a
+	full terminal for the init process, but also want to detach the
+	container. Don't use this unless you know what you're doing.
```
Comment (mikebrow) [inline contrib/cmd/recvtty/recvtty.go]: The warning not to use "null" unless you know what you are doing, doesn't really explain what could go wrong if you do or why the warning is here.

File: contrib/cmd/recvtty/recvtty.go [hunk 11]
```diff
@@ -0,0 +1,248 @@
...
+	if gitCommit != "" {
+		v = append(v, fmt.Sprintf("commit: %s", gitCommit))
+	}
+	app.Version = strings.Join(v, "\n")
+
+	// Set the flags.
+	app.Flags = []cli.Flag{
+		cli.StringFlag{
+			Name:  "mode, m",
+			Value: "single",
```
Comment (mikebrow) [inline contrib/cmd/recvtty/recvtty.go]: Given null is closer to the prior use cases for runc, is making "single" the best default choice here, or just a limitation given the above mentioned stdin limitation for this mockup client?

File: create.go [hunk 12]
```diff
@@ -29,9 +29,9 @@ command(s) that get executed on start, edit the args parameter of the spec. See
 			Usage: `path to the root of the bundle directory, defaults to the current directory`,
 		},
 		cli.StringFlag{
-			Name:  "console",
+			Name:  "console-socket",
 			Value: "",
-			Usage: "specify the pty slave path for use with the container",
+			Usage: "specify an AF_UNIX socket to send the master fd through",
```
Comment (mikebrow) [inline create.go]: Can this be made more descriptive.. send the master fd through sounds like the perspective is the container vs. the user / client application who is receiving / attaching through the specified socket.

**Comment by mikebrow** [comment]
General comment / question: Would it make more sense to have a new runC command to host the client side of the console-socket, rather than having to use another program like recvtty?

File: contrib/cmd/recvtty/recvtty.go (hunk 11 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: Just because we used a `--console /dev/pts/ptmx` to hack around detaching inside the tests doesn't mean that was the _intended_ usecase for `--console`. The original purpose of `--console` was to allow a higher level manager of runC to directly access the console file descriptor without runC getting in the way.

File: libcontainer/console_windows.go [hunk 13]
```diff
@@ -1,7 +1,8 @@
 package libcontainer
 
-// NewConsole returns an initalized console that can be used within a container
-func NewConsole(uid, gid int) (Console, error) {
+<<<<<<< HEAD
```
Comment (ereslibre) [inline libcontainer/console_windows.go]: I guess that's bad news for Windows users :wink:

Comment (cyphar) [inline libcontainer/console_windows.go]: :stuck_out_tongue_winking_eye:

**Comment by cyphar** [comment]
@mikebrow

> Would it make more sense to have a new runC command to host the client side of the console-socket, rather than having to use another program like recvtty? 

Maybe, maybe not. The reason I made a separate program for it is because the `recvtty` is more of a reference implementation than an actual tool. Also, having a command to be a consumer for `--console-socket` is not really in line IMO with the rest of the runC commands (which are all related with administration of containers). It also makes it clearer to people wanting to implement this how they should implement it as a separate binary.

**Comment by mikebrow** [comment]
@cyphar right, and I like the example program for that purpose.  How about some sort of runc default where if the console-socket is not specified, but is required, runc creates a unique socket that is based on the container id and hosts the console?

**Comment by cyphar** [comment]
`--console-socket` is only required for `--detach`. So in that instance AFAICS there's no way for runC to "host the console" because it will have exited in the only case where you need to set `--console-socket`.

File: contrib/cmd/recvtty/recvtty.go (hunk 11 above)
Comment (mikebrow) [inline contrib/cmd/recvtty/recvtty.go]: ok hack removed got it...

**Comment by mikebrow** [comment]
@cyphar ...my fault for putting two things in there.  Let me rephrase... 1) should we default the socket to container-id.soc, just a thought to make it easier to use debug etc. 2) While I get that -d (detach) needs to return to the caller I was really thinking about runc exec.  I may be somewhat confused by the runc exec command having the --console-socket option.. but then I see in the integration test case tests/integration/exec.bats the exec portion wan't changes to point to the console-socket, so I should probably just pull your PR and test it out :-)

**Comment by cyphar** [comment]
@mikebrow `--console-socket` on `exec` exists because you can do `runc exec -d` -- so it's the same argument. Currently we don't test `exec` detaching so there was no need to use the option.

File: contrib/cmd/recvtty/recvtty.go (hunk 9 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: `recvtty -h` will already show the default.

File: contrib/cmd/recvtty/recvtty.go (hunk 10 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: I've replaced this with `you probably should use this unless you're doing something like our bats integration tests`.

File: create.go (hunk 12 above)
Comment (cyphar) [inline create.go]: Fixed.

File: tests/integration/helpers.bash [hunk 14]
```diff
@@ -142,21 +146,40 @@ function testcontainer() {
   [[ "${output}" == *"$2"* ]]
 }
 
+function setup_recvtty() {
+	# Clean up the console socket.
```
Comment (cyphar) [inline tests/integration/helpers.bash]: You're right. Fixed.

File: Makefile (hunk 8 above)
Comment (cyphar) [inline Makefile]: Fixed.

**Comment by mikebrow** [comment]
@cyphar Thanks! I forgot there was a detach option for exec.

File: libcontainer/utils/cmsg.c [hunk 15]
```diff
@@ -0,0 +1,146 @@
...
+	if (!cmsg)
+		error("recvfd: got NULL from CMSG_FIRSTHDR");
+	if (cmsg->cmsg_level != SOL_SOCKET)
+		error("recvfd: expected SOL_SOCKET in cmsg: %d", cmsg->cmsg_level);
+	if (cmsg->cmsg_type != SCM_RIGHTS)
+		error("recvfd: expected SCM_RIGHTS in cmsg: %d", cmsg->cmsg_type);
+	if (cmsg->cmsg_len != CMSG_LEN(sizeof(int)))
+		error("recvfd: expected correct CMSG_LEN in cmsg: %d", cmsg->cmsg_len);
```
Comment (mikebrow) [inline libcontainer/utils/cmsg.c]: cmsg->cmsg_len
Should read: `error("recvfd: expected correct CMSG_LEN in cmsg: %lu", cmsg->cmsg_len);`

Comment (cyphar) [inline libcontainer/utils/cmsg.c]: Fixed.

**Comment by mikebrow** [comment]
@cyphar I get the following two new errors when running the Integration tests with this branch: 
from start_hello.bats "runc run; "runc run ({u,g}id != 0)"; 
these two tests fail with no output...

**Comment by cyphar** [comment]
@mikebrow That's odd. Can you give me an `strace -f` log of the runC commands run inside that integration tests. I _believe_ that I solved all of the races with sending the console, but I might be mistaken. Does the same issue happen with old versions of this branch (in case you had the chance to test them)?

**Comment by mrunalp** [comment]
I am hitting some failures when testing on a RHEL 7 server. See https://gist.github.com/anonymous/4771b162fdbf07a4097c51176daa852c

**Comment by mikebrow** [comment]
@cyphar just to add `runc run hello-world` works fine with 2 cpus.

**Comment by mikebrow** [comment]
@cyphar after reboot and rebuild the issue with no hello text no longer reproduces when I'm running hello-world standalone. But hello-world is still failing in the integration test.

File: create.go (hunk 12 above)
Comment (mikebrow) [inline create.go]: Change looks good!

**Comment by cyphar** [comment]
@mikebrow It's possible that the reason that the tests fail with `strace` is because of #1025. Can you reproduce the issue on `master`? Looking at the `strace` logs it looks like the console fd has been passed correctly, but the runC parent process isn't copying stdio properly?

**Comment by mikebrow** [comment]
Does not reproduce on master.

**Comment by cyphar** [comment]
@mikebrow What kernel / distribution are you using (so I can set up a test VM to reproduce this in)? I can't reproduce it on openSUSE Tumbleweed 20160916 (`Linux 4.7.2-2`).

**Comment by mikebrow** [comment]
@cyphar off a hunch I switched to building with the make dbuild target and all tests now pass.

**Comment by cyphar** [comment]
@mikebrow That doesn't sound good. It might a Go version issue then. What is the version of Go you're using on your host (compared to the version inside `make dbuild`)?

**Comment by cyphar** [comment]
@mrunalp As @mikebrow mentioned, his problem was fixed by using `make dbuild`. Now I realise this probably is not a solution for you (since you need to test things using RHEL as the build machine) but can you at least verify that `make dbuild` does solve the problem for you? If so, we need to figure out if it's a Go version issue (which is my suspicion) or if it's some other issue with the build process.

File: Makefile [hunk 16]
```diff
@@ -28,13 +29,21 @@ VERSION := ${shell cat ./VERSION}
...
-all: $(RUNC_LINK)
+.DEFAULT: runc
+
+all: runc recvtty
+
+runc: $(SOURCES) | $(RUNC_LINK)
 	go build -i -ldflags "-X main.gitCommit=${COMMIT} -X main.version=${VERSION}" -tags "$(BUILDTAGS)" -o runc .
 
-static: $(RUNC_LINK)
+recvtty: $(SOURCES) | $(RUNC_LINK)
```
Comment (mikebrow) [inline Makefile]: Since you are adding an extra binary build target, we need to add another copy to the dbuild target: 
```
diff --git a/Makefile b/Makefile
index 29786f8..1cbdd58 100644
--- a/Makefile
+++ b/Makefile
@@ -12,6 +12,7 @@ PROJECT := github.com/opencontainers/runc
 TEST_DOCKERFILE := script/test_Dockerfile
 BUILDTAGS := seccomp
 RUNC_BUILD_PATH := /go/src/github.com/opencontainers/runc/runc
+RECVTTY_BUILD_PATH := /go/src/github.com/opencontainers/runc/recvtty
 RUNC_INSTANCE := runc_dev
 COMMIT_NO := $(shell git rev-parse HEAD 2> /dev/null || true)
 COMMIT := $(if $(shell git status --porcelain --untracked-files=no),"${COMMIT_NO}-dirty","${COMMIT_NO}")
@@ -75,6 +76,7 @@ $(RUNC_LINK):
 dbuild: runcimage
        docker run --name=$(RUNC_INSTANCE) --privileged $(RUNC_IMAGE) make
        docker cp $(RUNC_INSTANCE):$(RUNC_BUILD_PATH) .
+       docker cp $(RUNC_INSTANCE):$(RECVTTY_BUILD_PATH) .
        docker rm $(RUNC_INSTANCE)
 
 lint:

```

**Comment by mrunalp** [comment]
Yeah I will try that out and let you know.

**Comment by mikebrow** [comment]
@cyphar my local go version is go1.6.2 the version in dbuild is go1.7

File: Makefile (hunk 16 above)
Comment (cyphar) [inline Makefile]: Cheers. Fixed.

**Comment by mikebrow** [comment]
With the dbuild version of runc & recvtty I'm getting random failures for runc exec:
terminal 1:
```
mike@mike-VirtualBox:~/go/src/testbusybox$ ../github.com/opencontainers/runc/recvtty foo.sock
** Got a masterfd with tag 'test_busybox' **
/ # 
```
terminal 2
```
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc run -d --console-socket foo.sock test_busybox
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
mike@mike-VirtualBox:~/go/src/testbusybox$ sudo runc exec test_busybox echo Hello from exec
Hello from exec

```

**Comment by mikebrow** [comment]
sudo strace -f -o "food01.out" runc exec test_busybox echo Hello from exec 2>&1 >/tmp/foo01.out
https://gist.github.com/mikebrow/334dde90bcabdf4235c503a33ed6fbb3

**Comment by mrunalp** [comment]
@cyphar okay, down to one bats failure on RHEL 7.2 now

```
# (in test file tests/integration/update.bats, line 98)
#   `[ "$status" -eq 0 ]' failed
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED
# runc spec (status=0):
# 
# ** Got a masterfd with tag 'test_update' **
# runc run -d --console-socket /tmp/console.sock test_update (status=0):
# 
# runc state test_update (status=0):
# {
#   "ociVersion": "1.0.0-rc1-dev",
#   "id": "test_update",
#   "pid": 23918,
#   "bundlePath": "/tmp/busyboxtest",
#   "rootfsPath": "/tmp/busyboxtest/rootfs",
#   "status": "running",
#   "created": "2016-09-19T16:39:38.642667185Z"
# }
# runc update test_update --blkio-weight 500 (status=0):
# 
# runc update test_update --cpu-period 900000 (status=0):
# 
# runc update test_update --cpu-quota 600000 (status=0):
# 
# runc update test_update --cpu-share 200 (status=0):
# 
# runc update test_update --cpuset-cpus 1 (status=1):
# failed to write 1 to cpuset.cpus: write /sys/fs/cgroup/cpuset/runc-update-integration-test/cpuset.cpus: numerical result out of range
# runc list (status=0):
# ID            PID         STATUS      BUNDLE             CREATED
# test_update   23918       running     /tmp/busyboxtest   2016-09-19T16:39:38.642667185Z
# runc kill test_update KILL (status=0):
# 
# runc delete test_update (status=0):
# 
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED
```

**Comment by mikebrow** [comment]
@mrunalp that's the single cpu issue see #1050 / #1052

**Comment by mrunalp** [comment]
Cool. Thanks!

**Comment by cyphar** [comment]
@opencontainers/runc-maintainers I've squashed the commits and rebased onto master. This should mean that all of the issues have been fixed. PTAL. Gogogo. :recycle: :tea: :green_heart: :green_book: :green_apple:.

**Comment by mikebrow** [comment]
@cyphar all my reported issues are fixed. Will continue going through my source code review. But this looks really good.

**Comment by mrunalp** [comment]
This looks fine overall. I am testing it across Fedora, RHEL, etc with different configs.

File: contrib/cmd/recvtty/recvtty.go [hunk 17]
```diff
@@ -0,0 +1,247 @@
...
+	if err != nil {
+		bail(err)
+	}
+
+	// Print the file descriptor tag.
+	ti, err := libcontainer.GetTerminalInfo(master.Name())
+	if err != nil {
+		bail(err)
+	}
+	fmt.Fprintf(os.Stderr, "** Got a masterfd with tag '%s' **\n", ti.Container)
```
Comment (hqhq) [inline contrib/cmd/recvtty/recvtty.go]: Is this a leftover debug info?

File: contrib/cmd/recvtty/recvtty.go [hunk 18]
```diff
@@ -0,0 +1,247 @@
...
+			if err != nil {
+				return
+			}
+
+			// Print the file descriptor tag.
+			ti, err := libcontainer.GetTerminalInfo(master.Name())
+			if err != nil {
+				bail(err)
+			}
+			fmt.Fprintf(os.Stderr, "** Got a masterfd with tag '%s' **\n", ti.Container)
```
Comment (hqhq) [inline contrib/cmd/recvtty/recvtty.go]: Same here, if we want to log this, why into stderr?

File: libcontainer/utils/cmsg.h [hunk 19]
```diff
@@ -0,0 +1,35 @@
...
+#if !defined(CMSG_H)
+#define CMSG_H
+
+#include <sys/types.h>
+
+/* TODO: Implement this properly with MSG_PEEK. */
+#define TAG_BUFFER 4096
+
+struct file_t {
+	char *tag;
```
Comment (hqhq) [inline libcontainer/utils/cmsg.h]: Any reasons why call it `tag` instead of `name`?

File: libcontainer/console.go [hunk 20]
```diff
@@ -11,5 +17,59 @@ type Console interface {
...
-	Fd() uintptr
+	File() *os.File
+}
+
+const (
+	TerminalInfoVersion = 1
+	TerminalInfoType    = "terminal"
+)
+
+// TerminalInfo is the structure which is passed as the nonancilliary data
```
Comment (hqhq) [inline libcontainer/console.go]: s/nonancilliary/nonancillary

https://en.wiktionary.org/wiki/ancilliary
I googled and found out it's not any BE & UE differences right ;)

File: libcontainer/utils/cmsg.c [hunk 21]
```diff
@@ -0,0 +1,146 @@
...
+	int *fdptr;
+	int ret;
+
+	union {
+		char buf[CMSG_SPACE(sizeof(file.fd))];
+		struct cmsghdr align;
+	} u;
+
+	/*
+	 * We need to send some other data along with ancilliary data, otherwise
```
Comment (hqhq) [inline libcontainer/utils/cmsg.c]: s/ancilliary/ancillary

File: libcontainer/utils/cmsg.c [hunk 22]
```diff
@@ -0,0 +1,146 @@
...
+	} u;
+
+	/* Allocate a buffer. */
+	/* TODO: Make this dynamic with MSG_PEEK. */
+	file.tag = malloc(TAG_BUFFER);
+	if (!file.tag)
+		error("recvfd: failed to allocate file.tag buffer\n");
+
+	/*
+	 * We need to "recieve" the non-ancilliary data even though we don't plan
```
Comment (hqhq) [inline libcontainer/utils/cmsg.c]: s/non-ancilliary/non-ancillary

File: libcontainer/console_linux.go [hunk 23]
```diff
@@ -75,21 +58,17 @@ func (c *linuxConsole) Close() error {
 
 // mount initializes the console inside the rootfs mounting with the specified mount label
 // and applying the correct ownership of the console.
-func (c *linuxConsole) mount(rootfs, mountLabel string) error {
+func (c *linuxConsole) mount(mountLabel string) error {
 	oldMask := syscall.Umask(0000)
 	defer syscall.Umask(oldMask)
-	if err := label.SetFileLabel(c.slavePath, mountLabel); err != nil {
```
Comment (hqhq) [inline libcontainer/console_linux.go]: why remove this?

File: libcontainer/sync.go [hunk 24]
```diff
@@ -0,0 +1,110 @@
...
+// during container setup. They come in pairs (with procError being a generic
+// response which is followed by a &genericError).
+//
+// [  child  ] <-> [   parent   ]
+//
+// procHooks   --> [run hooks]
+//             <-- procResume
+//
+// procConsole -->
+//             <-- procRequestFd
```
Comment (hqhq) [inline libcontainer/sync.go]: procConsoleReq?

File: libcontainer/sync.go [hunk 25]
```diff
@@ -0,0 +1,110 @@
...
+//  [send(fd)] --> [recv(fd)]
+//             <-- procAckFd
```
Comment (hqhq) [inline libcontainer/sync.go]: procConsoleAck?

File: libcontainer/init_linux.go [hunk 26]
```diff
@@ -262,11 +314,17 @@ func fixStdioPermissions(u *user.ExecUser) error {
...
 			continue
 		}
-		if err := syscall.Fchown(int(fd), u.Uid, u.Gid); err != nil {
+		// We only change the uid owner (as it is possible for the mount to
+		// prefer a different gid, and there's no reason for us to change it).
+		// The reason why we don't just leave the default uid=X mount setup is
+		// that users expect to be able to actually use their console. Without
+		// this code, you couldn't effectively run as a non-root user inside a
+		// container and also have a console set up.
+		if err := syscall.Fchown(int(fd), u.Uid, int(s.Gid)); err != nil {
```
Comment (hqhq) [inline libcontainer/init_linux.go]: I don't quite understand this, so we depend on `gid=x` set by mount options? What if it's not set in mount options while it's set specifically in `User`?

File: libcontainer/rootfs_linux.go [hunk 27]
```diff
@@ -88,11 +86,19 @@ func setupRootfs(config *configs.Config, console *linuxConsole, pipe io.ReadWrit
...
 			return newSystemErrorWithCause(err, "reopening /dev/null inside container")
 		}
 	}
+
+	return nil
+}
+
+// finalizeRootfs actually switches the root of the process and sets anything
+// to ro if necessary. You must call prepareRootfs first.
+func finalizeRootfs(config *configs.Config) (err error) {
```
Comment (hqhq) [inline libcontainer/rootfs_linux.go]: `PivotRoot` is called in `prepareRootfs`, is this intentional?

File: libcontainer/standard_init_linux.go [hunk 28]
```diff
@@ -79,12 +66,41 @@ func (l *linuxStandardInit) Init() error {
...
+		if err := prepareRootfs(l.config.Config); err != nil {
+			return err
+		}
+	}
+
+	// Signal the parent to run the pre-start hooks.
+	// The hooks are run after the mounts are setup, but before we switch to the new
+	// root, so that the old root is still available in the hooks for any mount
+	// manipulations.
+	if err := syncParentHooks(l.pipe); err != nil {
```
Comment (hqhq) [inline libcontainer/standard_init_linux.go]: It'll broken because we already pivoted in `prepareRootfs`, so I think that's not intentional.

File: contrib/cmd/recvtty/recvtty.go (hunk 17 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: I kept it in so that if the tests fail we can figure out whether recvtty got a somewhat reasonable message. I can remove it if you want (but it's kinda handy to show that the `--console-socket` API does give some information about the container that the socket comes from).

File: contrib/cmd/recvtty/recvtty.go (hunk 18 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: Same as the other one. If you want, I can move them to `stdout`?

File: libcontainer/utils/cmsg.h (hunk 19 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.h]: No real reason. I'll switch the name.

File: libcontainer/console_linux.go (hunk 23 above)
Comment (cyphar) [inline libcontainer/console_linux.go]: Ask @mrunalp, it's his patch. From my understanding it's because the console is already tagged by SELinux if you open it from inside the container (if you open it from outside you have to tag it manually which is what the code used to do)?

File: libcontainer/init_linux.go (hunk 26 above)
Comment (cyphar) [inline libcontainer/init_linux.go]: If `gid=x` is not specified, then the default GID owner is root. Even if you set the GID specifically in `User` what matters is whether you have administrative access to the console. You only need to be the UID owner to do any administrative task, so also requiring the GID owner would be redundant. In addition, the reason this code exists is to allow for things like `wall` and `write` to work -- where you have a special `tty` group that can write to all of the consoles.

File: libcontainer/rootfs_linux.go (hunk 27 above)
Comment (cyphar) [inline libcontainer/rootfs_linux.go]: Yes. "Finalize" really means to "mount things as ro as requested". My original patchset had `PivotRoot` in `finalizeRootfs` but I ran into a bunch of permission issues (and the code had to mess around with paths quite a bit).

File: libcontainer/standard_init_linux.go (hunk 28 above)
Comment (cyphar) [inline libcontainer/standard_init_linux.go]: Ah. That is a fair point. I can move this back inside `prepareRootfs`.

File: libcontainer/console.go (hunk 20 above)
Comment (cyphar) [inline libcontainer/console.go]: Or maybe wiktionary is funded by the UE people who deny the superiority of BE. :wink:

File: contrib/cmd/recvtty/recvtty.go (hunk 18 above)
Comment (hqhq) [inline contrib/cmd/recvtty/recvtty.go]: My preference would be `stdout`, `stderr` should only take error messages, but that not a big deal.

A prefix of `[recvtty]` might be sufficient.

File: libcontainer/console_linux.go (hunk 23 above)
Comment (hqhq) [inline libcontainer/console_linux.go]: OK, if it's intentional, we should remove the parameter since it's not used.

Comment (cyphar) [inline libcontainer/console_linux.go]: Yeah, you're right. I've modified @mrunalp's patch accordingly.

**Comment by hqhq** [comment]
Overall it looks good to me, this PR needs @crosbymichael 's input since it'll significantly impact containerd, and I'm not sure containerd would like `recvtty` (it already had plenty of binaries), if containerd wouldn't use it, maybe we shouldn't treat `recvtty` as a first class binary.

File: libcontainer/console.go (hunk 20 above)
Comment (hqhq) [inline libcontainer/console.go]: :smile: haha, if it looks right to you, I'll accept it, maybe just change it to `non-ancilliary` for consistency.

File: libcontainer/standard_init_linux.go (hunk 28 above)
Comment (cyphar) [inline libcontainer/standard_init_linux.go]: I just tried to implement the split with `PivotRoot` in `finalizeRootfs` and the code gets quite ugly quite quickly. So I'm just going to move the `syncParentHooks` back to `prepareRootfs` as it was before. As an aside, we really need to add an integration test for this behaviour of the hooks API.

File: libcontainer/console.go (hunk 20 above)
Comment (cyphar) [inline libcontainer/console.go]: I'm kidding, I just suck at spelling. :stuck_out_tongue:

**Comment by cyphar** [comment]
> Overall it looks good to me, this PR needs @crosbymichael 's input since it'll significantly impact containerd, and I'm not sure containerd would like recvtty (it already had plenty of binaries), if containerd wouldn't use it,

`containerd` should not be using `recvtty`, it's just meant to be used for testing and as an example consumer. `containerd` *should* use the `TerminalInfo` API that I wrote inside `libcontainer` and use `recvtty` as an example of how the API works.

> maybe we shouldn't treat recvtty as a first class binary.

`make` is actually not supposed to be building `recvtty` at all (`.DEFAULT` is set to `runc`). But I'm going to change the output for `recvtty` to be inside `contrib/cmd/recvtty`.

File: libcontainer/utils/cmsg.go [hunk 29]
```diff
@@ -0,0 +1,57 @@
...
+// information for a file descriptor).
+func SendFd(socket, file *os.File) error {
+	var cfile C.struct_file_t
+	cfile.fd = C.int(file.Fd())
+	cfile.name = C.CString(file.Name())
+	defer C.free(unsafe.Pointer(cfile.name))
+
+	_, err := C.sendfd(C.int(socket.Fd()), cfile)
+	return err
+}
```
Comment (dqminh) [inline libcontainer/utils/cmsg.go]: we probably can skip binding to CGO here if we manually encapsulate the control message and just write it to unix socket (i..e syscall.UnixRights and WriteMsgUnix,ReadMsgUnix iirc )

File: Makefile [hunk 30]
```diff
@@ -26,13 +27,23 @@ VERSION := ${shell cat ./VERSION}
...
+all: runc recvtty
+
+recvtty: contrib/cmd/recvtty/recvtty
+
+contrib/cmd/recvtty/recvtty: $(SOURCES) | $(RUNC_LINK)
+	go build -i -ldflags "-X main.gitCommit=${COMMIT} -X main.version=${VERSION}" -tags "$(BUILDTAGS)" -o contrib/cmd/recvtty/recvtty ./contrib/cmd/recvtty
+
+static: $(SOURCES) | $(RUNC_LINK)
 	CGO_ENABLED=1 go build -i -tags "$(BUILDTAGS) cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit=${COMMIT} -X main.version=${VERSION}" -o runc .
+	CGO_ENABLED=1 go build -i -tags "$(BUILDTAGS) cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit=${COMMIT} -X main.version=${VERSION}" -o contrib/cmd/recvtty/recvtty ./contrib/cmd/recvtty
```
Comment (cyphar) [inline Makefile]: I thought so too, but @hqhq mentioned that it isn't really an "official" binary so I'm on the fence about it.

File: libcontainer/utils/cmsg.go (hunk 29 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.go]: Those APIs require you to specify `oob []byte`, which would require us binding to CGO anyway. TBH, I prefer this rather than mixing our C and the syscall API.

File: libcontainer/console.go [hunk 31]
```diff
@@ -11,5 +17,59 @@ type Console interface {
...
+// contains some information about the container which the console master fd
+// relates to (to allow for consumers to use a single unix socket to handle
+// multiple containers). This structure will probably move to runtime-spec
+// at some point. But for now it lies in libcontainer.
+type TerminalInfo struct {
+	// Version of the API.
+	Version int `json:"version"`
+
+	// Type of message (future proofing).
+	Type string `json:"type"`
```
Comment (cyphar) [inline libcontainer/console.go]: I mainly did this for debugging with `strace` purposes. I'm happy to change it, but `syncT` has shown us that explicit type values makes it easier to debug stuff. Is there a strong reason to change it

File: contrib/cmd/recvtty/recvtty.go [hunk 32]
```diff
@@ -0,0 +1,247 @@
...
+	}
+	defer conn.Close()
+
+	// Close ln, to allow for other instances to take over.
+	ln.Close()
+
+	// Get the fd of the connection.
+	unixconn, ok := conn.(*net.UnixConn)
+	if !ok {
+		bail(fmt.Errorf("failed to cast to unixconn"))
```
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: Done. And also applied to the other `bail`s in that function.

File: libcontainer/console.go [hunk 33]
```diff
@@ -11,5 +17,59 @@ type Console interface {
...
+	// Container contains the ID of the container.
+	Container string `json:"container"`
+}
+
+func (ti *TerminalInfo) String() string {
+	encoded, err := json.Marshal(*ti)
+	if err != nil {
+		panic(err)
+	}
+	return strings.TrimSpace(string(encoded))
```
Comment (cyphar) [inline libcontainer/console.go]: Fixed.

File: libcontainer/console.go [hunk 34]
```diff
@@ -11,5 +17,59 @@ type Console interface {
...
+// at some point. But for now it lies in libcontainer.
+type TerminalInfo struct {
+	// Version of the API.
+	Version int `json:"version"`
+
+	// Type of message (future proofing).
+	Type string `json:"type"`
+
+	// Container contains the ID of the container.
+	Container string `json:"container"`
```
Comment (cyphar) [inline libcontainer/console.go]: Fixed.

**Comment by cyphar** [comment]
@dqminh I've fixed a few of your nits. PTAL.

File: libcontainer/console.go (hunk 31 above)
Comment (dqminh) [inline libcontainer/console.go]: not strong, but i prefer using predefined const number for known types. Also payload is smaller i guess.

File: Makefile (hunk 30 above)
Comment (dqminh) [inline Makefile]: i *think* as long as we dont install it explicitly its ok, but im not sure either

File: libcontainer/utils/cmsg.go (hunk 29 above)
Comment (dqminh) [inline libcontainer/utils/cmsg.go]: `oob []byte` is your `syscall.UnixRights` so there should not be any cgo bindings.

File: Makefile (hunk 30 above)
Comment (hqhq) [inline Makefile]: I was concerned that it might cause confusion that runc depends on this recvtty if we build it under root.

File: libcontainer/utils/cmsg.go (hunk 29 above)
Comment (cyphar) [inline libcontainer/utils/cmsg.go]: Alright, I'll play around with this. I'm mainly concerned because it's usually the case that the Go `syscall` package loves messing around with things (especially with fickle Unix APIs). But hopefully it should work fine.

Comment (cyphar) [inline libcontainer/utils/cmsg.go]: @dqminh I've tried messing around with it, and it doesn't work. Currently `syscall.ParseSocketControlMessage` is failing because for some reason `syscall.Recvmsg` is receiving an error `syncT` rather than the right data. I don't really think this is a step in the right direction. We can switch from CGO in a separate PR, and I don't think we should hold up this PR because it uses CGO for sending file descriptors.

File: contrib/cmd/recvtty/recvtty.go (hunk 18 above)
Comment (cyphar) [inline contrib/cmd/recvtty/recvtty.go]: Fixed.

File: Makefile (hunk 30 above)
Comment (cyphar) [inline Makefile]: I'm just going to leave it as-is, since it feels marginally safer tucked away so nobody ships it as a serious component of runC. :P

File: libcontainer/console.go (hunk 31 above)
Comment (cyphar) [inline libcontainer/console.go]: Sure, I've changed it to use `'T'` so that we don't lost the debugability.

File: libcontainer/console.go [hunk 35]
```diff
@@ -11,5 +16,59 @@ type Console interface {
...
+// contains some information about the container which the console master fd
+// relates to (to allow for consumers to use a single unix socket to handle
+// multiple containers). This structure will probably move to runtime-spec
+// at some point. But for now it lies in libcontainer.
+type TerminalInfo struct {
+	// Version of the API.
+	Version uint32 `json:"version"`
+
+	// Type of message (future proofing).
+	Type uint8 `json:"type"`
```
Comment (wking) [inline libcontainer/console.go]: I don't see much point in separating an integer `version` from a `type` enum.  With SemVer's structured versions, the parties exchanging messages can interoperate (in some cases) even if their target versions don't match exactly.  With a non-semantic integer version that's no longer true.  Two possible approaches:

a. Make `version` a SemVer field and use it to version messages of a given type (e.g. increment it when we adjust the payload for `T`-type messages, and have a separate SemVer version for some future `X`-type (say) messages).

b. Drop `version` and make `type` a string.  A future `T`-ish message would be `T2` (or whatever).  This is the pattern used by POSIX with `dup`, `dup2`, etc.

I expect this message schema to be low-churn, so I prefer (b).

And I'd rather have less-compact types (e.g. `terminal` instead of `T`).

Comment (cyphar) [inline libcontainer/console.go]: I changed it from a string to a `uint8` (I don't remember who suggested the change). I don't really want to switch back and forth over _one field_ in a structure for a ~2k line patch. 

Put simply this is why I went with having a type field: It means that we can future proof the specification of types. Now, if you want to write protocol version negotiation code for `--console-socket` you can go ahead. But personally I think that's massively overkill. We're just sending a **single** file descriptor. If we want to expand this later we can expand it inside the OCI `runtime-spec` (where this structure will end up living).

Comment (wking) [inline libcontainer/console.go]: I don't want to expand it (that would be (a)), I want to simplify it (b).  Still future-proof (because either you recognize `terminal` (or `terminal2`, or whatever) or you don't.  Just like with your current proposal, you either recognize `(T, 201610041)` (or `(T, 201612011)`, or whatever) or you don't.

Re: mixing type and version not being clean.  I'd agree if either had any semantic meaning.  But if they're both opaque magic, I don't see the point of matching a tuple when we could just be matching a single field.

Comment (cyphar) [inline libcontainer/console.go]: We can hash out in the spec. Do not discuss that here. Once the spec PR is merged we will vendor it and use that structure (and remove this one). Please don't make this drag out because of spec-related discussions -- what this  structure looks like is **orthogonal** to this feature.

**Comment by laijs** [comment]
--console-socket passes the container specified resource to the upper layer(docker/containerd/ocid). it is bad design. we should limit all the container specified resource in the runtime. so does --pid-file which exposes the pid of the container.

we should only control/fetch-info on the container via the runtime API(commandline https://github.com/opencontainers/runtime-spec/pull/513 or state.json)

detachable stdio is a strong required feature, we can/should implement it in
the runtime rather than in containerd-shim or ocid/conmon.

we can add `runc connect-stdio` or something else for connect/re-connect the stdio stream
we can add `runc set-win-size` or something else  for changing the winsize when tty=true.

**Comment by cyphar** [comment]
@laijs I'm sorry, but I very strongly disagree. AFAICS you're suggesting that runC has to be a daemon that manages this. runC is **never** going to be a daemon -- it's an explicit design decision. Note that `--console-socket` **only affects you** if you're going to be using `runc create` or `runc run -d`. In both of those cases, the `runc` process will exit meaning that there's nowhere for us to keep the master `ptmx` file descriptor open!

There are several process management issues that can _only_ be solved if `runC` exits and you set the parent process to be a subpreaper (`PRCTL_SET_SUB_REAPER`). So we _need_ to make the main runC process exit in certain cases.

Not to mention that doing it this way _actually_ makes the stdio management closer to a normal process (in a normal process, the parent has direct access to the stdio of the process and can do complicated management tasks without going through the daemon). The big problem with adding `runc` console control subcommands is that it also means that we now have to figure out what everyone and their dog wants us to implement inside `runc`. By allowing consumers to manage the master pty how they like, we don't have to deal with it anymore.

> --console-socket passes the container specified resource to the upper layer(docker/containerd/ocid). it is bad design.

If you can explain **why** it's a bad design in your opinion, that would be great.

**Comment by wking** [comment]
On Thu, Oct 20, 2016 at 09:27:10AM -0700, Lai Jiangshan wrote:
> --console-socket passes the container specified resource to the
> upper layer(docker/containerd/ocid). it is bad design. we should
> limit all the container specified resource in the runtime. so does
> --pid-file which exposes the pid of the container.
>
> we should only control/fetch-info on the container via the runtime
> API(commandline
> https://github.com/opencontainers/runtime-spec/pull/513 or
> state.json)

This spec discussion is probably better suited to
opencontainers/runtime-spec#513 [1].

[1]: https://github.com/opencontainers/runc/pull/1018#discussion_r83813355

**Comment by cyphar** [comment]
Alright, as per an OCI call a few weeks ago, we agreed we'd wait until the end of October before merging this (to allow for testing). Since it's now November, time for a status update.

@crosbymichael @mrunalp What is the status of testing / are there any things left to consider or implement? I know that @crosbymichael was talking about changing `--console-socket` to instead by implicit (like `LISTEN_FDS`). I would prefer if we make `--console-socket` instead take a file descriptor number which is an open socket connection -- that way it's a bit more explicit. Though there's the obvious issue of "how the hell do we test that with `bats`". Maybe we should make it take a **path** to an open socket file (in other words to `/proc/pid/fd/...`)?

**Comment by crosbymichael** [comment]
@cyphar testing looks good but I hate providing a path to a unit socket, I would like to just pass the FD

**Comment by cyphar** [comment]
@crosbymichael I agree, however I'm quite hesitant about switching to just passing an `fd` number because it would make testing with `bats` really hard. What if we made it something like `--console-socket /proc/pid/fd/...` so that you could point it at another process that has opened the socket for you (we could then come up with some `socat` trickery to test it in `bats`).

**Comment by cyphar** [comment]
@crosbymichael I'm on the fence about it. [[ I deleted my old message because I reconsidered my argument. I used to be pro-just-passing-the-fd. Now I'm on the fence. ]]

On one hand, I completely agree with your point. Working with a bound unix socket path is a huge pain, and there are a bunch of things we have to tell users about (it needs to be accessible by runC, you need to make it a `SOCK_STREAM` socket, and so on). In particular, this makes standardising on an interface more of a pain than necessary (and adds a writeable filesystem requirement that wouldn't exist otherwise).

However, I'm also quite hesitant about switching to just passing an `fd` number because it would make testing with `bats` really hard. Not to mention that you're then requiring that whatever process spawns runC needs to bind to the right socket and pass it as an fd. While this isn't _horrible_, it's enough of a pain that testing with `bats` would become unwieldy.

What if we made it something like `--console-socket /proc/pid/fd/...` so that you could point it at another process that has opened the socket for you (we could then come up with some `socat` trickery to test it in `bats`).

The other option is that we can simply tell users that the socket will always be `SOCK_STREAM` and call it a day (in other words "read the source code of `recvtty` or just use it to know what we want you to do"). The plus side of `recvtty` is that this is actually possible for us to do this because `recvtty` is part of our test suite (and we could add some tests around `recvtty` to make sure that it actually gets the output as expected if you want in a follow-up PR).

File: libcontainer/console.go [hunk 36]
```diff
@@ -11,5 +16,59 @@ type Console interface {
 	Path() string
 
 	// Fd returns the fd for the master of the pty.
-	Fd() uintptr
+	File() *os.File
```
Comment (datawolf) [inline libcontainer/console.go]: The comment need to be updated. thanks.

File: Makefile [hunk 37]
```diff
@@ -26,13 +27,23 @@ VERSION := ${shell cat ./VERSION}
...
 
-release: $(RUNC_LINK)
+release: $(RUNC_LINK) | $(RUNC_LINK)
 	@flag_list=(seccomp selinux apparmor static ambient); \
```
Comment (datawolf) [inline Makefile]: Is this right? `$(RUNC_LINK) | $(RUNC_LINK)` or `$(SOURCES) | $(RUNC_LINK)` ?

Comment (cyphar) [inline Makefile]: Yeah, it should be `$(SOURCES)`. Thanks.

File: tests/integration/tty.bats [hunk 38]
```diff
@@ -0,0 +1,113 @@
...
+@test "runc run [tty owner]" {
+	# Replace sh script with stat.
+	sed -i 's/"sh"/"sh", "-c", "stat -c %u:%g $(tty) | tr : \\\\\\\\n"/' config.json
+
+	# run busybox
+	runc run test_busybox
+	[ "$status" -eq 0 ]
+	[[ ${lines[0]} =~ 0 ]]
+	# This is set by the default config.json (it corresponds to the standard tty group).
+	[[ ${lines[1]} =~ 5 ]]
```
Comment (datawolf) [inline tests/integration/tty.bats]: The output is explicit, I think it is better use `==` instead of '=~'.

**Comment by hqhq** [comment]
@cyphar Why would passing an fd number make testing with bats so hard? I think handle fd number in runc could make the code cleaner, but I'm also fine with current implementation.

**Comment by cyphar** [comment]
@hqhq Because you'd need to open the right file descriptor that `recvtty` has opened. To be fair you could do it like this:

```
% recvtty --the-other-end-of-the-socket fdnum
% runc --console-socket 8888 8888<>/proc/$(pgrep recvtty)/fd/8888
```

But that seems quite ugly to me.

**Comment by hqhq** [comment]
@cyphar @crosbymichael I'm working on integrating this PR with docker and containerd, the right place for containerd to create the socket file should be `/run/docker/libcontainerd/containerd/<container-id>/init/console.sock`, and it's awkward to find out that we have a 108 chars limit for socket file path name, see https://github.com/golang/go/issues/6895 . :sweat:

**Comment by cyphar** [comment]
@hqhq In that case we'll have to make it take a file descriptor path. I'll add a patch for that.

**Comment by cyphar** [comment]
Bad news, you can't actually open `/proc/<pid>/fd/<fd>` if the file descriptor is a socket. You get `ENXIO`, which I'm not sure why that's happening (looking at the source I don't see why it's happening). But this means that we can't use `5<>/proc/pid/fd/...`.

All of this means that the only way we can implement this is to wrap runC with `recvtty` which isn't very helpful for testing.

@crosbymichael WDYT?

**Comment by hqhq** [comment]
@cyphar As a workaround, I created socket file in another shorter path so I can move on, then I found another issue, after start the container, io looks like:
image

I found out it's caused by https://github.com/opencontainers/runc/pull/1146, after revert that PR in runc, io works normally:
image

Just a heads up, we can surely handle it in a separate PR, running Docker integration tests now.

**Comment by cyphar** [comment]
@hqhq #1146 fixes issues that we have in runC (it's the reason the test suite runs right now), but it's possible that you'd need to change some of the terminal stuff within Docker to fix it. I can help you take a look at that if you'd like.

**Comment by hqhq** [comment]
@cyphar Yeah that's non-relevant to this PR, I'll look into that later.

Integration with Docker works fine, I think we can also handle the socket file path issue in following up PRs, can you squash your commits(if needs any) and remove the `[wip]` in the patch title, I think we can merge it now.

**Comment by cyphar** [comment]
@hqhq :tada: Alright, I've rebased and squashed the final `[wip]` commit. PTAL so we can (finally) merge this. :smile_cat:

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
Do we want to wait for @crosbymichael's LGTM?

**Comment by mrunalp** [comment]
Yeah.

**Comment by cyphar** [comment]
Rebased.

/cc @crosbymichael Can you please take a look at this so we can (finally) merge it?

**Comment by caniszczyk** [comment]
ping @crosbymichael :)

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by cyphar** [comment]
:tada: As discussed on the call, either @crosbymichael or myself will work on removing the `--console-socket` argument.

**Comment by williammartin** [comment]
@hqhq @cyphar Sorry to resurrect...did y'all ever come up with a solution for the weird terminal formatting mentioned in https://github.com/opencontainers/runc/pull/1018#issuecomment-262155656 ?
