### PR TITLE
Set temporary single CPU affinity before cgroup cpuset transition.

### LINKED ISSUE #3922: Issue joining cgroups cpuset with kernel scheduler task "random" distribution
### Description

A customer reported us an issue when attempting to join a running container inside `kubernetes` (`kubectl exec` ...). The container is running a real time application taking advantage of cores allocated to this container, the application uses the first CPU core of the allocated range as a slow thread (SCHED_OTHER policy) responsible for spawning RT threads (running under SCHED_FIFO policy) each running on a core.

They have configured kubernetes to ensure that it will allocate CPU cores within a specific range (all marked as isolated CPUs), they are using the kubernetes CPU manager with the static policy and have excluded all housekeeping CPUs from being allocated to a pod/container. Their machine is configured like this:

- For the kernel command line:
```
isolcpus=managed_irq,domain,2-23,26-47 nmi_watchdog=0 nohz=on nohz_full=2-23,26-47
rcu_nocb_poll=1 rcu_nocbs=2-23,26-47 irqaffinity=0,1,24,25
```

- Relevant sysctl:
```
kernel.hung_task_timeout_secs = 600
kernel.nmi_watchdog = 0
kernel.sched_rt_runtime_us = -1
vm.stat_interval = 10
kernel.timer_migration = 0
```

Customer has used this configuration successfully until RHEL 8.4, but with the introduction of this [patch](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76) in 8.4, a random CPU assignment/scheduling occurs when a process enter (`runc` in this context) in a cgroup cpuset, before the patch addition, `runc` was always scheduled on the first CPU core of the cgroup cpuset, it worked fine as the first CPU core was used by a slow thread running under SCHED_OTHER policy, since the introduction of the kernel patch, `runc` is randomly scheduled on a core that can be fully taken by a RT threads running under SCHED_FIFO policy and with `kernel.sched_rt_runtime_us=-1` there is no room for `runc` execution and the process get stuck, when it occurs it was observed that some other processes become unresponsive, so far `systemd` pid 1 was also stuck in a kernel call to `proc_cgroup_show` .

This is a corner case issue but serious enough to lock down a system.

### Steps to reproduce the issue

Please find in attachment an archive with a reproducer based on vagrant/libvirt.

Decompress the archive and run `vagrant up && vagrant halt && vagrant up`

Then run a vagrant VM terminal with `vagrant ssh` and execute:

```
./reproducer.sh install
./reproducer.sh run 2-3,5
```

In another vagrant VM terminal, run `./reproducer.sh exec sh`, the command should stuck and the system also, you shouldn't be able to open another vagrant terminal with `vagrant ssh` until the command in the first terminal is interrupted.

If you retry by running `./reproducer.sh run 2-3,5` in the first terminal but now `./reproducer.sh exec-patch sh` in the second terminal, the system is now operating correctly (PR patch on going)

[cpuset-issue-runc-repro.tar.gz](https://github.com/opencontainers/runc/files/11916735/cpuset-issue-runc-repro.tar.gz)

### Describe the results you received and expected

The system stucks instead of operating correctly

### What version of runc are you using?

runc 1.0.2 (but doesn't really matter here)

### Host OS information

RHEL 8.X

### Host kernel information

RHEL 8.X kernels

### PR DESCRIPTION
**Pull request by cclerget**
This handles a corner case when joining a container having all the processes running exclusively on isolated CPU cores to force the kernel to schedule runc process on the first CPU core within the cgroups cpuset.

The introduction of the kernel commit
46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76 has affected this deterministic scheduling behavior by distributing tasks across CPU cores within the cgroups cpuset. Some intensive real-time application are relying on this deterministic behavior and use the first CPU core to run a slow thread while other CPU cores are fully used by real-time threads with SCHED_FIFO policy. Such applications prevents runc process from joining a container when the runc process is randomly scheduled on a CPU core owned by a real-time thread.

* Fixes #3922

### CODE REVIEW

File: libcontainer/container_linux.go [hunk 1]
```diff
@@ -2261,3 +2290,61 @@ func requiresRootOrMappingTool(c *configs.Config) bool {
...
+// getEligibleCPU returns the first eligible CPU for CPU affinity before
+// entering in a cgroup cpuset.
+// - when there is not cpuset cores: no eligible CPU
+// - when there is not isolated cores: no eligible CPU
+// - when cpuset cores are all isolated cores: return first CPU of the cpuset
+// - when cpuset cores are mixed between housekeeping/isolated cores: no eligible CPU
+func getEligibleCPU(cpusetList, isolatedList string) (int, bool, error) {
+	if isolatedList == "" {
+		return 0, false, nil
+	} else if cpusetList == "" {
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:2303]: you can combine these two into
```go
if isolatedList == "" || cpusetList == "" {
```

File: libcontainer/container_linux.go [hunk 2]
```diff
@@ -2261,3 +2290,61 @@ func requiresRootOrMappingTool(c *configs.Config) bool {
...
+		return 0, false, nil
+	}
+
+	// The target container has a cgroup cpuset, get the bit range
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:2307]: nit: missing period

File: libcontainer/nsenter/nsexec.c [hunk 3]
```diff
@@ -1250,6 +1260,29 @@ void nsexec(void)
...
+			 * this handles a corner case when joining a container having all
+			 * the processes running exclusively on isolated CPU cores to force
+			 * the kernel to schedule runc process on the first CPU core within the
+			 * cgroups cpuset. The introduction of the kernel commit
+			 * 46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76 has affected this deterministic
+			 * scheduling behavior by distributing tasks across CPU cores within the
+			 * cgroups cpuset. Some intensive real-time application are relying on this
+			 * deterministic behavior and use the first CPU core to run a slow thread
+			 * while other CPU cores are fully used by real-time threads with SCHED_FIFO
+			 * policy. Such applications prevents runc process from joining a container
```
Comment (kolyshkin) [inline libcontainer/nsenter/nsexec.c:1274]: nit: `s/prevents/prevent/`

File: libcontainer/container_linux_test.go [hunk 4]
```diff
@@ -390,3 +390,87 @@ func TestGetContainerStateAfterUpdate(t *testing.T) {
...
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			affinityCore, eligible, err := getEligibleCPU(tt.cpuset, tt.isolset)
+			if err != nil && !tt.expectedErr {
+				t.Fatalf("unexpected error for %q: %s", tt.name, err)
+			} else if err == nil && tt.expectedErr {
+				t.Fatalf("unexpected success for %q", tt.name)
+			} else if tt.expectedEligible && !eligible {
+				t.Fatalf("was expecting eligible core but no eligible core returned for %q", tt.name)
```
Comment (kolyshkin) [inline libcontainer/container_linux_test.go:468]: nit: no need to add tt.name to error text, as it added to the test name by `t.Run`.

**Comment by kolyshkin** [comment]
Thanks for working on this. I changed it to draft until all the issues with the code and test cases are fixed, and left some minor comments.

**Comment by cclerget** [comment]
Thanks @kolyshkin , it should be ready for review now

**Comment by lifubang** [comment]
@cclerget Please rebase

**Comment by cclerget** [comment]
@lifubang Done

File: libcontainer/container_linux.go [hunk 5]
```diff
@@ -2280,3 +2309,57 @@ func requiresRootOrMappingTool(c *configs.Config) bool {
 	}
 	return !reflect.DeepEqual(c.GidMappings, gidMap)
 }
+
+// getEligibleCPU returns the first eligible CPU for CPU affinity before
+// entering in a cgroup cpuset.
+// - when there is not cpuset cores: no eligible CPU
+// - when there is not isolated cores: no eligible CPU
+// - when cpuset cores are all isolated cores: return first CPU of the cpuset
+// - when cpuset cores are mixed between housekeeping/isolated cores: no eligible CPU.
```
Comment (lifubang) [inline libcontainer/container_linux.go:2318]: @cclerget Is this rule too strict? I think we can calculate an eligible CPU. What was your idea when making this rule? Is it about algorithms’ complexity? Or something else I didn't notice?

File: libcontainer/nsenter/nsexec.c [hunk 6]
```diff
@@ -1053,6 +1063,29 @@ void nsexec(void)
...
+			 * while other CPU cores are fully used by real-time threads with SCHED_FIFO
+			 * policy. Such applications prevent runc process from joining a container
+			 * when the runc process is randomly scheduled on a CPU core owned by a
+			 * real-time thread.
+			 */
+			if ((int32_t) config.cpu_affinity >= 0) {
+				cpu_set_t set;
+				CPU_ZERO(&set);
+				CPU_SET(config.cpu_affinity, &set);
+				if (sched_setaffinity(0, sizeof(set), &set) == -1)
```
Comment (lifubang) [inline libcontainer/nsenter/nsexec.c:1085]: @cclerget I have tested your solution in my host. There is a big problem, the cpu affinity has the higher priority then `cpuset.cpus`. All tasks in the container will be scheduled to this tempporary single CPU.
I think you should remove the cpu affinity before the container started.

**Review by lifubang — CHANGES_REQUESTED** [review]

File: libcontainer/nsenter/nsexec.c (hunk 6 above)
Comment (cclerget) [reply libcontainer/nsenter/nsexec.c:1085]: @lifubang When the process is joining an existing container, the CPU affinity mask is reset to the cgroup cpuset, `taskset -c -p $$` returns the cpu affinity mask corresponding to cpuset.

What you've observed is expected, as the scheduler do not schedule tasks pinned to isolated CPUs, that's why this [patch](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76) is problematic.
Since the scheduler doesn't manage tasks on isolated CPUs, everything is executed on the temporary CPU, my changes just restore the kernel behavior prior to kernel patch above.
You can test without my changes, you will also observe that all processes runs on the same isolated CPU, the difference is that the isolated CPU will randomly change each time you are entering in the container, but subsequent processes still runs on the same isolated CPU.

Removing the cpu affinity before executing container process would defeat the purpose of this patch, as the kernel could pin it randomly on a "locked" isolated core, this is the last case from [patch](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76) description:

```
The cases that this mainly affects are:
 - modifying cpuset.cpus
 - when tasks join a cpuset
 - when modifying a task's affinity via sched_setaffinity(2)
```

File: libcontainer/container_linux.go (hunk 5 above)
Comment (cclerget) [reply libcontainer/container_linux.go:2318]: @lifubang Yes, originally in kubernetes context, I translated this to a non-deterministic CPU allocation and I wasn't expecting such setup to be used. But you're right, the first housekeeping CPU could be used here to handle specific CPU allocations no matter the context

File: libcontainer/nsenter/nsexec.c (hunk 6 above)
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:1085]: > What you've observed is expected,

I think it is not expected.
For example:
```bash
root@acmcoder:/home/acmcoder# cat /sys/devices/system/cpu/isolated
0-1,3
```
ContainerA: cpuset.cpus: "1,3"
When the ContainerA started, all the tasks in this container will be scheduled to `cpu1`, no tasks in `cpu3`.

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:1085]: > You can test without my changes, you will also observe that all processes runs on the same isolated CPU,

No, I have tested it. With the same configuration as above, both `cpu1` and `cpu3` have  the same level load.

Comment (cclerget) [reply libcontainer/nsenter/nsexec.c:1085]: > ContainerA: cpuset.cpus: "1,3"
When the ContainerA started, all the tasks in this container will be scheduled to cpu1, no tasks in cpu3.

Just to be sure, the patch is affecting `runc exec` not `runc run` (`initSetns` only https://github.com/opencontainers/runc/pull/3923/files#diff-1cdede3fe918430ca0b7e4056abc49abca8a2925c6770ec1951befa6091f7a94R2251)

Let me clarify and describe what I did for testing, I have a VM with 8 CPUs with `isolcpus=0-3`.

I'm using an OCI config containing, the container just call sleep for some time :

```
	"linux": {
		"cgroupsPath": "/repro",
		"resources": {
			"cpu": {
				"cpus": "0-3",
				"mems": "0"
			},
			"devices": [
				{
					"allow": false,
					"access": "rwm"
				}
			]
		},
		"namespaces": [
			{
				"type": "mount"
			}
		]
	}
```

In a first terminal I'm starting the container with:

```
sudo runc run --pid-file /tmp/repro.pid --bundle /tmp/bundle repro
```

Then in a second terminal I'm spawing another process to test the patch :

```
sudo runc exec repro sh -c "for i \$(seq 1 100); do cat /proc/self/stat|awk '{print $39}'; done"
```

I did that with and without my runc changes and with `isolcpus=0-3` for both, all iterations will show the exact same CPU between 0-3 for the unmodified runc (this is expected, this is the kernel [patch](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76) in action):

```
sudo runc exec repro sh -c "for i \$(seq 1 100); do cat /proc/self/stat|cut -d ' ' -f 39; done"
2
2
2
2
2
2
....
```

While modified runc will show 0 for all (expected result), my patch spawn the entering process on the first CPU of the `cpuset.cpus`.


```
sudo runc exec repro sh -c "for i \$(seq 1 100); do cat /proc/self/stat|cut -d ' ' -f 39; done"
2
2
2
2
2
2
....
```
Now if you run the same without `isolcpus` set in the VM, you will notice that all iterations are showing different CPU for each iterations.

Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:1085]: Your clarify is clear, I have understood all your opinions, thanks.

Comment (cclerget) [reply libcontainer/nsenter/nsexec.c:1085]: Cool ! I also pushed changes related to https://github.com/opencontainers/runc/pull/3923#discussion_r1264319356

**Comment by lifubang** [comment]
@cclerget I think this patch is helpful to solve the issue #3922 . 

I also think that the existence of [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76) has its meaning.
Maybe in most situation, people may need the behavior of this kernel's patch, but after your patch, people have no chance to let the kernel distribute tasks to different cpus, because your patch masks the kernel's patch.

**Comment by cclerget** [comment]
@lifubang I understand your concerns, what if I restrict the scope of the patch by calling `getEligibleCPU` only when `kernel.sched_rt_runtime_us` has `-1` value ? When set to `-1`, it gives zero room for kernel to switch in kernel space on a CPU where a real-time application is running on (under scheduler real-time policies) and do not make any context switch.

This setting value is part of the problem that I'm attempting to address, when all tasks (except the slow-thread) are running under scheduler a real-time policy within a cgroup cpuset, the kernel patch will arbitrary pin `runc` process to one of the CPU during cgroup transition, if `runc` is not pinned to the CPU running the slow-thread (usually running on the first CPU of the cpuset for a deterministic placement), `runc` will get stuck and won't be able to enter in container with the side effect of locking down the system by acquiring a lock in cgroup subsystem during transition, the lock is not released until the `runc` process has been placed in scheduler CPU queue, which do not happen in this case until the real-time thread exit or make a context switch (not the case).

So it might make sense to also check this value and only call `getEligibleCPU` for this specific case. This should drastically reduce the scope of the patch, as many setup won't use this setting, and people using it are aware of consequences, so I think this patch will be required to restore the previous deterministic task placement of the kernel in such setup where this kernel patch is not appropriate, it is useful in most situations but not this one where random task placement has bad consequences

**Comment by lifubang** [comment]
> what if I restrict the scope of the patch by calling `getEligibleCPU` only when `kernel.sched_rt_runtime_us` has `-1` value ?

I think it's a good idea.

**Comment by cclerget** [comment]
Changes applied

**Comment by lifubang** [comment]
> Changes applied

@cclerget Thanks. But sorry, you should rebase to resolve conflicts.

**Comment by cclerget** [comment]
@lifubang done

File: libcontainer/container_linux.go [hunk 7]
```diff
@@ -2358,3 +2378,120 @@ func requiresRootOrMappingTool(c *configs.Config) bool {
...
+
+	return nil
+}
+
+// getEligibleCPU returns the first eligible CPU for CPU affinity before
+// entering in a cgroup cpuset:
+//   - when there is not cpuset cores: no eligible CPU
+//   - when there is not isolated cores: no eligible CPU
+//   - when cpuset cores are all isolated cores: return the first CPU of the cpuset
+//   - when cpuset cores are mixed between housekeeping/isolated cores: return the
```
Comment (lifubang) [inline libcontainer/container_linux.go:2434]: There is another situation: when all cpuset cores are not isolated cores.
This function should return -1, false, nil.

**Review by lifubang — CHANGES_REQUESTED** [review]

File: libcontainer/container_linux.go (hunk 7 above)
Comment (lifubang) [reply libcontainer/container_linux.go:2434]: And add a test case to cover this situation, thanks.

Comment (cclerget) [reply libcontainer/container_linux.go:2434]: This is covered by `isolatedCores > 0` https://github.com/opencontainers/runc/pull/3923/files#diff-1cdede3fe918430ca0b7e4056abc49abca8a2925c6770ec1951befa6091f7a94R2496 which is greater than 0 when there at least one core present in both sets.

And here the corresponding test case https://github.com/opencontainers/runc/pull/3923/files#diff-a632fc3b003cd903187e1091e7699141c62c87887c4a5e5ab17f99cb3de427c0R392

Comment (cclerget) [reply libcontainer/container_linux.go:2435]: I updated the function comment as a covered case

Comment (lifubang) [reply libcontainer/container_linux.go:2435]: To simplify this function, I have another idea. Could you consider break the for loop and return when isolatedCores>0 && affinityCore>-1?

Comment (lifubang) [reply libcontainer/container_linux.go:2435]: > Yes, you covered it.

You have covered these two cases in one case:
1. cpuset: 0-1, isolated: 10-11
2. cpuset: 10-11, isolated: 0-1

Comment (cclerget) [reply libcontainer/container_linux.go:2435]: > Yes, you covered it. My original thought is that we should set affinityCore to -1, if isolatedCores==0, or combine this two returns to one? Keep affinityCore, remove isolatedCores?

Fixed

> To simplify this function, I have another idea. Could you consider break the for loop and return when isolatedCores>0 && affinityCore>-1?

As we need to handle the mixed case, we can only return when mixed case is detected and isolatedCores > 0, it's covered here https://github.com/opencontainers/runc/pull/3923/files#diff-1cdede3fe918430ca0b7e4056abc49abca8a2925c6770ec1951befa6091f7a94R2483

Globally, the loop has been a bit refactored to be less verbose. Thanks !

Comment (cclerget) [reply libcontainer/container_linux.go:2435]: > You have covered these two cases in one case:

    cpuset: 0-1, isolated: 10-11
    cpuset: 10-11, isolated: 0-1

Fixed too

**Review by lifubang — APPROVED** [review]

**Comment by cclerget** [comment]
@lifubang I realized that I forgot to remove the print line at https://github.com/opencontainers/runc/commit/a3c5576990cd33c7fc0fa6500f30c771af8ff501#diff-1cdede3fe918430ca0b7e4056abc49abca8a2925c6770ec1951befa6091f7a94R2386, I just removed it with this change https://github.com/opencontainers/runc/compare/a3c5576990cd33c7fc0fa6500f30c771af8ff501..00b21903d5c44c0b5220ca95375f675a2a08891a, sorry about that

**Comment by lifubang** [comment]
Thanks, @kolyshkin PTAL

**Comment by lifubang** [comment]
Need rebase @cclerget

**Comment by lifubang** [comment]
@opencontainers/runc-maintainers PTAL
@cclerget has rebased many times. I think this patch is very important for some real-time nodes.

**Review by AkihiroSuda — APPROVED** [review]

**Comment by lifubang** [comment]
@cclerget I have no time to dive into the code design, do you know there is a way to move all your code from `c` to `golang`?

**Comment by cclerget** [comment]
@lifubang Will look if I can move that into `setnsProcess.start`

File: libcontainer/process_linux.go [hunk 8]
```diff
@@ -81,9 +84,40 @@ func (p *setnsProcess) signal(sig os.Signal) error {
...
+			return fmt.Errorf("getting container cgroups: %w", err)
+		} else if cg.CpusetCpus != "" {
+			cpuAffinity, err = getCPUAffinity(os.DirFS("/"), cg.CpusetCpus)
+			if err != nil {
+				return fmt.Errorf("setting CPU affinity: %w", err)
+			}
+		}
+	}
+
+	err := startCommandWithCPUAffinity(p.cmd, cpuAffinity)
```
Comment (lifubang) [inline libcontainer/process_linux.go:119]: I think maybe we should move the `cpuAffinity` check to here to make the code more readable:
```
	var err Error
	if cpuAffinity < 0 {
		err = cmd.Start()
	} else {
		err = startCommandWithCPUAffinity(p.cmd, cpuAffinity)
        }
```

File: libcontainer/process_linux.go [hunk 9]
```diff
@@ -81,9 +84,40 @@ func (p *setnsProcess) signal(sig os.Signal) error {
...
+	cpuAffinity := -1
+
+	if len(p.manager.GetPaths()) > 0 {
+		// get the target container cgroup
+		if cg, err := p.manager.GetCgroups(); err != nil {
+			return fmt.Errorf("getting container cgroups: %w", err)
+		} else if cg.CpusetCpus != "" {
+			cpuAffinity, err = getCPUAffinity(os.DirFS("/"), cg.CpusetCpus)
+			if err != nil {
+				return fmt.Errorf("setting CPU affinity: %w", err)
```
Comment (lifubang) [inline libcontainer/process_linux.go:114]: setting -> getting

**Comment by lifubang** [comment]
Thanks, overall still LGTM.
@cclerget Could you please add an integration test to read and check cpuAffinity value in the container with some mock data in `https://github.com/opencontainers/runc/blob/main/libcontainer/integration/exec_test.go`?
@AkihiroSuda Could you review this solution to check whether this is still LGTY or not before @cclerget squashing all the commits.

**Comment by dqminh** [comment]
Can you explain more what does "temporary" mean here ? If we called `sched_setaffinity` manually to the first CPU i suppose we are working around the random distribution of tasks and the affinity to first CPU is permanent, am i understanding this correctly ?

**Comment by cclerget** [comment]
@lifubang 
> Could you please add an integration test to read and check cpuAffinity value in the container with some mock data in https://github.com/opencontainers/runc/blob/main/libcontainer/integration/exec_test.go?

Now the question is, do you just want the case where there is no eligible CPU to ensure to not mess up with affinity for most case, or do you also want to test the case for an eligible CPU by mocking `/sys/devices/system/cpu/isolated` and `/proc/sys/kernel/sched_rt_runtime_us` ? For the latter case I could add an `fs.FS` to `libcontainer.Process`, if it sounds reasonable ?

@dqminh The call to `sched_setaffinity` just set the CPU affinity mask for a short period hence "temporary", when the runc process is placed in the container cgroup it is joining, cgroup set (or reset) the CPU affinity mask for the process to `cpuset.cpus` value, the process still run on the first CPU set until the kernel scheduler decide to move it to another CPU of `cpuset.cpus` list if necessary and possible, this restores the same behavior as before the kernel patch.

**Comment by lifubang** [comment]
> For the latter case I could add an `fs.FS` to `libcontainer.Process`, if it sounds reasonable ?

I have a strange idea:
1. mount -o bind ./sched_rt_runtime_us /proc/sys/kernel/sched_rt_runtime_us
2. mount -o bind ./isolated /sys/devices/system/cpu/isolated
3. integration test
4. umount /proc/sys/kernel/sched_rt_runtime_us
5. umount /sys/devices/system/cpu/isolated

**Comment by cclerget** [comment]
@lifubang the hacky way yeah, that should do it, hoping to not interfere with other tests running in parallel in the future, there is few chance but we never know

File: libcontainer/message_linux.go [hunk 10]
```diff
@@ -22,6 +22,10 @@ const (
 	UidmapPathAttr   uint16 = 27288
 	GidmapPathAttr   uint16 = 27289
 	TimeOffsetsAttr  uint16 = 27290
+	MountSourcesAttr uint16 = 27290
+	IdmapSourcesAttr uint16 = 27291
+	TimeOffsetsAttr  uint16 = 27292
+	CPUAffinityAttr  uint16 = 27293
```
Comment (kolyshkin) [inline libcontainer/message_linux.go]: Why is this here?

Comment (kolyshkin) [reply libcontainer/message_linux.go]: I mean, `MountSources` and `IdmapSources`.

File: libcontainer/nsenter/nsexec.c [hunk 11]
```diff
@@ -110,6 +113,10 @@ struct nlconfig_t {
 #define UIDMAPPATH_ATTR		27288
 #define GIDMAPPATH_ATTR		27289
 #define TIMENSOFFSET_ATTR	27290
+#define MOUNT_SOURCES_ATTR	27290
+#define IDMAP_SOURCES_ATTR	27291
+#define TIMENSOFFSET_ATTR	27292
```
Comment (kolyshkin) [inline libcontainer/nsenter/nsexec.c]: ditto

File: docs/isolated-cpu-affinity-transition.md [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+
+* `temporary` to temporarily set the runc process CPU affinity to the first
+isolated CPU core of the container cgroup cpuset.
+* `definitive`: to definitively set the runc process CPU affinity to the first
+isolated CPU core of the container cgroup cpuset.
+
+__WARNING:__ `definitive` requires a kernel >= 6.2, also works with RHEL 9 and
+above.
+
+### How it works ?
```
Comment (kolyshkin) [inline docs/isolated-cpu-affinity-transition.md:32]: nit: extra space

**Review by kolyshkin — COMMENTED** [review]
One general comment: please ensure the comments you're adding start with an Uppercased letter and end with a period.

Otherwise it's harder to maintain long-term.

File: tests/integration/exec.bats [hunk 13]
```diff
@@ -340,3 +340,143 @@ EOF
...
+	runc run -d --console-socket "$CONSOLE_SOCKET" test_isolated_bad_transition
+	[ "$status" -eq 0 ]
+
+	# test with bad transition value
+	echo "runc.exec.isolated-cpu-affinity-transition=bad nohz_full=$cpus" >"$tmp/cmdline"
+
+	mount --bind "$tmp/cmdline" /proc/cmdline
+
+	runc exec test_isolated_bad_transition true
+	runc_status=$status
```
Comment (kolyshkin) [inline tests/integration/exec.bats:428]: You don't have to save `$status`, as `umount` command won't change it.

File: libcontainer/system/kernelparam/lookup.go [hunk 14]
```diff
@@ -0,0 +1,52 @@
...
+	"io/fs"
+	"strings"
+	"unicode"
+)
+
+type KernelBootParam string
+
+const (
+	IsolatedCPUAffinityTransition KernelBootParam = "runc.exec.isolated-cpu-affinity-transition"
+	NohzFull                      KernelBootParam = "nohz_full"
```
Comment (kolyshkin) [inline libcontainer/system/kernelparam/lookup.go:13]: I'd just use the `string` directly, and remove these consts (move them to code that's using `LookupKernelBootParameters`)

File: libcontainer/system/kernelparam/lookup.go [hunk 15]
```diff
@@ -0,0 +1,52 @@
+package kernelparam
+
+import (
+	"io/fs"
+	"strings"
+	"unicode"
```
Comment (kolyshkin) [inline libcontainer/system/kernelparam/lookup.go:6]: I _think_ that kernel boot parameters is guaranteed to be in ASCII and not UTF-8, so maybe no `unicode` usage is required. Have to check that though.

File: docs/isolated-cpu-affinity-transition.md (hunk 12 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:32]: I don't get it, could you suggest the patch please ?

File: libcontainer/nsenter/nsexec.c (hunk 11 above)
Comment (cclerget) [reply libcontainer/nsenter/nsexec.c]: same

File: tests/integration/exec.bats (hunk 13 above)
Comment (cclerget) [reply tests/integration/exec.bats]: fixed

File: libcontainer/system/kernelparam/lookup.go (hunk 14 above)
Comment (cclerget) [reply libcontainer/system/kernelparam/lookup.go]: fixed

File: libcontainer/system/kernelparam/lookup.go (hunk 15 above)
Comment (cclerget) [reply libcontainer/system/kernelparam/lookup.go]: fixed

**Comment by cclerget** [comment]
> One other observation -- you add some code to the first commit, when remove most of it in the second one. Perhaps you can rework this to avoid doing that, as otherwise it's hard to review commit by commit.

Sorry about that, so I squashed the two commits and I'm pushing separate commits for each review rounds.

An additional note, my PR includes a similar fix to https://github.com/opencontainers/runc/pull/4041 which should work for all kernel, I don't know when the patch referred [here](https://lore.kernel.org/lkml/20220922180041.1768141-1-longman@redhat.com/) to reset the CPU affinity is going to be merged in kernel upstream, but even if it is, it won't fill the gap for a range of kernel version since 6.2

**Comment by cclerget** [comment]
Hello @kolyshkin @lifubang @AkihiroSuda , any chance to get it reviewed please ?

**Comment by arun2arunraj** [comment]
@AkihiroSuda : Any idea when this PR will be merged and released for public usage ?

**Comment by AkihiroSuda** [comment]
This PR is still marked as a draft, so this is not considered ready to be merged

File: docs/isolated-cpu-affinity-transition.md [hunk 16]
```diff
@@ -0,0 +1,74 @@
+## Isolated CPU affinity transition
+
+The introduction of the kernel commit 46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:3]: Version should be shown here

File: docs/isolated-cpu-affinity-transition.md [hunk 17]
```diff
@@ -0,0 +1,74 @@
...
+Some containerized real-time applications are relying on this deterministic
+behavior and uses the first CPU core to run a slow thread while other CPU
+cores are fully used by the real-time threads with SCHED_FIFO policy.
+Such applications can prevent runc process from joining a container when the
+runc process is randomly scheduled on a CPU core owned by a real-time thread.
+
+Runc introduces a way to restore this behavior via a dedicated kernel boot
+parameter:
+
+`runc.exec.isolated-cpu-affinity-transition`
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:20]: Why not use:
- an annotation in config.json
- a CLI flag for runc
- env var

Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:20]: This PR essentially targets kubernetes environments using realtime tuned profiles, that's why I choose a kernel param as it could be added as part of the tuned profile. I thought about annotations but I'm a bit hesitant for two reasons:
- for security reasons, in k8s environments with untrusted users, giving the possibility to alter such behavior through pod annotations might not be ideal
- interactions between annotations and runtimes in k8s CRI as highlighted [here](https://github.com/kubernetes/cri-api/blob/30022f215cd7c176a48d567186d153476fc46f7b/pkg/apis/runtime/v1/api.proto#L462-L469).

Regarding CLI flag and environment variable, it would require additional configuration by using a dedicated wrapper to pass the CLI flag or modifying systemd unit for the environment variable, plus the environment variable could not be passed correctly to runtime by CRI or others, those options are not really convenient IMHO.

I found kernel param approach to be the less intrusive and less coupled

Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: I mentioned an annotation in config.json, not an annotation in Kubernetes pod
https://github.com/opencontainers/runtime-spec/blob/main/config.md#annotations

Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: Also curious why not just add a new proper JSON field to config.json ?

Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:20]: Yes I understood, this fix needs to be enabled either system wide or per container primary in kubernetes environment running realtime applications without dealing with the OCI runtime spec, basically it should be deployed in environments with current tools like containerd/kubelet without any modifications at this level, so modifying the spec is not really an option. I mentionned about pod annotations as those can be passed to runtimes by CRI implementations like containerd/cri-o via OCI runtime spec annotations

**Comment by lifubang** [comment]
> One other observation -- you add some code to the first commit, when remove most of it in the second one. Perhaps you can rework this to avoid doing that, as otherwise it's hard to review commit by commit.

@kolyshkin @AkihiroSuda @cclerget 
Sorry for delay reply, this is becuase https://github.com/opencontainers/runc/pull/3923#issuecomment-1709337514 . @cclerget wanted us to choose which one is better? C or Go?

File: docs/isolated-cpu-affinity-transition.md (hunk 16 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:3]: done

**Comment by cclerget** [comment]
Hello @kolyshkin @lifubang @AkihiroSuda, I marked the PR as ready for review, the code is actually
well covered by various tests, the feature is disabled by default and can be enabled only with this
new kernel param such that it doesn't impact the current behavior.

I would also like to reiterate, there is also another important fix similar to https://github.com/opencontainers/runc/pull/4041 but covering all kernel since kernel 6.2. To give you an idea of the issue, you can add this [test](https://github.com/opencontainers/runc/pull/3923/files#diff-b03819d46bd922c514657ed0e4b8be870459566df28338bf30f6d8fcbd8f9719R448) to the main branch and run the tests on RHEL 9 or on a system with a kernel >= 6.2 and see the container process assigned to the first CPU only instead of all when runc is executed under specific CPU affinity.

I hope we could move forward quickly on this PR once you are all agree.

File: docs/isolated-cpu-affinity-transition.md (hunk 17 above)
Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: Pod annotations are not OCI annotations

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
I'm still not convinced why we have to introduce a kernel cmdline specifically for this

File: docs/isolated-cpu-affinity-transition.md (hunk 17 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:20]: Right, I'm just talking about how it would work from a kubernetes pov to enable this feature by using an OCI annotation like you've suggested instead of using the kernel param.

AFAIK containerd allow to pass (un)filtered pod annotations for CRI container runtime via `pod_annotations`:

```
[plugins."io.containerd.grpc.v1.cri".containerd]
  default_runtime_name = "runc"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
      runtime_type = "io.containerd.runc.v2"
      base_runtime_spec = "/etc/containerd/cri-base.json"
      pod_annotations = ["*", "*/*"]
      container_annotations = ["*", "*/*"]
```

While looks like cri-o automatically pass pod annotations and store them as OCI annotations.

Such that a pod annotated with `org.opencontainers.runc.exec.isolated-cpu-affinity-transition` by example would enable the feature for runc for exec probes or `kubectl exec`.

Is it this approach that you would prefer ?

Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:20]: @AkihiroSuda ^^

Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: > While looks like cri-o automatically pass pod annotations and store them as OCI annotations.

If this is true, it is a serious bug of cri-o.

> `org.opencontainers.runc.exec.isolated-cpu-affinity-transition`

SGTM

Comment (haircommander) [reply docs/isolated-cpu-affinity-transition.md:20]: how else would a k8s user specify annotations for the oci runtime?

Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: > how else would a k8s user specify annotations for the oci runtime? just image annotations??

No, non-admin user mustn't be able to specify OCI annotations that change the behavior of the runtime.

Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md]: @AkihiroSuda changes committed in https://github.com/opencontainers/runc/pull/3923/commits/197b60daec3f9257811f350da46f15adec24a8d4 to use OCI annotation instead of kernel param

File: docs/isolated-cpu-affinity-transition.md [hunk 18]
```diff
@@ -0,0 +1,148 @@
...
+Some containerized real-time applications are relying on this deterministic
+behavior and uses the first CPU core to run a slow thread while other CPU
+cores are fully used by the real-time threads with SCHED_FIFO policy.
+Such applications can prevent runc process from joining a container when the
+runc process is randomly scheduled on a CPU core owned by a real-time thread.
+
+Runc introduces a way to restore this behavior by adding the following
+annotation to the container runtime spec (`config.json`):
+
+`org.opencontainers.runc.exec.isolated-cpu-affinity-transition`
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:20]: This list should be updated too
https://github.com/opencontainers/runc/blob/8e69225e2e5f25c46e79cf49935db362ead8f496/features.go#L67-L71

File: docs/isolated-cpu-affinity-transition.md [hunk 19]
```diff
@@ -0,0 +1,148 @@
...
+
+#### Pod deployment example
+
+```yaml
+apiVersion: v1
+kind: Pod
+metadata:
+  name: demo-pod
+  annotations:
+    org.opencontainers.runc.exec.isolated-cpu-affinity-transition: "temporary"
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:121]: This is not needed for containerd IIUC

File: docs/isolated-cpu-affinity-transition.md [hunk 20]
```diff
@@ -0,0 +1,148 @@
...
+annotation allowed to be passed to the container runtime in `/etc/containerd/config.toml`:
+
+```toml
+[plugins."io.containerd.grpc.v1.cri".containerd]
+  default_runtime_name = "runc"
+  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
+    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
+      runtime_type = "io.containerd.runc.v2"
+      base_runtime_spec = "/etc/containerd/cri-base.json"
+      pod_annotations = ["org.opencontainers.runc.exec.isolated-cpu-affinity-transition"]
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:105]: `container_annotations` might be better here, as the annotation does not really relate to Kubernetes pods
https://github.com/containerd/containerd/blob/v1.7.14/docs/cri/config.md?plain=1#L310

File: docs/isolated-cpu-affinity-transition.md [hunk 21]
```diff
@@ -0,0 +1,148 @@
...
+  name: demo-pod
+  annotations:
+    org.opencontainers.runc.exec.isolated-cpu-affinity-transition: "temporary"
+spec:
+  containers:
+  - name: demo
+    image: registry.com/demo:latest
+```
+
+#### Deployment template example
```
Comment (AkihiroSuda) [inline docs/isolated-cpu-affinity-transition.md:128]: This might be redundant

**Comment by AkihiroSuda** [comment]
Please squash the commits when this PR is ready to be merged

File: docs/isolated-cpu-affinity-transition.md (hunk 18 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:20]: Ok, do you know if CRI implementations like containerd are using this list actually to automatically exclude annotations ?

File: docs/isolated-cpu-affinity-transition.md (hunk 19 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:121]: I guess it's related to your comment about `container_annotations`, because I don't see how runc could enable the feature without that

File: docs/isolated-cpu-affinity-transition.md (hunk 20 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:105]: From my tests only `pod_annotations` is working and pass the annotation to sandbox and container, `container_annotations` are coming from device plugins and kubernetes internals, like stated in the comment this is not controlled by users, preventing users to enable the feature on a per-pod basis

File: docs/isolated-cpu-affinity-transition.md (hunk 21 above)
Comment (cclerget) [reply docs/isolated-cpu-affinity-transition.md:128]: I will remove it

File: docs/isolated-cpu-affinity-transition.md (hunk 18 above)
Comment (AkihiroSuda) [reply docs/isolated-cpu-affinity-transition.md:20]: Not yet

**Comment by cclerget** [comment]
Ok I've pushed the requested changes, I haven't applied changes related to your comments https://github.com/opencontainers/runc/pull/3923#pullrequestreview-1962335750 and https://github.com/opencontainers/runc/pull/3923#pullrequestreview-1962330692, please let me know if you disagree with my comments, otherwise I'll go ahead and squash commits

**Comment by cclerget** [comment]
@AkihiroSuda commits squashed

**Review by AkihiroSuda — APPROVED** [review]

File: libcontainer/cgroups/fs/fs.go [hunk 22]
```diff
@@ -263,3 +265,26 @@ func (m *Manager) OOMKillCount() (uint64, error) {
...
+func GetEffectiveCPUs(cpusetPath string, cgroups *configs.Cgroup) string {
+	// Fast path.
+	if cgroups.CpusetCpus != "" {
+		return cgroups.CpusetCpus
+	} else if !strings.HasPrefix(cpusetPath, defaultCgroupRoot) {
+		return ""
+	}
+
+	// Iterates until it goes to the cgroup root path.
+	for path := filepath.Clean(cpusetPath); path != defaultCgroupRoot; path = filepath.Dir(path) {
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/fs.go:282]: AFAIK filepath.Clean is not needed here because m.Path returns cleaned path.

File: libcontainer/cgroups/fs/fs.go [hunk 23]
```diff
@@ -263,3 +265,26 @@ func (m *Manager) OOMKillCount() (uint64, error) {
...
+
+func GetEffectiveCPUs(cpusetPath string, cgroups *configs.Cgroup) string {
+	// Fast path.
+	if cgroups.CpusetCpus != "" {
+		return cgroups.CpusetCpus
+	} else if !strings.HasPrefix(cpusetPath, defaultCgroupRoot) {
+		return ""
+	}
+
+	// Iterates until it goes to the cgroup root path.
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/fs.go:281]: Maybe makes sense to add something like "needed for containers in which cpuset controller is not enabled -- in this case a parent cgroup is used" -- if my understanding is correct.

File: libcontainer/process_linux.go [hunk 24]
```diff
@@ -133,8 +137,58 @@ func (p *setnsProcess) start() (retErr error) {
...
+
+			_, annotations := utils.Annotations(p.config.Config.Labels)
+			cpuAffinity, definitive, err = isolatedCPUAffinityTransition(
+				os.DirFS("/"),
+				cg.CpusetCpus,
+				annotations,
+			)
+			if err != nil {
+				// Close the pipe to not be blocked in the parent.
+				p.comm.closeChild()
```
Comment (kolyshkin) [inline libcontainer/process_linux.go:175]: ditto

File: libcontainer/process_linux.go [hunk 25]
```diff
@@ -995,5 +1069,196 @@ func setIOPriority(ioprio *configs.IOPriority) error {
...
+
+// startCommandWithCPUAffinity starts a command on a specific CPU if set.
+func startCommandWithCPUAffinity(cmd *exec.Cmd, cpuAffinity int) error {
+	errCh := make(chan error)
+	defer close(errCh)
+
+	// Use a goroutine to dedicate an OS thread.
+	go func() {
+		cpuSet := new(unix.CPUSet)
+		cpuSet.Zero()
```
Comment (kolyshkin) [inline libcontainer/process_linux.go:1217]: AFAIK this is not needed, in Go everything is initialized to default values (0s in this case), and you've just instantiated a new CPUSet.

File: tests/integration/exec.bats [hunk 26]
```diff
@@ -340,3 +340,168 @@ EOF
 	[ ${#lines[@]} -eq 1 ]
 	[[ ${lines[0]} = *"exec /run.sh: no such file or directory"* ]]
 }
+
+@test "runc exec with isolated cpus affinity temporary transition [cgroup cpuset]" {
+	requires root
```
Comment (kolyshkin) [inline tests/integration/exec.bats:345]: need to add `cgroups_cpuset` to the requires list.

File: tests/integration/exec.bats [hunk 27]
```diff
@@ -340,3 +340,168 @@ EOF
...
+	mems="$(cat /sys/devices/system/node/online 2>/dev/null || true)"
+	[[ -n $mems ]] && update_config ".linux.resources.cpu.mems = \"$mems\""
+
+	runc run -d --console-socket "$CONSOLE_SOCKET" test_isolated_temporary_transition
+	[ "$status" -eq 0 ]
+
+	# set all online cpus as isolated
+	echo "nohz_full=$all_cpus" >"$tmp/cmdline"
+
+	mount --bind "$tmp/cmdline" /proc/cmdline
```
Comment (kolyshkin) [inline tests/integration/exec.bats:367]: who's undoing this mount?

Comment (kolyshkin) [reply tests/integration/exec.bats:367]: my bad, missed the line below.

File: tests/integration/exec.bats (hunk 26 above)
Comment (kolyshkin) [reply tests/integration/exec.bats:345]: Same for other tests

File: tests/integration/exec.bats [hunk 28]
```diff
@@ -340,3 +340,168 @@ EOF
...
+	all_cpus="$(cat /sys/devices/system/cpu/online)"
+
+	update_config ".linux.resources.cpu.cpus = \"$all_cpus\""
+
+	# set temporary isolated CPU affinity transition
+	update_config '.annotations += {"org.opencontainers.runc.exec.isolated-cpu-affinity-transition": "temporary"}'
+
+	local mems
+	mems="$(cat /sys/devices/system/node/online 2>/dev/null || true)"
+	[[ -n $mems ]] && update_config ".linux.resources.cpu.mems = \"$mems\""
```
Comment (kolyshkin) [inline tests/integration/exec.bats:359]: Perhaps you can separate this into a function (at least the mems and all_cpus part).

File: tests/integration/exec.bats [hunk 29]
```diff
@@ -340,3 +340,168 @@ EOF
...
+	runc exec test_isolated_definitive_transition grep "Cpus_allowed_list:" /proc/self/status
+
+	umount /proc/cmdline
+
+	[ "$status" -eq 0 ]
+
+	load /etc/os-release
+
+	# fix unbound variable in condition below
+	PLATFORM_ID=${PLATFORM_ID:-}
```
Comment (kolyshkin) [inline tests/integration/exec.bats:414]: nit: can you use `VERSION_ID` instead, it looks easier?

File: libcontainer/process_linux.go [hunk 30]
```diff
@@ -133,8 +137,58 @@ func (p *setnsProcess) start() (retErr error) {
...
+	// from joining a container when the runc process is randomly
+	// scheduled on a CPU core owned by a real-time thread.
+	cpuAffinity := -1
+	resetCPUAffinity := true
+
+	if len(p.manager.GetPaths()) > 0 {
+		// Get the target container cgroup.
+		if cg, err := p.manager.GetCgroups(); err != nil {
+			// Close the pipe to not be blocked in the parent.
+			p.comm.closeChild()
```
[the remark this answers is not in the document]
Comment (cclerget) [reply libcontainer/process_linux.go:162]: Not enough, the defer closes the parent side of the pipe, we also need to close the child side otherwise the process get stuck

File: libcontainer/process_linux.go (hunk 24 above)
Comment (cclerget) [reply libcontainer/process_linux.go:175]: same

**Comment by cclerget** [comment]
@kolyshkin addressed your comments in https://github.com/opencontainers/runc/pull/3923/commits/ea7b6c03c026310013f6cc16c8a03b1cee3fcfce, will squash the commits after approval

File: docs/isolated-cpu-affinity-transition.md [hunk 31]
```diff
@@ -0,0 +1,126 @@
+## Isolated CPU affinity transition
+
+The introduction of the kernel commit 46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76
+in 5.7 has affected a deterministic scheduling behavior by distributing tasks
+across CPU cores within a cgroups cpuset. It means that some runc operations
+like `runc exec` might be impacted under some circumstances, by example when
```
Comment (andreaskaris) [inline docs/isolated-cpu-affinity-transition.md:6]: Not a review, just a question (but maybe you'll decide to clarify this further). Without looking at the code, and only at this piece of documentation (and at the commit message):
* will this only improve the behavior of threads launched with `runc exec`?  (if so, then the documentation should not be "some runc operations like")
* otherwise, what other commands or situations will benefit from this patch? (i.e., in which cases do I want to annotate my pods with this annotation to revert to the behavior pre 46a87b3851f0d6eb05e6d83d5c5a30df0eca8f76)
* related to the above, will this change the behavior of any new process spawned in the container (an example would be a DPDK application using the vhost device to create kernel vhost threads, would those still float around freely, or be sent to the first CPU with the annotation in place

Comment (andreaskaris) [reply docs/isolated-cpu-affinity-transition.md]: Awesome, thanks for the clarification and thanks for your work on this!

**Comment by cclerget** [comment]
@kolyshkin changes ok with you ?

**Review by kolyshkin — APPROVED** [review]
LGTM; please squash the commits

**Comment by cclerget** [comment]
Done thanks !

**Comment by MatthewHink** [comment]
Thank goodness this is finally merged! Really appreciate your help everyone!

**Comment by kolyshkin** [comment]
The more I look into this the more I think I did a bad job reviewing this, and it needs to be redone in a different way:
1. There's too much logic here figuring out which CPUs to use. Runc is a low level tool and is not supposed to be that "smart".
2. What's worse, this logic is executed on every exec, making it slower.
3. Some of the logic in `(*setnsProcess).start` is executed even if no annotation is set, thus making ALL execs slow.
4. As pointed out in https://github.com/opencontainers/runtime-spec/pull/1252, if we want to support this across different runtimes (e.g. crun and runc), this should not be an annotation, but rather a process parameter.

Let's fix this:
1. Revert this PR.
2. Move some of the functionality (determining which CPU to pin exec to) to upper level runtime (cri-o/containerd).
3. Open a PR in runtime-spec proposing the changes to runc/crun.
4. Open a PR to runc implementing that proposal.

**Comment by NeilHanlon** [comment]
while I recognize that this is a complex issue, I am unsure if reverting this is the best path forward, considering implementations of this are already deployed and in use.

This review has taken an exceedingly long time and we are now on the cusp of even *more* review.

It would be disappointing if we have to start this whole process over again.

**Comment by kolyshkin** [comment]
> while I recognize that this is a complex issue, I am unsure if reverting this is the best path forward, considering implementations of this are already deployed and in use.
> 
> This review has taken an exceedingly long time and we are now on the cusp of even _more_ review.
> 
> It would be disappointing if we have to start this whole process over again.

I have to admit I did a sloppy job reviewing this; yet this is not in any of the released runc versions (and this is why it needs to be reverted now, before we officially release it).

Now, this has to be re-implemented in the right way, starting from runtime-spec (see https://github.com/opencontainers/runtime-spec/pull/1253), then in runtimes (such as cri-o and containerd), when in low level runtimes (such as runc and crun).

Any help (esp in cri-o and containerd) is appreciated.

**Comment by kolyshkin** [comment]
@cclerget I am sorry this had to be reverted, but now when  opencontainers/runtime-spec#1253 is merged we can work on reviving it if you're still interested. Now, 90% of the work is to be done by containerd/cri-o (they should do the work of converting pod annotation (what used to be `org.opencontainers.runc.exec.isolated-cpu-affinity-transition`) to `process.ExecCPUAffinity` setting for runc, and runc should only enforce the affinity.

Let me know if you still want to work on this and we'll figure it out.

**Comment by cclerget** [comment]
@kolyshkin It's unfortunate but understand the rational behind this decision.

I'm more concerned about the revert of the fix not directly related to the original issue like mentioned in my comment https://github.com/opencontainers/runc/pull/3923#issuecomment-1948291803.

It has also been noted by the customer when using a tuned profile like CPU-partitioning, the CPU affinity patch at least on kernel < 6.2 or RHEL < 9 doesn't fix the runc "noisy neighbor" behavior after cgroup transition, on those kernels and systems `execCPUAffinity.final` won't be effective without a rework of cgroup handling, I'm not sure if this would work with the various cgroup managers, but the idea is to create a child cgroup (let's call it `nsexec`) under the container cgroup when `execCPUAffinity.initial` is set and `execCPUAffinity.final` is set and different, in order to put the runc exec process in this `nsexec` child cgroup, such that this child cgroup could set a more restricted cpuset reflecting `execCPUAffinity.final` when different from `execCPUAffinity.initial` and restrict the executed process to this specific cpuset to remediate to the "noisy neighbor" behavior. Does that make sense ?

I'd like to but right now I haven't much room to work on it, maybe in two weeks

**Comment by jsco2t** [comment]
@kolyshkin has there been any commitment by `containerd/cri-o` as to when they might land their portion of this solution? I looked through the recent issues in `containerd` but didn't see anything to suggest to me that they were doing planning around this feature area (though I certainly could have missed it).
