### PR TITLE
Fix regression of exec command

### LINKED ISSUE #1264: runc exec requires command to be passed on CLI
It seems that [this commit](https://github.com/opencontainers/runc/commit/b517076907b7c18d7a1f296ec390cf3f275e2375) introduced a minArgs requirement of 2 for `runc exec`, with the second arg consisting of a process to run.

Is this actually a requirement here? Previously we were able to run `runc exec` by passing `-p process.json` containing the command to run etc.

Would it be ok to make the `<container command>` optional again?
We'd be happy to submit the PR.

Thanks!
Ed & Konstantinos

### PR DESCRIPTION
**Pull request by WeiZhang555**
Fixes #1264

Set minimal required args to 1 for `exec` command to roll back to
previous behavior, also modify help message a little bit.

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
ping @cyphar

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

File: exec.go [hunk 1]
```diff
@@ -86,7 +87,7 @@ following will output a list of processes running in the container:
 		},
 	},
 	Action: func(context *cli.Context) error {
-		if err := checkArgs(context, 2, minArgs); err != nil {
+		if err := checkArgs(context, 1, minArgs); err != nil {
```
Comment (cyphar) [inline exec.go]: This should actually be conditional based on whether `-p` was provided. I'll write a patch to fix it.
