### PR TITLE
check that StartTransientUnit/StopUnit succeeds

### LINKED ISSUE #2313: runc --systemd-cgroup run: need to check that StartTransientUnit succeeds
**TL;DR: runc should check that system was able to create a unit.**

I was working on runc on a Fedora 31 Vagrant box with older selinux packages (`container-selinux-2.117.0-1.gitbfde70a.fc31.noarch`). Command `runc --systemd run xoo` succeeded, but the container process was running in the same cgroup as my shell, and the designated cgroup was empty (see https://github.com/opencontainers/runc/issues/2310 for details).

```console
# runc --systemd run xoo
# runc list
ID          PID         STATUS      BUNDLE         CREATED                          OWNER
xoo         16201       running     /vagrant/tst   2020-04-14T02:23:16.049427501Z   root
# cat /proc/16201/cgroup 
0::/user.slice/user-1000.slice/session-3.scope
# cat /proc/self/cgroup 
0::/user.slice/user-1000.slice/session-3.scope
```

journalctl shows:
```
Apr 14 02:23:16 localhost.localdomain audit[1]: AVC avc:  denied  { setsched } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
Apr 14 02:23:16 localhost.localdomain systemd[1]: runc-xoo.scope: Failed to add PIDs to scope's control group: Permission denied
Apr 14 02:23:16 localhost.localdomain systemd[1]: runc-xoo.scope: Failed with result 'resources'.
Apr 14 02:23:16 localhost.localdomain systemd[1]: Failed to start libcontainer container xoo.
```

So, systemd failed to create a unit, but runc did not show any errors (it's the same with podman+crun).

When trying to start a unit with `systemd.run`, it shows an error:
```
# systemd-run --scope sleep 999
Job failed. See "journalctl -xe" for details.
# journalctl -xe
...
Apr 14 02:36:49 localhost.localdomain audit[1]: AVC avc:  denied  { setsched } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
Apr 14 02:36:49 localhost.localdomain systemd[1]: foobar.scope: Failed to add PIDs to scope's control group: Permission denied
Apr 14 02:36:49 localhost.localdomain systemd[1]: foobar.scope: Failed with result 'resources'.
Apr 14 02:36:49 localhost.localdomain systemd[1]: Failed to start /usr/bin/sleep 999.
...
```

### LINKED ISSUE #2344: cgroup2/systemd: remove /sys/fs/cgroup/system.slice/runc-test.scope: device or resource busy
When we don't use `pid` namespace or use pid namespace with path in `config.json`, we can reproduce it by steps:
```
[root@localhost systemdtest]# runc --systemd-cgroup run -d test
[root@localhost systemdtest]# runc --systemd-cgroup exec -d test sleep 2000000
[root@localhost systemdtest]# cat /sys/fs/cgroup/system.slice/runc-test.scope/cgroup.procs
278991
279011
[root@localhost systemdtest]# runc --systemd-cgroup delete -f test
ERRO[0000] remove /sys/fs/cgroup/system.slice/runc-test.scope: device or resource busy
```

### PR DESCRIPTION
**Pull request by lifubang**
fix #2313(relate to #2310) #2344 

To fix #2313 
We can check whether `StartTransientUnit` succeeds or not with the value from the channel.
If we got `failed`, we should run `ResetFailedUnit` and return the error.

```
[root@localhost systemdtest]# runc --systemd-cgroup run -d test
WARN[0000] signal: killed                               
ERRO[0000] cannot detect unified path                   
ERRO[0000] container_linux.go:349: starting container process caused "process_linux.go:306: applying cgroup configuration for process caused \"StartTransientUnit job is not done: failed\"" 
container_linux.go:349: starting container process caused "process_linux.go:306: applying cgroup configuration for process caused \"StartTransientUnit job is not done: failed\""
```
The error `ERRO[0000] cannot detect unified path` relates to #2329 .

To fix #2344 
We should wait `StopUnit` succeeds.

Signed-off-by: lifubang <lifubang@acmcoder.com>

### CODE REVIEW

**Comment by lifubang** [comment]
@kolyshkin PTAL

File: libcontainer/cgroups/systemd/unified_hierarchy.go [hunk 1]
```diff
@@ -136,7 +137,11 @@ func (m *UnifiedManager) Apply(pid int) error {
 	statusChan := make(chan string, 1)
 	if _, err := dbusConnection.StartTransientUnit(unitName, "replace", properties, statusChan); err == nil {
 		select {
-		case <-statusChan:
+		case s := <-statusChan:
+			if s != "done" {
+				dbusConnection.ResetFailedUnit(unitName)
+				return fmt.Errorf("StartTransientUnit job is not done: %s", s)
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/unified_hierarchy.go:143]: 1. I would make the error message more user-friendly. Say, something like
```go
"error creating systemd unit `%s`: got `%s`", unitName, s);
```

2. You can use `errors.Errorf()` like everywhere else in this file.

**Comment by kolyshkin** [comment]
@lifubang have you tested that the fix works? I have described the repro in details here: https://github.com/containers/crun/pull/331#issuecomment-614984042, should take 10-15 minutes to check it (mostly waiting for vagrant up).

**Comment by lifubang** [comment]
> Can you also add the same code (wait for the operation to complete, check it's "done", return an error if not) to the `Destroy()` method. Currently it does not even wait.
> 
> Oh, finally, could you please wait until #2299 is merged and then rebase? It is mostly code refactoring in there.

OK

**Comment by lifubang** [comment]
> have you tested that the fix works?

I have test it in vmware.

File: libcontainer/cgroups/systemd/unified_hierarchy.go [hunk 2]
```diff
@@ -167,18 +171,42 @@ func (m *UnifiedManager) Destroy() error {
...
+			logrus.Warnf("Timed out while waiting for StopUnit(%s) completion signal from dbus. Continuing...", unitName)
+		}
+	} else {
+		// TODO: When we destroy cgroup, the initProcess has been killed, so we always get `Unit **** not loaded` err.
+		// Because the unit is created by StartTransientUnit method,
+		// so when process exited, the cgroup path may has been deleted by systemd.
+		// Because of this, we should not return the error.
+		// But if the system is very busy, we may not get this error by chance.
+		// Shall we need to always warn this information?
+		logrus.Warnf("error stopping systemd unit `%s`: got `%s`. Continuing...", unitName, err)
```
Comment (lifubang) [inline libcontainer/cgroups/systemd/unified_hierarchy.go:205]: @kolyshkin 
Shall we need to always warn this information?
When we destroy cgroup, the initProcess has been killed, so we will always get `Unit **** not loaded` err.
Because the unit is created by StartTransientUnit method,
so when process exited, the cgroup path may has been deleted by systemd.
Because of this, we should not return the error.
But if the system is very busy, we may not get this error by chance.

Comment (lifubang) [reply libcontainer/cgroups/systemd/unified_hierarchy.go:205]: I think I should move this commit to #2329 , and discuss in there.
WDYT @kolyshkin

**Comment by lifubang** [comment]
> Can you also add the same code (wait for the operation to complete, check it's "done", return an error if not) to the `Destroy()` method. Currently it does not even wait.

I add it in #2329

**Comment by kolyshkin** [comment]
Needs rebase

File: libcontainer/cgroups/systemd/v2.go [hunk 3]
```diff
@@ -139,7 +140,11 @@ func (m *unifiedManager) Apply(pid int) error {
 	statusChan := make(chan string, 1)
 	if _, err := dbusConnection.StartTransientUnit(unitName, "replace", properties, statusChan); err == nil {
 		select {
-		case <-statusChan:
+		case s := <-statusChan:
+			if s != "done" {
```
Comment (mrunalp) [inline libcontainer/cgroups/systemd/v2.go:144]: Is there a constant for this defined somewhere? If not, can create one and add a link to the API where it says it is expected to return `done` here? It may be helpful if we run into any compatibility issues in the future.

Comment (kolyshkin) [reply libcontainer/cgroups/systemd/v2.go:144]: Even in systemd sources those are not defined, for example, see https://github.com/systemd/systemd/blob/33b58dfb41a0c0db8110f1fc6dd0fc54e0d9cd4a/src/shared/bus-wait-for-jobs.c#L281 (and above).

It is somewhat described in e.g. https://godoc.org/github.com/coreos/go-systemd/dbus#Conn.StartUnit or https://www.freedesktop.org/wiki/Software/systemd/dbus/

Comment (lifubang) [reply libcontainer/cgroups/systemd/v2.go]: @mrunalp 
Besides @kolyshkin 's description, we can also Refer to https://github.com/coreos/go-systemd/blob/5a0db84d3dc459ccdc6ffcc44b1c452bf9f171cb/dbus/methods.go#L78-L101

I have add a constant now.

File: libcontainer/cgroups/systemd/v2.go [hunk 4]
```diff
@@ -168,7 +173,18 @@ func (m *unifiedManager) Destroy() error {
...
 		return err
 	}
-	dbusConnection.StopUnit(getUnitName(m.cgroups), "replace", nil)
+	unitName := getUnitName(m.cgroups)
+	statusChan := make(chan string, 1)
+	if _, err := dbusConnection.StopUnit(unitName, "replace", statusChan); err == nil {
+		select {
+		case s := <-statusChan:
+			if DbusJobCompletionResultType(s) != DbusJobDone {
+				logrus.Warnf("error stopping unit `%s`: got `%s`. Continuing...", unitName, s)
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/v2.go:182]: I think `s/stopping/removing/` is better.

File: libcontainer/cgroups/systemd/common.go [hunk 5]
```diff
@@ -11,6 +11,26 @@ import (
...
+// has been canceled  before it finished execution. timeout indicates that the
+// job timeout was reached. failed indicates that the job failed. dependency
+// indicates that a job this job has been depending on failed and the job hence
+// has been removed too. skipped indicates that a job was skipped because it
+// didn't apply to the units current state.
+type DbusJobCompletionResultType string
+
+const (
+	DbusJobDone       DbusJobCompletionResultType = "done"
+	DbusJobCanceled   DbusJobCompletionResultType = "canceled"
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/common.go:27]: Are you using any of those (I mean, except for `DbusJobDone`)?

File: libcontainer/cgroups/systemd/common.go [hunk 6]
```diff
@@ -11,6 +11,26 @@ import (
 	"github.com/opencontainers/runc/libcontainer/configs"
 )
 
+// Refer to https://github.com/coreos/go-systemd/blob/5a0db84d3dc459ccdc6ffcc44b1c452bf9f171cb/dbus/methods.go#L78-L101
+// or https://godoc.org/github.com/coreos/go-systemd/dbus#Conn.StartUnit
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/common.go:15]: these two are the same: one is the source code, another is godoc extracted from it.

And we only need "done", let's not overcomplicate things.

File: libcontainer/cgroups/systemd/v2.go (hunk 4 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/v2.go]: done!

File: libcontainer/cgroups/systemd/common.go (hunk 5 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/common.go]: Remove now!

File: libcontainer/cgroups/systemd/common.go (hunk 6 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/common.go]: Done

File: libcontainer/cgroups/systemd/v2.go (hunk 3 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/v2.go:145]: add a link to the API address now. @mrunalp

File: libcontainer/cgroups/systemd/common.go (hunk 6 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/common.go]: In v1, shall we need to add this?
If yes, I'll add a const string `DbusJobDone`.

**Comment by lifubang** [comment]
> Can you also add the same code (wait for the operation to complete, check it's "done", return an error if not) to the `Destroy()` method. Currently it does not even wait.

@kolyshkin this code also can fix #2344

File: libcontainer/cgroups/systemd/v2.go [hunk 7]
```diff
@@ -168,7 +174,19 @@ func (m *unifiedManager) Destroy() error {
...
-	dbusConnection.StopUnit(getUnitName(m.cgroups), "replace", nil)
+	unitName := getUnitName(m.cgroups)
+	statusChan := make(chan string, 1)
+	if _, err := dbusConnection.StopUnit(unitName, "replace", statusChan); err == nil {
+		select {
+		case s := <-statusChan:
+			// Please refer to https://godoc.org/github.com/coreos/go-systemd/dbus#Conn.StartUnit
+			if s != "done" {
+				logrus.Warnf("error removing unit `%s`: got `%s`. Continuing...", unitName, s)
+			}
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/systemd/v2.go:185]: The channel can be closed here?

Comment (lifubang) [reply libcontainer/cgroups/systemd/v2.go:185]: I think we should not close the channel, because if someone send string to this closed channel, it will cause goroutine panic. Although I guess there is nobody would send sth to this channel.

**Comment by kolyshkin** [comment]
> this code also can fix #2344
Nice! @lifubang please update the description to say so (and about the StopUnit, too).

File: libcontainer/cgroups/systemd/v2.go (hunk 7 above)
Comment (kolyshkin) [reply libcontainer/cgroups/systemd/v2.go:185]: I checked the `github.com/coreos/go-systemd/dbus` code.

Looks like once it sends a string over the channel it forgets it. So yes we should close the channel -- unless we hit the timeout!

**Comment by kolyshkin** [comment]
So, I guess this code should be moved to `libcontainer/cgroups/systemd/common.go` and used from both v1 and v2.

File: libcontainer/cgroups/systemd/v2.go (hunk 7 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/v2.go]: finished now

**Comment by lifubang** [comment]
Both v1 and v2 are using the same `StartTransientUnit/StopUnit` method now, and close the channel when finished now.

File: libcontainer/cgroups/systemd/common.go [hunk 8]
```diff
@@ -99,3 +102,51 @@ func isUnitExists(err error) bool {
 	}
 	return false
 }
+
+func startJob(unitName string, properties []systemdDbus.Property) error {
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/common.go:106]: `s/startJob/startUnit/`

File: libcontainer/cgroups/systemd/common.go [hunk 9]
```diff
@@ -99,3 +102,51 @@ func isUnitExists(err error) bool {
...
+			logrus.Warnf("Timed out while waiting for StartTransientUnit(%s) completion signal from dbus. Continuing...", unitName)
+		}
+	} else if !isUnitExists(err) {
+		return err
+	}
+
+	return nil
+}
+
+func stopJob(unitName string) error {
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/common.go:132]: s/stopJob/stopUnit/

File: libcontainer/cgroups/systemd/common.go (hunk 8 above)
Comment (kolyshkin) [reply libcontainer/cgroups/systemd/common.go:106]: Job is a very misleading term here.

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
needs rebase

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
@kolyshkin LGTY?

File: libcontainer/cgroups/systemd/v1.go [hunk 10]
```diff
@@ -226,14 +213,9 @@ func (m *LegacyManager) Destroy() error {
...
-	if err != nil {
-		return err
-	}
-
-	dbusConnection.StopUnit(getUnitName(m.Cgroups), "replace", nil)
-	if err := cgroups.RemovePaths(m.Paths); err != nil {
-		return err
+	unitName := getUnitName(m.Cgroups)
+	if err := stopUnit(unitName); err != nil {
+		return nil
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/systemd/v1.go:218]: return err?

File: libcontainer/cgroups/systemd/v2.go [hunk 11]
```diff
@@ -175,14 +161,13 @@ func (m *unifiedManager) Destroy() error {
 	m.mu.Lock()
 	defer m.mu.Unlock()
 
-	dbusConnection, err := getDbusConnection()
-	if err != nil {
-		return err
+	unitName := getUnitName(m.cgroups)
+	if err := stopUnit(unitName); err != nil {
+		return nil
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/systemd/v2.go:166]: return err?

**Comment by AkihiroSuda** [comment]
Also needs https://github.com/opencontainers/runc/pull/2331

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by kolyshkin** [comment]
LGTM
