### PR TITLE
Fix tmpfs mode opts when dir already exists

### LINKED ISSUE #3911: tmpfs mounts with pre-existing dir (effecitvely) ignores mode options
### Description

Lets say you have a tmpfs mount like so:

```json
{ "destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"] }
```

If a directory already exists in the rootfs for the destination the mode set during mount is overwritten by the original mode on that directory.
This seems to be cause here: https://github.com/opencontainers/runc/blob/bcaee38a9a1d1d13b274a569008067321dcf9c70/libcontainer/rootfs_linux.go#L446-L468

Where a `stat` is called, if the stat does not fail at the end, after mount, a `chmod` is performed.
Where this is particularly problematic is when re-using the same rootfs (e.g. restarting a container) because it also does an `mkdir(dest, 0755)`. So the next time a container is started with that rootfs the stat call will succeed and any mode set by the mount is overwritten.

### Steps to reproduce the issue

Using ctr for simplicity of getting a rootfs:

```console
$ mkdir -p /tmp/test/rootfs
$ sudo ctr image mount docker.io/library/busybox:latest /tmp/test/rootfs
$ sudo runc spec --bundle /tmp/test # creates a default runc spec
$ sudo mv /tmp/test/config.json /tmp/test/config.json.orig
$ sudo jq '.process += { "args": ["stat", "-c", "%a", "/tmp/test"]} | .mounts += [{ "destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"] }]' /tmp/test/config.json.orig > /tmp/test/config.json
$ sudo runc run --bundle /tmp/test
444
$ sudo runc run --bundle /tmp/test
755
```

### Describe the results you received and expected

The target directory mode is set to the pre-existing directory's mode rather than the mode set in the mount.
After a container restart the mode actually changes in the above example which is highly unexpected.

I suspect this could be fixed by looking for a mode option and using that when doing the mkdir, though technically this is only a partial fix because the same rootfs could technically be used with different mount options.
Alternatively I guess `chmod` could be skipped if `mode` is set in the options.

### What version of runc are you using?
```
runc version 1.1.7
commit: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
spec: 1.0.2-dev
go: go1.19.10
libseccomp: 2.5.3
```

### Host OS information

```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Host kernel information

```
Linux dev2 5.15.0-1040-azure #47-Ubuntu SMP Thu Jun 1 19:38:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

ref: https://github.com/docker/for-linux/issues/138

### PR DESCRIPTION
**Pull request by cpuguy83**
When a directory already exists (or after a container is restarted) the perms of the directory being mounted to were being used even when a different permission is set on the tmpfs mount options.

This prepends the original directory perms to the mount options. If the perms were already set in the mount opts then those perms will win.
This eliminates the need to perform a chmod after mount entirely.

Fixes #3911

### CODE REVIEW

File: libcontainer/rootfs_linux.go [hunk 1]
```diff
@@ -450,22 +450,21 @@ func mountToRootfs(c *mountConfig, m mountEntry) error {
 			}
 		}
 
+		if stat != nil {
```
Comment (kolyshkin) [inline libcontainer/rootfs_linux.go:453]: nit: maybe change this to `else` (of the previous `if err != nil`)?

**Comment by kolyshkin** [comment]
LGTM overall. I've checked the test fails before the fix, and changed it slightly so that if it fails we see what the stat output is (and simplified it a bit).

```bats
@test "runc run with tmpfs perms" {
        # shellcheck disable=SC2016
        update_config '.process.args = ["sh", "-c", "stat -c %a /tmp/test"]'
        update_config '.mounts += [{"destination": "/tmp/test", "type": "tmpfs", "source": "tmpfs", "options": ["mode=0444"]}]'

        # Directory is to be created by runc.
        runc run test_tmpfs
        [ "$status" -eq 0 ]
        [ "$output" = "444" ]

        # Run a 2nd time with the pre-existing directory.
        # Ref: https://github.com/opencontainers/runc/issues/3911
        runc run test_tmpfs
        [ "$status" -eq 0 ]
        [ "$output" = "444" ]

        # Existing directory, custom perms, no mode on the mount,
        # so it should use the directory's perms.
        update_config '.mounts[-1].options = []'
        chmod 0710 rootfs/tmp/test
        # shellcheck disable=SC2016
        runc run test_tmpfs
        [ "$status" -eq 0 ]
        [ "$output" = "710" ]

        # Add back the mode on the mount, and it should use that instead.
        # Just for fun, use different perms than was used earlier.
        # shellcheck disable=SC2016
        update_config '.mounts[-1].options = ["mode=0410"]'
        runc run test_tmpfs
        [ "$status" -eq 0 ]
        [ "$output" = "410" ]
}
```

File: libcontainer/rootfs_linux.go (hunk 1 above)
Comment (cpuguy83) [reply libcontainer/rootfs_linux.go]: Updated.

**Review by kolyshkin — APPROVED** [review]
LGTM, thanks.

We should backport this to 1.1

**Comment by kolyshkin** [comment]
@opencontainers/runc-maintainers PTAL

**Review by thaJeztah — APPROVED** [review]
oh! thought I already reviewed this one, but I guess we only discussed it and I forgot.


LGTM, thanks!
