### PR TITLE
nsenter: implement a two-stage join for setns

### LINKED ISSUE #4390: 'runc exec' errors with 'failed to setns into net namespace: Operation not permitted'
### Description

At [modal.com](https://modal.com/) we run a custom multi-tenant container runtime which can use `runc` or `runsc` (gVisor). For us `runsc exec` is working but we're hitting a failure on doing `runc exec` which I've debugged for a long time and can't root cause.

Doing `runc exec ta-01J5P4BZS64CE57EXK048QMNE1 bash` fails because of `EPERM` on attempting to enter the `runc` container's network namespace.

Using `sudo strace -ft runc exec -cap CAP_SYS_ADMIN ta-01J5P4BZS64CE57EXK048QMNE1 bash` I can see that specifically it's failing on the `setns` syscall like this:

```bash
[pid 1021859] 20:17:39 setns(11, CLONE_NEWNET) = -1 EPERM (Operation not permitted
```

Oddly running `sudo nsenter --all --target=267854 ls` from the same terminal works. If I `strace` that command I can see that it makes the same syscalls as `runc exec` albeit in a different order. 

```
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/user", O_RDONLY) = 3
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/cgroup", O_RDONLY) = 4
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/ipc", O_RDONLY) = 5
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/uts", O_RDONLY) = 6
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/net", O_RDONLY) = 7
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/pid", O_RDONLY) = 8
17:30:23 openat(AT_FDCWD, "/proc/267854/ns/mnt", O_RDONLY) = 9
17:30:23 setgroups(0, NULL)             = 0
17:30:23 setns(4, CLONE_NEWCGROUP)      = 0
17:30:23 close(4)                       = 0
17:30:23 setns(5, CLONE_NEWIPC)         = 0
17:30:23 close(5)                       = 0
17:30:23 setns(6, CLONE_NEWUTS)         = 0
17:30:23 close(6)                       = 0
17:30:23 setns(7, CLONE_NEWNET)         = 0
17:30:23 close(7)                       = 0
17:30:23 setns(8, CLONE_NEWPID)         = 0
17:30:23 close(8)                       = 0
17:30:23 setns(9, CLONE_NEWNS)          = 0
17:30:23 close(9)                       = 0
17:30:23 setns(3, CLONE_NEWUSER)        = 0
17:30:23 close(3)                       = 0
```

**Things I've looked into:**

* Capabilities — I'm running with `sudo` so this shouldn't be a problem
* Namespace hierarchy — looks correct
* Seccomp — doesn't appear active
* SELinux — is disabled
* AppArmor — is disabled

---

I'm stuck on figuring out what's wrong here. My next move was going to be compiling my own `runc` to add debugging code into `nsexec.c`. 

### Steps to reproduce the issue

I fear this is tricky to reproduce, but I will provide details on what we're doing:

1. From our container runtime running as root: `runc --system-cgroup run ta-123 --bundle $BUNDLE_PATH` 
    a. `config.json` given below
3. From a terminal on the same host: `sudo runc --debug exec -c CAP_SYS_ADMIN ta-01J6NQG0GEHAQ07FTVHC4GAS64 ls`

The container's network namespace is created from our container runtime with `ip netns add ta-123` prior to container creation, and inside a `CreateRuntime` hook we use the CNI Bridge and Loopback plugins to setup `lo` and `eth0`. 

<details>
<summary>config.json</summary>

```json
{
  "annotations": {
    "org.systemd.property.IPAccounting": "true"
  },
  "hooks": {
    "createRuntime": [
      {
        "args": ["$OMITTED$"],
        "path": "/usr/bin/python3"
      }
    ],
    "postStop": [
      {
        "args": ["$OMITTED$"],
        "path": "/usr/bin/python3"
      }
    ]
  },
  "hostname": "modal",
  "linux": {
    "cgroupsPath": "modal.slice:container:ta-01J6NG5R94KSZSJAHD2XXMYXMS",
    "gidMappings": [
      {
        "containerID": 0,
        "hostID": 0,
        "size": 1
      },
      {
        "containerID": 1,
        "hostID": 100000,
        "size": 16777216
      }
    ],
    "maskedPaths": [
      "/proc/acpi",
      "/proc/asound",
      "/proc/kcore",
      "/proc/keys",
      "/proc/latency_stats",
      "/proc/timer_list",
      "/proc/timer_stats",
      "/proc/sched_debug",
      "/sys/devices/virtual",
      "/sys/firmware",
      "/proc/scsi"
    ],
    "namespaces": [
      {
        "type": "pid"
      },
      {
        "type": "ipc"
      },
      {
        "type": "uts"
      },
      {
        "type": "mount"
      },
      {
        "type": "user"
      },
      {
        "type": "cgroup"
      },
      {
        "path": "/run/netns/ta-01J6NG5R94KSZSJAHD2XXMYXMS",
        "type": "network"
      }
    ],
    "readonlyPaths": [
      "/proc/bus",
      "/proc/fs",
      "/proc/irq",
      "/proc/sys",
      "/proc/sysrq-trigger"
    ],
    "resources": {
      "cpu": {
        "period": 100000,
        "quota": 412500,
        "shares": 128
      },
      "memory": {
        "reservation": 134217728
      }
    },
    "sysctl": {},
    "uidMappings": [
      {
        "containerID": 0,
        "hostID": 0,
        "size": 1
      },
      {
        "containerID": 1,
        "hostID": 100000,
        "size": 16777216
      }
    ]
  },
  "mounts": [
    {
      "destination": "/proc",
      "source": "proc",
      "type": "proc"
    },
    {
      "destination": "/dev",
      "options": [
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ],
      "source": "tmpfs",
      "type": "tmpfs"
    },
    {
      "destination": "/dev/pts",
      "options": [
        "nosuid",
        "noexec",
        "newinstance",
        "ptmxmode=0666",
        "mode=0620"
      ],
      "source": "devpts",
      "type": "devpts"
    },
    {
      "destination": "/dev/shm",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "mode=1777",
        "size=65536k"
      ],
      "source": "shm",
      "type": "tmpfs"
    },
    {
      "destination": "/dev/mqueue",
      "options": [
        "nosuid",
        "noexec",
        "nodev"
      ],
      "source": "mqueue",
      "type": "mqueue"
    },
    {
      "destination": "/sys",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "ro",
        "rbind"
      ],
      "source": "/sys",
      "type": "bind"
    },
    {
      "destination": "/sys/fs/cgroup",
      "options": [
        "nosuid",
        "noexec",
        "nodev",
        "relatime",
        "ro"
      ],
      "source": "cgroup",
      "type": "cgroup"
    },
    {
      "destination": "/etc/resolv.conf",
      "options": [
        "ro",
        "rbind",
        "rprivate",
        "nosuid",
        "noexec",
        "nodev"
      ],
      "source": "/opt/container-etc-resolv.conf",
      "type": "bind"
    },
    {
      "destination": "/run/modal.sock",
      "options": [
        "nosuid",
        "nodev",
        "noexec",
        "bind",
        "private"
      ],
      "source": "/run/modal-ta-01J6NG5R94KSZSJAHD2XXMYXMS-388233379.sock",
      "type": "bind"
    }
  ],
  "ociVersion": "1.0.2-dev",
  "process": {
    "args": [
      "/bin/dumb-init",
      "--",
      "python",
      "-u",
      "-R",
      "--check-hash-based-pycs",
      "never",
      "-m",
      "modal._container_entrypoint",
     "Ch10YS0wMUo2Tkc1Ujk0S1NaU0pBSEQyWFhNWVhNUxIZZnUtMGRmNTA1WFU4ZnFrZkp5a2RCQUV3bCIZYXAtd1JBaXM5UlhJWnpFcDhrRXhFT2lMeDqPAQoCZjESAWYaGW1vLVFBUnBqRDNvbDJhWFd1V0pyYUxBclIaGW1vLWNNQkhGWUJLTHZyemowN1lXeWM5NjQiGWltLWN1eWltWlBhSXR3SjFQamowTFB5OTc4AkACSgIiAKgBkE7yAQRydW5j2gIbChlpbS1jdXlpbVpQYUl0d0oxUGpqMExQeTk3wgMA+AMBagRtYWlu"
    ],
    "capabilities": {
      "ambient": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
      ],
      "bounding": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
      ],
      "effective": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
      ],
      "inheritable": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
      ],
      "permitted": [
        "CAP_AUDIT_WRITE",
        "CAP_CHOWN",
        "CAP_DAC_OVERRIDE",
        "CAP_FOWNER",
        "CAP_FSETID",
        "CAP_KILL",
        "CAP_MKNOD",
        "CAP_NET_BIND_SERVICE",
        "CAP_NET_RAW",
        "CAP_SETFCAP",
        "CAP_SETGID",
        "CAP_SETPCAP",
        "CAP_SETUID",
        "CAP_SYS_CHROOT"
      ]
    },
    "cwd": "/root",
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "TERM=xterm",
      "SSL_CERT_DIR=/etc/ssl/certs",
      "SOURCE_DATE_EPOCH=1641013200",
      "PIP_NO_CACHE_DIR=off",
      "PYTHONHASHSEED=0",
      "PIP_ROOT_USER_ACTION=ignore",
      "CFLAGS=-g0",
      "PIP_DEFAULT_TIMEOUT=30",
      "BLIS_NUM_THREADS=1",
      "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
      "LANG=C.UTF-8",
      "MKL_NUM_THREADS=1",
      "OMP_NUM_THREADS=1",
      "OPENBLAS_NUM_THREADS=1",
      "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "PYTHONPATH=/pkg/:/root/",
    ],
    "noNewPrivileges": true,
    "rlimits": [
      {
        "hard": 65536,
        "soft": 65536,
        "type": "RLIMIT_NOFILE"
      }
    ],
    "terminal": false,
    "user": {
      "gid": 0,
      "uid": 0
    }
  },
  "root": {
    "path": "/tmp/task-data-cTR0Dv/ta-01J6NG5R94KSZSJAHD2XXMYXMS/.tmpZue7Vk/rootfs",
    "readonly": false
  }
}
```

</details>

### Describe the results you received and expected

I expect that `runc exec` will succeed, but it fails on entering the network namespace. **Full failure:**

```bash
sudo runc --debug exec -c CAP_SYS_ADMIN ta-01J6NQG0GEHAQ07FTVHC4GAS64 ip
DEBU[0000] nsexec[1889889]: => nsexec container setup
DEBU[0000] nsexec[1889889]: set process as non-dumpable
DEBU[0000] nsexec-0[1889889]: ~> nsexec stage-0
DEBU[0000] nsexec-0[1889889]: spawn stage-1
DEBU[0000] nsexec-0[1889889]: -> stage-1 synchronisation loop
DEBU[0000] nsexec-1[1889891]: ~> nsexec stage-1
DEBU[0000] nsexec-1[1889891]: setns(0x10000000) into user namespace (with path /proc/1813667/ns/user)
DEBU[0000] nsexec-1[1889891]: setns(0x8000000) into ipc namespace (with path /proc/1813667/ns/ipc)
DEBU[0000] nsexec-1[1889891]: setns(0x4000000) into uts namespace (with path /proc/1813667/ns/uts)
DEBU[0000] nsexec-1[1889891]: setns(0x40000000) into net namespace (with path /proc/1813667/ns/net)
FATA[0000] nsexec-1[1889891]: failed to setns into net namespace: Operation not permitted
FATA[0000] nsexec-0[1889889]: failed to sync with stage-1: next state: Invalid argument
```

### What version of runc are you using?

```
runc --version
runc version 1.7.19
commit: v1.1.13-0-g58aa920
spec: 1.0.2-dev
go: go1.21.12
libseccomp: 2.5.1
```

**and**

```
./runc.amd64 --version
runc version 1.1.13
commit: v1.1.13-0-g58aa9203-dirty
spec: 1.0.2-dev
go: go1.21.11
libseccomp: 2.5.5
```

### Host OS information

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

But also reproduced on Oracle Linux as well. 

### Host kernel information

`Linux ip-10-1-1-198 5.15.0-1068-aws #74~20.04.1-Ubuntu SMP Tue Aug 6 19:32:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by cyphar**
If we are running with privileges and are asked to join an externally
created user namespaces as well as some other namespace that was *not*
created underneath said user namespace, the approach we added in commit
https://github.com/opencontainers/runc/commit/2cd9c31b995cff313c828dafbfeea082c7318c3f ("nsenter: guarantee correct user namespace ordering")
doesn't work.

While in theory you would want all externally created namespaces to be
sane, it seems that some tools really do create unrelated namespaces and
ask us to join them. Luckily we can just loosely copy what nsenter(1)
appears to do -- we first try to join any namespaces we can (with host
root privileges), then we join any user namespaces, and then we join any
remaining namespaces (now with the user namespace's privileges).

Note that we *do not* have to try to join namespaces after we create our
own user namespace. Namespace permissions are based purely on the owning
user namespace (not the rootuid) so we will not have access to any extra
namespaces once we unshare(CLONE_NEWUSER) (in fact we will not be able
to setns(2) to anything!).

Fixes #4390
Closes #4491

Fixes: https://github.com/opencontainers/runc/commit/2cd9c31b995cff313c828dafbfeea082c7318c3f ("nsenter: guarantee correct user namespace ordering")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Huh, these diffs from `cmft` are _really_ weird:

```diff
diff --git a/libcontainer/nsenter/nsexec.c b/libcontainer/nsenter/nsexec.c
index 4da0665c..b0787c61 100644
--- a/libcontainer/nsenter/nsexec.c
+++ b/libcontainer/nsenter/nsexec.c
@@ -432,21 +432,21 @@ static struct nstype_t {
 	int type;
 	char *name;
 } all_ns_types[] = {
-	{ .type = CLONE_NEWCGROUP, .name = "cgroup" },
-	{ .type = CLONE_NEWIPC, .name = "ipc" },
-	{ .type = CLONE_NEWNS, .name = "mnt" },
-	{ .type = CLONE_NEWNET, .name = "net" },
-	{ .type = CLONE_NEWPID, .name = "pid" },
-	{ .type = CLONE_NEWTIME, .name = "time" },
-	{ .type = CLONE_NEWUSER, .name = "user" },
-	{ .type = CLONE_NEWUTS, .name = "uts" },
-	{}, /* null terminator */
+	{.type = CLONE_NEWCGROUP,.name = "cgroup"},
+	{.type = CLONE_NEWIPC,.name = "ipc"},
+	{.type = CLONE_NEWNS,.name = "mnt"},
+	{.type = CLONE_NEWNET,.name = "net"},
+	{.type = CLONE_NEWPID,.name = "pid"},
+	{.type = CLONE_NEWTIME,.name = "time"},
+	{.type = CLONE_NEWUSER,.name = "user"},
+	{.type = CLONE_NEWUTS,.name = "uts"},
+	{},			/* null terminator */
 };
 
 /* Returns the clone(2) flag for a namespace, given the name of a namespace. */
 static int nstype(char *name)
 {
-	for (struct nstype_t *ns = all_ns_types; ns->name != NULL; ns++)
+	for (struct nstype_t * ns = all_ns_types; ns->name != NULL; ns++)
 		if (!strcmp(name, ns->name))
 			return ns->type;
 	/*
@@ -567,18 +565,17 @@ static char *strappend(char *dst, char *src)
 static char *nsset_to_str(nsset_t nsset)
 {
 	char *str = NULL;
-	for (struct nstype_t *ns = all_ns_types; ns->name != NULL; ns++) {
+	for (struct nstype_t * ns = all_ns_types; ns->name != NULL; ns++) {
 		if (ns->type & nsset) {
 			if (str)
 				str = strappend(str, ", ");
 			str = strappend(str, ns->name);
 		}
 	}
-	return str ?: strdup("");
+	return str ? : strdup("");
 }
```

**Comment by cyphar** [comment]
Seems like AlmaLinux's `nsenter` auto-sets the mappings if you don't define them. Very weird.

File: libcontainer/nsenter/nsexec.c [hunk 1]
```diff
@@ -488,38 +496,142 @@ void join_namespaces(char *nslist)
...
+	 *
+	 * This is necessary for containers that are configured to join some
+	 * externally-created namespace but are also configured to create their
+	 * own user namespace (or join an unrelated user namespace).
+	 *
+	 * This is similar to what nsenter(1) seems to do in practice.
+	 */
+	joined |= __join_namespaces(to_join & ~(joined | CLONE_NEWUSER), ns_list, ns_len);
+	joined |= __join_namespaces(CLONE_NEWUSER, ns_list, ns_len);
+	joined |= __join_namespaces(to_join & ~(joined | CLONE_NEWUSER), ns_list, ns_len);
```
Comment (lifubang) [inline libcontainer/nsenter/nsexec.c:631]: In practice, is there any namespaces will be joined failed before we join user namespace, but will join successfully after user ns joined?

Comment (cyphar) [reply libcontainer/nsenter/nsexec.c:631]: If we are rootless and there are userns-owned namespaces, we need to be in the userns in order to have the necessary permissions to do `setns`. This is what 2cd9c31b995cff313c828dafbfeea082c7318c3f fixed.

(This is also what `nsenter(1)` does afaics.)

File: libcontainer/nsenter/nsexec.c [hunk 2]
```diff
@@ -488,38 +496,148 @@ void join_namespaces(char *nslist)
...
+
+	for (size_t i = 0; i < ns_len; i++) {
+		struct namespace_t *ns = &ns_list[i];
+		int type = nstype(ns->type);
+		int err, saved_errno;
 
-		write_log(DEBUG, "setns(%#x) into %s namespace (with path %s)", flag, ns->type, ns->path);
-		if (setns(ns->fd, flag) < 0)
+		if (!(type & allow)) {
+			write_log(DEBUG, "skipping setns(%#x) into %s namespace (with path %s)",
```
Comment (lifubang) [inline libcontainer/nsenter/nsexec.c:523]: Maybe we should check is this type ns has been joined before, or else it will make user confused for this log.

File: libcontainer/nsenter/nsexec.c [hunk 3]
```diff
@@ -488,38 +496,148 @@ void join_namespaces(char *nslist)
...
+	 * containers -- we don't get setns(2) permissions until we join the userns
+	 * and get CAP_SYS_ADMIN).
+	 *
+	 * Splitting the joins this way is necessary for containers that are
+	 * configured to join some externally-created namespace but are also
+	 * configured to join an unrelated user namespace.
+	 *
+	 * This is similar to what nsenter(1) seems to do in practice.
+	 */
+	joined |= __join_namespaces(to_join & ~(joined | CLONE_NEWUSER), ns_list, ns_len);
```
Comment (lifubang) [inline libcontainer/nsenter/nsexec.c:635]: Maybe for rootless container, all `to_join` ns paths will be joined fail? So it will introduce some unnecessary syscalls for rootless container? From this aspect, please look #4491 to check whether it will be more simple to fix the related issue in go code or not?

File: libcontainer/nsenter/nsexec.c [hunk 4]
```diff
@@ -488,38 +496,148 @@ void join_namespaces(char *nslist)
...
+	/* Double-check that we used up (and thus joined) all of the nsfds. */
+	for (size_t i = 0; i < ns_len; i++) {
+		struct namespace_t *ns = &ns_list[i];
+		int type = nstype(ns->type);
+
+		if (ns->fd < 0)
+			continue;
+
+		failed_to_join |= type;
+		write_log(FATAL, "failed to setns(%#x) into %s namespace (with path %s): %s",
```
[the remark this answers is not in the document]
Comment (kolyshkin) [reply libcontainer/nsenter/nsexec.c:595]: @lifubang it gives more information than just the list of namespaces we failed to join.

File: libcontainer/nsenter/nsexec.c [hunk 5]
```diff
@@ -524,9 +549,95 @@ void join_namespaces(char *nslist)
...
+			  type, ns->type, ns->path, strerror(EPERM));
+		close(ns->fd);
+		ns->fd = -1;
 	}
 
-	free(namespaces);
+	/* Make sure we joined the namespaces we planned to. */
+	if (failed_to_join)
+		bail("failed to join {%s} namespaces: %s", nsset_to_str(failed_to_join), strerror(EPERM));
```
Comment (kolyshkin) [inline libcontainer/nsenter/nsexec.c:603]: nit: `bail` appends `: %m` to the message printed so maybe instead of `: %s", ... strerror(EPERM)` you can just assign `errno = EPERM` before calling it.

Otherwise we'll end up with something like `... namespaces: Operation not permitted: Success` which is somewhat confusing.

**Review by kolyshkin — APPROVED** [review]
A single nit; LGTM otherwise.

File: libcontainer/nsenter/nsexec.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:595]: Make sense, it will provide more information about `path`.

File: libcontainer/nsenter/nsexec.c (hunk 2 above)
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:523]: Too many logs about skipping setns.
```bash
@lifubang ➜ ~/bb $ sudo /workspaces/runc/runc --debug exec -d test sleep inf
DEBU[0000]libcontainer/dmz/cloned_binary_linux.go:202 libcontainer/dmz.IsCloned() F_GET_SEALS on /proc/self/exe failed: invalid argument 
DEBU[0000]libcontainer/dmz/cloned_binary_linux.go:227 libcontainer/dmz.CloneSelfExe() runc-dmz: using overlayfs for sealed /proc/self/exe 
DEBU[0000]libcontainer/container_linux.go:506 libcontainer.(*Container).newParentProcess() runc-dmz: using /proc/self/exe clone         
DEBU[0000] nsexec[8341]: => nsexec container setup      
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec[8341]: set process as non-dumpable    
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: ~> nsexec stage-0            
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: spawn stage-1                
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: -> stage-1 synchronisation loop 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: ~> nsexec stage-1            
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x8000000) into ipc namespace (with path /proc/8162/ns/ipc): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x4000000) into uts namespace (with path /proc/8162/ns/uts): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x40000000) into net namespace (with path /proc/8162/ns/net): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x20000000) into pid namespace (with path /proc/8162/ns/pid): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x20000) into mnt namespace (with path /proc/8162/ns/mnt): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: setns(0x2000000) into cgroup namespace (with path /proc/8162/ns/cgroup): Success 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x8000000) into ipc namespace (with path /proc/8162/ns/ipc) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x4000000) into uts namespace (with path /proc/8162/ns/uts) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x40000000) into net namespace (with path /proc/8162/ns/net) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x20000000) into pid namespace (with path /proc/8162/ns/pid) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x20000) into mnt namespace (with path /proc/8162/ns/mnt) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x2000000) into cgroup namespace (with path /proc/8162/ns/cgroup) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x8000000) into ipc namespace (with path /proc/8162/ns/ipc) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x4000000) into uts namespace (with path /proc/8162/ns/uts) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x40000000) into net namespace (with path /proc/8162/ns/net) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x20000000) into pid namespace (with path /proc/8162/ns/pid) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x20000) into mnt namespace (with path /proc/8162/ns/mnt) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: skipping setns(0x2000000) into cgroup namespace (with path /proc/8162/ns/cgroup) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: unshare remaining namespaces 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: spawn stage-2                
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: request stage-0 to forward stage-2 pid (8343) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: stage-1 requested pid to be forwarded 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: forward stage-1 (8342) and stage-2 (8343) pids to runc 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: signal completion to stage-0 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: stage-1 complete             
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: <- stage-1 synchronisation loop 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: -> stage-2 synchronisation loop 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[8341]: signalling stage-2 to run    
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[8342]: <~ nsexec stage-1            
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-2[6]: ~> nsexec stage-2               
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-2[6]: signal completion to stage-0    
DEBU[0000] nsexec-0[8341]: stage-2 complete             
DEBU[0000] nsexec-0[8341]: <- stage-2 synchronisation loop 
DEBU[0000] nsexec-0[8341]: <~ nsexec stage-0            
DEBU[0000] nsexec-2[6]: <= nsexec container setup       
DEBU[0000] nsexec-2[6]: booting up go runtime ...       
DEBU[0000] child process in init()                      
DEBU[0000] reading sync                                 
DEBU[0000] read sync type:procReady                     
DEBU[0000] writing sync type:procRun                    
DEBU[0000] reading sync                                 
DEBU[0000] sync pipe closed                             
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() writing sync type:procReady                  
DEBU[0000] reading sync                                 
DEBU[0000] read sync type:procRun                       
DEBU[0000] setns_init: about to exec
```

File: libcontainer/nsenter/nsexec.c (hunk 5 above)
Comment (lifubang) [reply libcontainer/nsenter/nsexec.c:603]: It looks like:
```
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[11318]: skipping setns(0x10000000) into user namespace (with path /proc/1/ns/user) 
DEBU[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[11318]: setns(0x10000000) into user namespace (with path /proc/1/ns/user): Invalid argument 
FATA[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-1[11318]: failed to setns into user namespace: Invalid argument 
FATA[0000]libcontainer/logs/logs.go:55 libcontainer/logs.processEntry() nsexec-0[11317]: failed to sync with stage-1: next state: Success 
ERRO[0000]utils.go:62 main.fatalWithCode() runc run failed: unable to start container process: can't get final child's PID from pipe: EOF
```

File: libcontainer/nsenter/nsexec.c (hunk 2 above)
Comment (cyphar) [reply libcontainer/nsenter/nsexec.c:523]: We can probably skip the "skipping" messages, but we should keep the error and success lines. These are all debug logs, so there is basically no overhead to having them without debug logging enabled (we don't forward them in `log.c` if the log level isn't debug).

**Comment by lifubang** [comment]
Do you want this PR in 1.2.2? Because it's really a bug.

**Comment by kolyshkin** [comment]
> Do you want this PR in 1.2.2? Because it's really a bug.

This is a bug but not a regression, and the change is somewhat radical. For release-1.2 branch we should focus on regressions and security fixes, while keeping it stable. So, to my mind, let's keep it for 1.3 and not backport to 1.2.x.

We also have a goal to release 1.3.0 in a timely manner (say in about 5 months from now, not a few years like it happened with runc 1.2.0).

**Comment by kolyshkin** [comment]
@lifubang @AkihiroSuda @rata PTAL

**Review by lifubang — APPROVED** [review]
