### PR TITLE
libcontainer: dmz: fix "go get" builds

### LINKED ISSUE #4096: libcontainer cannot be build due to runc-dmz (as a Go library for third party projects) : `dmz_linux.go:21:12: pattern runc-dmz: no matching files found`
### Description

With the latest `main`, projects using libcontainer cannot build unless they set `-tags runc_nodmz` flag.

### Steps to reproduce the issue

1. pull latest `go get github.com/opencontainers/runc@main`
2. build

### Describe the results you received and expected

Result:
`../../../../../pkg/mod/github.com/opencontainers/runc@v1.1.1-0.20231025141802-edd00eb3cbd2/libcontainer/dmz/dmz_linux.go:21:12: pattern runc-dmz: no matching files found`

This can work when adding `runc_nodmz` to build flags but is it expected that all libcontainer consumers do this?

### What version of runc are you using?

`github.com/opencontainers/runc v1.1.1-0.20231025141802-edd00eb3cbd2`

### Host OS information

_No response_

### Host kernel information

_No response_

### PR DESCRIPTION
**Pull request by cyphar**
Because runc-dmz is not checked into Git, go get will end up creating a copy of libcontainer/dmz with no runc-dmz binary, which causes external libcontainer users to have compilation errors.

Unfortunately, we cannot get go:embed to just ignore that there are no files matching the provided pattern, so instead we need to create a dummy file that matches the go:embed (which we check into Git and so go get _will_ copy) and switch to embed.FS.

This is a little bit uglier, but at least it will fix external libcontainer users.

Fixes #4096
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

File: libcontainer/dmz/dmz_linux.go [hunk 1]
```diff
@@ -6,21 +6,32 @@ package dmz
...
+// /proc/self/exe.
 //
-//go:generate sh -c "make -B runc-dmz || echo -n >runc-dmz"
-//go:embed runc-dmz
+// There is an empty file called runc-dmz-dummy-file.txt in libcontainer/dmz in
+// order to work around the restriction that go:embed requires at least one
+// file to match the pattern.
+//
+//go:generate sh -c "make -B runc-dmz"
+//go:embed runc-dmz*
```
Comment (AkihiroSuda) [inline libcontainer/dmz/dmz_linux.go:25]: Can we just embed a directory for simplicity?
https://pkg.go.dev/embed#FS.ReadDir

Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:25]: We could, but we still need a dummy file. If you have an empty directory, you just get:

```
libcontainer/dmz/dmz_linux.go:24:12: pattern binary: cannot embed directory binary: contains no embeddable files
```

Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:25]: Also `ReadDir` and doing logic based on it is more complicated than using `ReadFile` (if the file is not embedded we get `nil, someError` -- and we can safely ignore the error).

Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:25]: This is how it looks with a directory. I guess it is a little nicer in some aspects, but it's basically the same thing:

```diff
diff --git a/libcontainer/dmz/Makefile b/libcontainer/dmz/Makefile
index 3c30db243d91..959529c5fd91 100644
--- a/libcontainer/dmz/Makefile
+++ b/libcontainer/dmz/Makefile
@@ -14,6 +14,6 @@ else
 	CFLAGS += -DRUNC_USE_STDLIB
 endif
 
-runc-dmz: _dmz.c
+binary/runc-dmz: _dmz.c
 	$(CC) $(CFLAGS) -static -o $@ $^
 	$(STRIP) -gs $@
diff --git a/libcontainer/dmz/.gitignore b/libcontainer/dmz/binary/.gitignore
similarity index 100%
rename from libcontainer/dmz/.gitignore
rename to libcontainer/dmz/binary/.gitignore
diff --git a/libcontainer/dmz/binary/dummy-file.txt b/libcontainer/dmz/binary/dummy-file.txt
new file mode 100644
index 000000000000..e69de29bb2d1
diff --git a/libcontainer/dmz/binary/runc-dmz b/libcontainer/dmz/binary/runc-dmz
new file mode 100755
index 000000000000..18eda9255e75
Binary files /dev/null and b/libcontainer/dmz/binary/runc-dmz differ
diff --git a/libcontainer/dmz/dmz_linux.go b/libcontainer/dmz/dmz_linux.go
index 12f9709a269a..f2b0e8daed7d 100644
--- a/libcontainer/dmz/dmz_linux.go
+++ b/libcontainer/dmz/dmz_linux.go
@@ -6,21 +6,32 @@ package dmz
 import (
 	"bytes"
 	"debug/elf"
-	_ "embed"
+	"embed"
 	"os"
 
 	"github.com/sirupsen/logrus"
 )
 
-// Try to build the runc-dmz binary. If it fails, replace it with an empty file
-// (this will trigger us to fall back to a clone of /proc/self/exe). Yeah, this
-// is a bit ugly but it makes sure that weird cross-compilation setups don't
-// break because of runc-dmz.
+// Try to build the runc-dmz binary on "go generate". If it fails (or
+// libcontainer is being imported as a library), the embed.FS will not contain
+// the file, which will then cause us to fall back to a clone of
+// /proc/self/exe.
 //
-//go:generate sh -c "make -B runc-dmz || echo -n >runc-dmz"
-//go:embed runc-dmz
+// There is an empty file called runc-dmz-dummy-file.txt in libcontainer/dmz in
+// order to work around the restriction that go:embed requires at least one
+// file to match the pattern.
+//
+//go:generate sh -c "make -B binary/runc-dmz"
+//go:embed binary
+var runcDmzFs embed.FS
+
+// The contents of runc-dmz.
 var runcDmzBinary []byte
 
+func init() {
+	runcDmzBinary, _ = runcDmzFs.ReadFile("binary/runc-dmz")
+}
+
 // Binary returns a cloned copy (see CloneBinary) of a very minimal C program
 // that just does an execve() of its arguments. This is used in the final
 // execution step of the container execution as an intermediate process before
```

**Review by AkihiroSuda — APPROVED** [review]

**Comment by mythi** [comment]
FWIW, I tested this with my cAdvisor PR using

```
replace github.com/opencontainers/runc => github.com/cyphar/runc v1.0.0-rc4.0.20231030083055-39322bc53518
```

and without `-tags runc_nodmz`. Both `make test` and `make build` in cAdvisor built OK.

File: libcontainer/dmz/dmz_linux.go [hunk 2]
```diff
@@ -6,21 +6,32 @@ package dmz
...
+var runcDmzFs embed.FS
+
+// The contents of runc-dmz.
 var runcDmzBinary []byte
 
+func init() {
+	runcDmzBinary, _ = runcDmzFs.ReadFile("runc-dmz")
```
Comment (kolyshkin) [inline libcontainer/dmz/dmz_linux.go:32]: I'm thinking, since we only need dmz binary for runc start/run/exec, maybe instead of adding `init()` it is better to integrate this code into the `Binary` function below?

We may even get rid of using `bytes.NewBuffer` since it might be sufficient to do `runDmzFs.Open` and return the resulting file.

**Review by kolyshkin — CHANGES_REQUESTED** [review]
https://github.com/opencontainers/runc/pull/4101#discussion_r1376870750

File: libcontainer/dmz/dmz_linux.go (hunk 2 above)
Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:32]: Because we need to check the ELF prefix, having a single slice that is re-used for every container start is IMHO preferable to using the `fs.File` abstraction (where `Read` can return errors even though in practice it will never error).

I can switch to `sync.Once` if you like.

**Review by kolyshkin — APPROVED** [review]
LGTM

I've also checked if it makes sense to get rid of `debug/elf` dependency in order to reduce runc binary size, as we only use a single constant from it.

Apparently not, probably because `github.com/cilium/ebpf` also uses it.

File: libcontainer/dmz/dmz_linux.go [hunk 3]
```diff
@@ -6,20 +6,32 @@ package dmz
...
+// libcontainer is being imported as a library), the embed.FS will not contain
+// the file, which will then cause us to fall back to a clone of
+// /proc/self/exe.
 //
-//go:generate sh -c "make -B runc-dmz || echo -n >runc-dmz"
-//go:embed runc-dmz
-var runcDmzBinary []byte
+// There is an empty file called runc-dmz-dummy-file.txt in libcontainer/dmz in
+// order to work around the restriction that go:embed requires at least one
+// file to match the pattern.
```
Comment (kolyshkin) [inline libcontainer/dmz/dmz_linux.go:23]: A nit. AFAIK we don't need `runc-dmz-dummy-file.txt` in `libcontainer/dmz` anymore since we have `.gitignore` in there (which, by the way, is also being embedded).

Or, we need to do
```diff
-//go:embed binary
+//go:embed binary/runc-*
```
so that `.gitignore` is not included. 

Either way is fine.

**Comment by mythi** [comment]
`github.com/cyphar/runc v1.0.0-rc4.0.20231102014201-9cc74bf7e259` built/tested in my env OK here too.

File: libcontainer/dmz/dmz_linux.go (hunk 3 above)
Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:23]: Actually `.gitignore` is not embedded [because files starting with `_` and `.` are not included by `go:embed` when embedding a directory unless you use the `all:` prefix](https://pkg.go.dev/embed#hdr-Directives):

> If a pattern names a directory, all files in the subtree rooted at that directory are embedded (recursively), except that files with names beginning with ‘.’ or ‘_’ are excluded. [...] If a pattern begins with the prefix ‘all:’, then the rule for walking directories is changed to include those files beginning with ‘.’ or ‘_’. For example, ‘all:image’ embeds both ‘image/.tempfile’ and ‘image/dir/.tempfile’.

If you remove `runc-dmz` and `dummy-file.txt` as well as the `go:generate` line in `libcontainer/dmz/dmz_linux.go` (to emulate using `go get` on runc), you'll find that the build fails with the same error as before.

File: libcontainer/dmz/dmz_linux.go [hunk 4]
```diff
@@ -31,18 +43,25 @@ var runcDmzBinary []byte
...
 	if os.Getenv("RUNC_DMZ") == "legacy" {
 		logrus.Debugf("RUNC_DMZ=legacy set -- switching back to classic /proc/self/exe cloning")
 		return nil, ErrNoDmzBinary
 	}
+	runcDmzBinaryOnce.Do(func() {
+		runcDmzBinary, _ = runcDmzFs.ReadFile("binary/runc-dmz")
+		// Verify that our embedded binary has a standard ELF header.
+		if !bytes.HasPrefix(runcDmzBinary, []byte(elf.ELFMAG)) {
+			if len(runcDmzBinary) != 0 {
+				logrus.Infof("misconfigured build: embedded runc-dmz binary is non-empty but is missing a proper ELF header")
```
Comment (AkihiroSuda) [inline libcontainer/dmz/dmz_linux.go:56]: Should be an error

Comment (cyphar) [reply libcontainer/dmz/dmz_linux.go:56]: The problem is that we cannot tell if the embedded binary is broken at build-time, so making this an error would mean someone with an incredibly broken build system could result in a runc binary that fails to start any containers (when the alternative is we safely fallback to binary cloning).

I guess you could argue that at some point, we can't protect people from their own carelessness, but given that this can only be checked at runtime and falling back to `/proc/self/exe` cloning is completely safe, I feel like this is the right balance.

**Review by AkihiroSuda — APPROVED** [review]
