### PR TITLE
Fix flakiness in TestHook

### LINKED ISSUE #5245: Flaky TestHook
Seeing this for the second time:

```
=== RUN   TestHook
time="2026-04-13T17:48:47Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
.....
time="2026-04-13T17:48:47Z" level=warning msg="cannot serialize hook of type configs.FuncHook, skipping"
    exec_test.go:1090: unexpected error: exit status 1
--- FAIL: TestHook (0.11s)
```

1. https://github.com/opencontainers/runc/actions/runs/24150883471/job/70477231257?pr=5222 (from https://github.com/opencontainers/runc/pull/5222).
2. https://github.com/opencontainers/runc/actions/runs/24358098981/job/71130299998 (from https://github.com/opencontainers/runc/pull/5244).

Once I saw it I opened https://github.com/opencontainers/runc/pull/5232 to be able to find out what's going on, but it is still not merged.

### PR DESCRIPTION
**Pull request by kolyshkin**
Since commit 3cdda46 (PR #5186) the poststart hooks runs after the container
process start, and so they race.

Add a sleep to container command line to allow the poststart hook to win.

Fixes: #5245

### CODE REVIEW

File: libcontainer/integration/exec_test.go [hunk 1]
```diff
@@ -1074,9 +1075,9 @@ func TestHook(t *testing.T) {
 	container, err := newContainer(t, config)
 	ok(t, err)
 
-	// e.g: 'ls /prestart ...'
 	var cmd strings.Builder
-	cmd.WriteString("ls ")
+	// The poststart hook is racing with this command. Give it time to win.
+	cmd.WriteString("sleep 2 && ls ")
 	for _, hook := range hookFiles {
 		cmd.WriteString("/" + hook + " ")
```
Comment (lifubang) [inline libcontainer/integration/exec_test.go]: I think adding `sleep 2` can minimize the race window, but it doesn’t guarantee its complete elimination.

Yes, `poststart` is special. We could add a check like `if hook != "poststart"` here, and move the file-existence verification of "/poststart" to a point after the container has started but before it’s destroyed.

**Review by rata — COMMENTED** [review]
What is the problem exactly? I don't follow how the msg in the issue you reference `cannot serialize hook of type configs.FuncHook, skipping` is related to this. Can you please elaborate?

Also, if the post-start shouldn't run before the container itself, shouldn't we synchronize on that in runc?

File: libcontainer/integration/exec_test.go (hunk 1 above)
Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: > We could add a check like `if hook != "poststart"` here, and move the file-existence verification of "/poststart" to a point after the container has started but before it’s destroyed.

That is exactly what the initial version of this commit did. I ditched it because it adds some complexity which I didn't like at the time. Here's the diff:

```diff
diff --git a/libcontainer/integration/exec_test.go b/libcontainer/integration/exec_test.go
index cd0df282..1d43e7ea 100644
--- a/libcontainer/integration/exec_test.go
+++ b/libcontainer/integration/exec_test.go
@@ -1075,11 +1075,14 @@ func TestHook(t *testing.T) {
        container, err := newContainer(t, config)
        ok(t, err)
 
-       // e.g: 'ls /prestart ...'
        var cmd strings.Builder
        cmd.WriteString("ls ")
        for _, hook := range hookFiles {
-               cmd.WriteString("/" + hook + " ")
+               // The poststart hook is racing with this command, so
+               // we check that it worked later (see below).
+               if hook != "poststart" {
+                       cmd.WriteString("/" + hook + " ")
+               }
        }
 
        var stdout strings.Builder
@@ -1098,6 +1101,13 @@ func TestHook(t *testing.T) {
        // Wait for process
        waitProcess(&pconfig, t)
 
+       // Check that poststart hook worked.
+       f, err = os.Open(config.Rootfs + "/poststarst")
+       if err != nil {
+               t.Fatalf("poststart hook failed: %s", err)
+       }
+       f.Close()
+
        if err := container.Destroy(); err != nil {
                t.Fatalf("container destroy %s", err)
        }
```

If you prefer this, I'll update the patch.

**Comment by kolyshkin** [comment]
> What is the problem exactly?

I think I described it adequately already. Let's try again :)

1. We used to run the poststart hook right after `runc init` is run. 
2. Since the above is against the spec, we changed it in PR #5186.
3. The above change resulted in a TestHook flakiness (reported in #5245).
4. The flakiness is caused by the fact that now we run container's init process and poststart hook it parallel. In this very test, the "container's init process" is "ls -l /poststart ....", and the poststart hook is "touch /poststart". These two are racing and if "ls" wins, the test fails.


> I don't follow how the msg in the issue you reference `cannot serialize hook of type configs.FuncHook, skipping` is related to this. Can you please elaborate?

It is not related, I just copy-pasted the test output in its entirely (in fact not, I skipped over many "cannot serialize" messages). The error message is the last one (with the stderr added by PR #5232) it is more clear):

```
    exec_test.go:1098: command failed: exit status 1; stderr:
        ls: /poststart: No such file or directory
```
 
> Also, if the post-start shouldn't run before the container itself, shouldn't we synchronize on that in runc?

It should not, and it does not. Basically runc start tells `runc init` to execve the container's init process, then proceeds to run the poststart hook. So yes, these two run in parallel. Since the container's init process is usually a long-lived one, it does not make sense to wait for it.

Having said that, ideally we should ensure that the container's init is actually running (or was running), and then run the poststart hook. I remember looking for how to do just that (for issue #4437, see comments in there). In short, I was looking for a way to ensure the `runc init` has already execve'd the user process (for either start or exec) but could not find a good way. Something like looping reading the in-container `/proc/1/exe` or `/proc/1/cmdline` until it changes is probably not a good way.

If you know a good way, maybe amend #4437.

File: libcontainer/integration/exec_test.go (hunk 1 above)
Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: pushed; ptal @lifubang

**Review by lifubang — APPROVED** [review]

**Review by rata — APPROVED** [review]
@kolyshkin OHHH, now I understand. Thanks a lot for the detailed explanation!

This looks good, specially now without the sleep and the check just after it. Thanks!
