### PR TITLE
set the default value of CpuBurst to nil instead of 0

### LINKED ISSUE #4210: runc update will clear cpu burst value
1. runc update will clear cpu burst value
```
root@acmcoder:/home/acmcoder/ubuntutest# cat /sys/fs/cgroup/cpu/user.slice/test/cpu.cfs_burst_us
0
root@acmcoder:/home/acmcoder/ubuntutest#
root@acmcoder:/home/acmcoder/ubuntutest# runc update --cpu-burst=10000 test
root@acmcoder:/home/acmcoder/ubuntutest# cat /sys/fs/cgroup/cpu/user.slice/test/cpu.cfs_burst_us
10000
root@acmcoder:/home/acmcoder/ubuntutest# runc update --memory=100M test
root@acmcoder:/home/acmcoder/ubuntutest# cat /sys/fs/cgroup/cpu/user.slice/test/cpu.cfs_burst_us
0
```

2. Error for container update for the kernel not support cpu burst
When I'm testing #4188 in ubuntu 20.04 with cgroupv2, I got some errors:
```
✗ update cgroup v1/v2 common limits
   (in test file tests/integration/update.bats, line 74)
     `[ "$status" -eq 0 ]' failed
   runc spec (status=0):

   runc run -d --console-socket /tmp/bats-run-JaQGX1/runc.L3uZyo/tty/sock test_update (status=0):

   cat: /sys/fs/cgroup/runc-cgroups-integration-test/test-cgroup-16459/memory.swap.max: No such file or directory
   current 33554432 !? 33554432
   current 25165824 !? 25165824
   current 20 !? 20
   runc update test_update --cpuset-cpus 1 (status=1):
   time="2024-03-03T07:53:10+08:00" level=warning msg="Setting back cgroup configs failed due to error: open /sys/fs/cgroup/runc-cgroups-integration-test/test-cgroup-16459/cpu.max.burst: no such file or directory, your state.json and actual configs might be inconsistent."
   time="2024-03-03T07:53:10+08:00" level=error msg="open /sys/fs/cgroup/runc-cgroups-integration-test/test-cgroup-16459/cpu.max.burst: no such file or directory"
```

```
root@iZj6ccy7ct4rpjdodcohzlZ:~/ubuntu# uname -a
Linux iZj6ccy7ct4rpjdodcohzlZ 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@iZj6ccy7ct4rpjdodcohzlZ:~/ubuntu# ls /sys/fs/cgroup/user.slice/user-0.slice/
cgroup.controllers      cpu.max                cpu.weight           memory.low        rdma.max
cgroup.events           cpu.pressure           cpu.weight.nice      memory.max        session-104.scope
cgroup.freeze           cpuset.cpus            io.max               memory.min        session-106.scope
cgroup.max.depth        cpuset.cpus.effective  io.pressure          memory.oom.group  session-109.scope
cgroup.max.descendants  cpuset.cpus.partition  io.stat              memory.pressure   test
cgroup.procs            cpuset.mems            io.weight            memory.stat       test1
cgroup.stat             cpuset.mems.effective  memory.current       pids.current      user@0.service
cgroup.subtree_control  cpu.stat               memory.events        pids.events       user-runtime-dir@0.service
cgroup.threads          cpu.uclamp.max         memory.events.local  pids.max
cgroup.type             cpu.uclamp.min         memory.high          rdma.current
```

### PR DESCRIPTION
**Pull request by lifubang**
Fix #4210 

We should set the default of `CpuBurst` to nil instead of 0 when we are updating a container's resource limit.

### CODE REVIEW

File: update.go [hunk 1]
```diff
@@ -216,7 +215,6 @@ other options are ignored.
 				opt  string
 				dest *uint64
 			}{
-				{"cpu-burst", r.CPU.Burst},
 				{"cpu-period", r.CPU.Period},
 				{"cpu-rt-period", r.CPU.RealtimePeriod},
 				{"cpu-share", r.CPU.Shares},
```
Comment (AkihiroSuda) [inline update.go:220]: Shouldn't we distinguish nil from zero for all the fields?

See https://github.com/opencontainers/runc/pull/4142/commits/c9ba576e41cb39a8e82f0b5dc6155ea718703a6c

Comment (lifubang) [reply update.go:220]: Yes, I think we should deal with all this type field. Could you please provide your PR link?

Comment (AkihiroSuda) [reply update.go:220]: - https://github.com/opencontainers/runc/pull/4142

Comment (AkihiroSuda) [reply update.go:220]: ping @lifubang @kolyshkin PTAL

Comment (lifubang) [reply update.go]: cherry-picked from your PR and add a testcase.

**Comment by lifubang** [comment]
@kolyshkin How about merge this to fix the `CpuBurst` issue first?

**Comment by rata** [comment]
I can confirm containerd tests pass now with this PR: https://github.com/containerd/containerd/actions/runs/8555412932/job/23442925228?pr=9313

**Review by kolyshkin — APPROVED** [review]
This is not totally right in my view, and also a tad overcomplicated, but it fixes a real bug, and a proper solution requires changes to cgroup managers.

Thus LGTM.
