### PR TITLE
utils: mkdirall: fix handling of suid/sgid bits

### LINKED ISSUE #4401: mkdirall regression with filepath.MkdirAll
> This may causes a regression for `dind` now. @cyphar 
> ```
> @lifubang ➜ ~/ubuntu $ sudo /workspaces/runc/runc create test
> ERRO[0000] runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": possible attack detected: newly created directory "/home/codespace/ubuntu/rootfs/proc" has incorrect mode 0o42755 (expected 0o40755)
> ```
> This is from github codespace online webide, I think it looks like a `dind`, and it worked before.

_Originally posted by @lifubang in https://github.com/opencontainers/runc/pull/4393#discussion_r1758064041_

### PR DESCRIPTION
**Pull request by cyphar**
~~*Draft until filepath-securejoin v0.3.2 is released.*~~

This fixes some minor issues with suid/sgid bits introduced by #4393.

/cc @lifubang
Fixes #4401
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
@lifubang Can you verify this fixes the `dind` issue? I added a test which should be a reproducer for the problem you hit.

**Comment by lifubang** [comment]
> @lifubang Can you verify this fixes the `dind` issue? I added a test which should be a reproducer for the problem you hit.

Has verified that it has indeed fixed the dind issue. Thanks.

**Comment by cyphar** [comment]
I've released a new version of filepath-securejoin, so this should be ready now.

File: libcontainer/utils/utils_unix.go [hunk 1]
```diff
@@ -319,6 +319,14 @@ func MkdirAllInRootOpen(root, unsafePath string, mode uint32) (_ *os.File, Err e
 	if mode&^0o7777 != 0 {
 		return nil, fmt.Errorf("tried to include non-mode bits in MkdirAll mode: 0o%.3o", mode)
 	}
+	// Linux (and thus os.MkdirAll) silently ignores the suid and sgid bits if
+	// passed. While it would make sense to return an error in that case (since
+	// the user has asked for a mode that won't be applied), for compatibility
+	// reasons we have to ignore these bits.
+	if ignoredBits := mode &^ 0o1777; ignoredBits != 0 {
+		logrus.Warnf("MkdirAll called with no-op mode bits that are ignored by Linux 0o%.3o", ignoredBits)
```
Comment (rata) [inline libcontainer/utils/utils_unix.go:327]: Do we want some separator before the ignored bits? I mean, like this:
```suggestion
		logrus.Warnf("MkdirAll called with no-op mode bits that are ignored by Linux: 0o%.3o", ignoredBits)
```

File: tests/integration/mounts.bats [hunk 2]
```diff
@@ -211,6 +211,29 @@ function test_mount_order() {
...
+		source: "tmpfs",
+		destination: "/setgid/a/b/c",
+		options: ["ro", "nodev", "nosuid"]
+	}]'
+	update_config '.process.args |= ["true"]'
+
+	runc run test_busybox
+	[ "$status" -eq 0 ]
+
+	# Verify that the setgid bit is inherited.
```
Comment (rata) [inline tests/integration/mounts.bats:230]: Just curious: this works just because, even if mkdir will ignore those bits, linux will honor it when doing the mkdir, as it is inside a dir with setgid?

**Review by rata — APPROVED** [review]
LGTM, thanks!

File: tests/integration/mounts.bats (hunk 2 above)
Comment (cyphar) [reply tests/integration/mounts.bats:230]: The ignoring and inheriting behaviours are two separate issues. This test works because `S_ISGID` on a directory will cause any new directory created inside it to also have `S_ISGID` set.

Comment (rata) [reply tests/integration/mounts.bats:230]: Cool, that is exactly what I was saying :)

**Review by kolyshkin — APPROVED** [review]
LGTM
