### PR TITLE
Fix the conversion of sysctl variable dots and slashes

### LINKED ISSUE #3256: '/' is allowed as a separator in sysctl name
[Runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#sysctl) says:

> sysctl (object, OPTIONAL) allows kernel parameters to be modified at
runtime for the container. For more information, see the sysctl(8)
man page.

and linux sysctl says:

```
variable
The name of a key to read from. An example is
kernel.ostype. The '/' separator is also accepted in place of a '.'.
```
```
       Note that either "/" or "."  may be used as separators within
       sysctl variable names. If the first separator is a slash,
       remaining slashes and dots are left intact. If the first
       separator is a dot, dots and slashes are interchanged.
       "kernel.domainname=foo" and "kernel/domainname=foo" are
       equivalent and will cause "foo" to be written to
       /proc/sys/kernel/domainname. Either
       "net.ipv4.conf.enp3s0/200.forwarding" or
       "net/ipv4/conf/enp3s0.200/forwarding" may be used to refer to
       /proc/sys/net/ipv4/conf/enp3s0.200/forwarding. A glob glob(7)
       pattern may be used to write the same value to all matching keys.
       Keys for which an explicit pattern exists will be excluded from
       any glob matching. In addition, a key may be explicitly excluded
       from being set by any matching glob patterns by specifying the
       key name prefixed with a "-" character and not followed by "=",
       see SYNOPSIS.
```

https://man7.org/linux/man-pages/man8/sysctl.8.html
https://man7.org/linux/man-pages/man5/sysctl.d.5.html

However, in fact, the sysctl name in runc does not support a slash as a separator.

This PR  https://github.com/opencontainers/runc/pull/3254  wants to solve this problem, but I think the conversion method does not match the linux sysctl definition.

see https://github.com/opencontainers/runc/pull/3254/files#r739936786 for more details.

So I opened this issue to track the fix of this issue andI will open a new PR to fix this.

Related to: 
- kubernetes/kubernetes#102393
- https://github.com/opencontainers/runc/pull/3254

/assign

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Fixes #3256 

see  
- https://github.com/opencontainers/runc/pull/3254/files#r739936786 
- https://github.com/kubernetes/kubernetes/pull/102393#discussion_r661550379

Fix the sysctl conversion function according to the linux ssyctl conversion definition.
```
       Note that either "/" or "."  may be used as separators within
       sysctl variable names. If the first separator is a slash,
       remaining slashes and dots are left intact. If the first
       separator is a dot, dots and slashes are interchanged.
       "kernel.domainname=foo" and "kernel/domainname=foo" are
       equivalent and will cause "foo" to be written to
       /proc/sys/kernel/domainname. Either
       "net.ipv4.conf.enp3s0/200.forwarding" or
       "net/ipv4/conf/enp3s0.200/forwarding" may be used to refer to
       /proc/sys/net/ipv4/conf/enp3s0.200/forwarding. A glob glob(7)
       pattern may be used to write the same value to all matching keys.
       Keys for which an explicit pattern exists will be excluded from
       any glob matching. In addition, a key may be explicitly excluded
       from being set by any matching glob patterns by specifying the
       key name prefixed with a "-" character and not followed by "=",
       see SYNOPSIS.
```
see following webpages for more details:
https://man7.org/linux/man-pages/man8/sysctl.8.html
https://man7.org/linux/man-pages/man5/sysctl.d.5.html 

Related to: 
- kubernetes/kubernetes#102393
- https://github.com/opencontainers/runc/pull/3254

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
PTAL @AkihiroSuda @mrunalp

File: libcontainer/configs/validate/validator.go [hunk 1]
```diff
@@ -128,6 +128,41 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
 	return nil
 }
 
+// convertSysctlVariableToDotsSeparator can return sysctl variables in dots separator format.
+// The '/' separator is also accepted in place of a '.'.
+// Convert the sysctl variables to dots separator format for validation.
+// More info:
+//   https://man7.org/linux/man-pages/man8/sysctl.8.html
+//   https://man7.org/linux/man-pages/man5/sysctl.d.5.html
+func convertSysctlVariableToDotsSeparator(val string) string {
```
Comment (AkihiroSuda) [inline libcontainer/configs/validate/validator.go:137]: Could you add example inputs and outputs the code comment?
Also could you consider adding unit tests

Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go:137]: I can add unit tests, but this package test uses `package validate_test`.
Then this function must be exported, otherwise it cannot be referenced. I am not sure whether to export this function, after all, this method is only used in this package.

Comment (AkihiroSuda) [reply libcontainer/configs/validate/validator.go:137]: The package name should be renamed to `validate`, then you can add unit tests without exporting the function.

Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go:140]: Okay, I have renamed the test package name to `validate`.

**Review by AkihiroSuda — DISMISSED** [review]

File: libcontainer/configs/validate/validator.go [hunk 2]
```diff
@@ -128,6 +128,44 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
...
+// Input sysctl variable "net/ipv4/conf/eno2.100.rp_filter"
+// will return the converted value "net.ipv4.conf.eno2/100.rp_filter"
+func convertSysctlVariableToDotsSeparator(val string) string {
+	if val == "" {
+		return val
+	}
+	sepFunc := func(r rune) bool {
+		return r == '.' || r == '/'
+	}
+	firsSepIndex := strings.IndexFunc(val, sepFunc)
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator.go:147]: Why not use `strings.IndexAny`?

File: libcontainer/configs/validate/validator.go [hunk 3]
```diff
@@ -128,6 +128,44 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
...
+		} else {
+			f := func(r rune) rune {
+				switch r {
+				case '.':
+					return '/'
+				case '/':
+					return '.'
+				default:
+					return r
+				}
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator.go:160]:
```suggestion
				return r
```

File: libcontainer/configs/validate/validator.go [hunk 4]
```diff
@@ -128,6 +128,44 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
...
+			}
+			convertedSysctlVal := strings.Map(f, val)
+			return convertedSysctlVal
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator.go:163]:
```suggestion
			return strings.Map(f, val)
```

File: libcontainer/configs/validate/validator.go [hunk 5]
```diff
@@ -128,6 +128,44 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
...
+// will return the converted value "net.ipv4.conf.eno2/100.rp_filter"
+func convertSysctlVariableToDotsSeparator(val string) string {
+	if val == "" {
+		return val
+	}
+	sepFunc := func(r rune) bool {
+		return r == '.' || r == '/'
+	}
+	firsSepIndex := strings.IndexFunc(val, sepFunc)
+	if firsSepIndex != -1 {
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator.go:148]: This can be rewritten to simplify things a bit. Less indentation, avoiding else block etc.

For example:

```go
if firstSepIndex == -1 || val[idx] == '.' {
	return val
}
// Replace . with / and vice versa.
f := func(r rune) rune {
.....
return strings.Map(f, val)
```

File: libcontainer/configs/validate/validator.go (hunk 2 above)
Comment (kolyshkin) [reply libcontainer/configs/validate/validator.go:147]: There's also a typo: `firs` -> `first`

File: libcontainer/configs/validate/validator_test.go [hunk 6]
```diff
@@ -178,21 +177,47 @@ func TestValidateUsernamespaceWithoutUserNS(t *testing.T) {
...
 	err := validator.Validate(config)
 	if err == nil {
 		t.Error("Expected error to occur but it was nil")
 	}
 }
 
+// TestConvertSysctlVariableToDotsSeparator tests whether the sysctl variable
+// can be correctly converted to a dot as a separator.
+func TestConvertSysctlVariableToDotsSeparator(t *testing.T) {
+	type Test struct {
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator_test.go:190]: `s/Test/testCase/g`
or something

File: libcontainer/configs/validate/validator_test.go [hunk 7]
```diff
@@ -178,21 +177,47 @@ func TestValidateUsernamespaceWithoutUserNS(t *testing.T) {
...
+		sysctl string
+		except string
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator_test.go:192]: you probably mean "expect" here.

You can also use "in" and "out" (as the test input and output).

**Review by kolyshkin — CHANGES_REQUESTED** [review]
Left some nits.

Can you please separate out the `package validate_test -> package validate` change to a separate (first) commit?

File: libcontainer/configs/validate/validator.go (hunk 2 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go]: Yes, this function `strings.IndexAny` is more convenient, I have modified it.

`firs` -> `first`： I didn’t pay attention, it has been modified.

File: libcontainer/configs/validate/validator.go (hunk 4 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go]: Updated.

File: libcontainer/configs/validate/validator.go (hunk 5 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go]: Thanks for advice. Updated.

File: libcontainer/configs/validate/validator_test.go (hunk 6 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator_test.go]: Updated `Test` -> `testCase`.

File: libcontainer/configs/validate/validator_test.go (hunk 7 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator_test.go]: It might be better to understand this way. Updated.

File: libcontainer/configs/validate/validator.go (hunk 3 above)
Comment (mengjiao-liu) [reply libcontainer/configs/validate/validator.go]: default:
					return r

You mean to delete these two lines?
But I think it’s not necessary to delete it, and it’s okay to write it in the switch segment.

File: libcontainer/configs/validate/validator.go [hunk 8]
```diff
@@ -128,6 +128,37 @@ func (v *ConfigValidator) cgroupnamespace(config *configs.Config) error {
...
+
+	f := func(r rune) rune {
+		switch r {
+		case '.':
+			return '/'
+		case '/':
+			return '.'
+		default:
+			return r
+		}
```
Comment (kolyshkin) [inline libcontainer/configs/validate/validator.go:157]:
```suggestion
		return r
```

(i.e. remove the `default` case)

**Comment by kolyshkin** [comment]
LGTM except for a single nit, thank you @mengjiao-liu!

Also, this needs to be rebased due to #3261

**Comment by kolyshkin** [comment]
Ah, and the signed-off-by needs to be added to the commits (see https://github.com/opencontainers/runc/pull/3257/checks?check_run_id=4100751081)

**Comment by mengjiao-liu** [comment]
Rebased and signed-off-by. Thanks for reminding!

**Review by AkihiroSuda — APPROVED** [review]

**Review by kolyshkin — APPROVED** [review]
LGTM, thank you!
