### PR TITLE
Fix setupDev logic in rootfs_linux.go

### LINKED ISSUE #80: Sharing /dev/ with the container breaks /dev/ptmx on the host
When a container is launched with a bind mount between /dev (on the host) and /dev (in the container), all subsequent attempts to open /dev/ptmx fail.

`setupPtmx()` in `libcontainer/rootfs_linux.go` will unconditionally remove `/dev/ptmx` and then symlink it to `/dev/pts/ptmx` , which is a character file that is untouchable by unprivileged users. This prevents unprivileged programs which rely on `getpt` from running on the host (such as X terminals, screen, and tmux).

I discovered this via docker, but it happens in any libcontainer app if /dev/ is shared with the container before `setupPtmx`. Is there a reason for libcontainer to touch /dev (at all) if it's mounted directly from the host? I have tested this on Fedora 22 and 21, SELinux is set to permissive, as well as Arch Linux without SELinux.

I can reproduce this consistently.

`uname -a`: `Linux wtemple.localdomain 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`config.json`:
```
{
    "version": "0.1.1",
    "platform": {
        "os": "linux",
        "arch": "amd64"
    },
    "process": {
        "terminal": true,
        "user": "root",
        "args": [
            "/bin/sh"
        ],
        "env": [
            "PATH=/bin,/sbin"
        ],
        "cwd": ""
    },
    "root": {
        "path": "rootfs",
        "readonly": true
    },
    "hostname": "shell",
    "mounts": [
        {
            "type": "proc",
            "source": "proc",
            "destination": "/proc",
            "options": ""
        },
        {
            "type": "sysfs",
            "source": "sysfs",
            "destination": "/sys",
            "options": "nosuid,noexec,nodev"
        },
        {
            "type": "bind",
            "source": "/dev",
            "destination": "/dev",
            "options": "bind"
        }
    ],
    "linux": {
        "namespaces": [
            {
                "type": "process"
            },
            {
                "type": "network"
            },
            {
                "type": "mount"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            }
        ],
        "capabilities": [
            "AUDIT_WRITE",
            "KILL",
            "NET_BIND_SERVICE"
        ],
        "devices": [
            "null"
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by LK4D4**
setupDev was introduced in #96, but broken since #536 because spec 0.3.0 introduced default devices.

Fix #80 again
Fix docker/docker#21808

This is carry of #732, so Closes #732 
ping @mrunalp @cpuguy83 @crosbymichael

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by cpuguy83** [comment]
```
libcontainer/rootfs_linux_test.go:53: assignment count mismatch: 2 = 1
libcontainer/rootfs_linux_test.go:72: assignment count mismatch: 2 = 1
libcontainer/rootfs_linux_test.go:91: assignment count mismatch: 2 = 1
libcontainer/rootfs_linux_test.go:110: assignment count mismatch: 2 = 1
```

File: libcontainer/rootfs_linux_test.go [hunk 1]
```diff
@@ -35,3 +39,79 @@ func TestCheckMountRoot(t *testing.T) {
...
+	config := &configs.Config{
+		Mounts: []*configs.Mount{
+			{
+				Device:      "bind",
+				Source:      "/dev",
+				Destination: "/dev",
+			},
+		},
+	}
+	setupDev, err := needsSetupDev(config)
```
Comment (mrunalp) [inline libcontainer/rootfs_linux_test.go]: No err returned from the function.

**Comment by LK4D4** [comment]
@cpuguy83 @mrunalp fixed, sorry for that

**Comment by cpuguy83** [comment]
IANTM but LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM
