### PR TITLE
Fixing valid-id in regex

### LINKED ISSUE #635: Valid IDs
Why are IDs restricted by this pattern?

```
idRegex = regexp.MustCompile(`^[\w_-]+$`)
```

https://github.com/opencontainers/runc/blob/master/libcontainer/factory_linux.go#L29

### PR DESCRIPTION
**Pull request by rajasec**
Fixes #635
Also removed _ ,as _ is part of \w
Signed-off-by: rajasec <rajasec79@gmail.com>

### CODE REVIEW

File: libcontainer/factory_linux.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ const (
 )
 
 var (
-	idRegex  = regexp.MustCompile(`^[\w_-]+$`)
+	idRegex  = regexp.MustCompile(`^[\w-\.]+$`)
```
Comment (cyphar) [inline libcontainer/factory_linux.go]: FWIW, I'm fairly sure most regex implementations consider `[.]` to mean the literal `.` character (not "any" character, since `[.]` would be meaningless otherwise).

**Comment by rajasec** [comment]
But without this change, "." is not accepted as valid ID by runc.  So I've added part of idregex so that dot is also accepted.

**Comment by cyphar** [comment]
Sorry, what I was saying is that you can write it as `[\w-.]` and it should still work. It's just a nit. :P

**Comment by rajasec** [comment]
@cyphar 
Agree. what you mention will work.  Since it gave panic for [\w_-.], so I've added the back tick before the dot operator to be safe.
Let me know whether you are ok with the current change.

**Comment by rajasec** [comment]
@crosbymichael @mrunalp @hqhq 
Let me know your comments.

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by ip1981** [comment]
Honestly, this restriction should not exist. My deployment tools allow some odd ids, my filesystem allows odd file names, and then comes an intermediate layer (runc) telling they cannot be together. Just let it crash, it's out of scope. At least add a comment about why you think this restriction is needed. So nobody will ask again.

**Comment by wking** [comment]
On Fri, Mar 18, 2016 at 10:51:59AM -0700, Igor Pashev wrote:
> Honestly, this restriction should not exist.

Related discussion in [1,2].  Since this seems like a spec issue
that's more generic than runC, maybe move the discussion into the
mailing list thread [1]?

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/P9gZBYhiqDE
     Subject: [PATCH] runtime: Document container ID charset and uniqueness domain
     Date: Thu, 3 Sep 2015 15:07:33 -0700
     Message-ID: <c08ed73c894899e5ff6c312ecd22de7b4b296e79.1441317770.git.wking@tremily.us>
[2]: https://github.com/opencontainers/specs/pull/270#discussion_r47824814
     Subject: Update cgroupsPath to cgroupName and clarify the
       semantics around that.
