### PR TITLE
libct: Signal: honor RootlessCgroups

### LINKED ISSUE #4394: [v1.2 regression] [cgroup v1 + rootless] `nerdctl run -d --name=bar --pid=container:foo ; nerdctl rm -f bar` hangs
```bash
nerdctl run -d --name=foo busybox sleep infinity
nerdctl run -d --name=bar --pid=container:foo busybox sleep infinity
nerdctl rm -f bar
# runc v1.1.14 works, but v1.2.0-rc.3 hangs here.
# However, `nerdctl stop bar && nerdctl rm bar` still works.
```

The issue is reproducible with:
- Ubuntu 20.04 (cgroup v1) + rootless

Not reproducible with:
- Ubuntu 20.04 (cgroup v1) + rootful
- Ubuntu 20.04 (rebooted in cgroup v2) + rootless
- Ubuntu 20.04 (rebooted in cgroup v2) + rootful
- Ubuntu 24.04 (cgroup v2) + rootless
- Ubuntu 24.04 (cgroup v2) + rootful

containerd version (v1.7.16, v2.0.0-rc.4) and nerdctl version (v1.7.6, v2.0.0-rc.1) do not seem to matter.

I haven't figured out how to reproduce the issue with a plain nerd-less bats.

- - -
Regression in https://github.com/opencontainers/runc/commit/9583b3d1c297021109081872c52302316ede15b1 `libct: move killing logic to container.Signal` :
- #3825

### PR DESCRIPTION
**Pull request by AkihiroSuda**
`signalAllProcesses()` depends on the cgroup and is expected to fail when runc is running in rootless without an access to the cgroup.

When `RootlessCgroups` is set to `true`, runc just ignores the error from `signalAllProcesses` and may leak some processes running. (See the comments in this PR)
In the future, runc should walk the process tree to avoid such a leak.

Note that `RootlessCgroups` is a misnomer; it is set to `false` despite the name when cgroup v2 delegation is configured.
This is expected to be renamed in a separate commit.

Fix #4394

### CODE REVIEW

File: libcontainer/container_linux.go [hunk 1]
```diff
@@ -388,11 +388,18 @@ func (c *Container) Signal(s os.Signal) error {
 	// leftover processes. Handle this special case here.
 	if s == unix.SIGKILL && !c.config.Namespaces.IsPrivate(configs.NEWPID) {
 		if err := signalAllProcesses(c.cgroupManager, unix.SIGKILL); err != nil {
+			if c.config.RootlessCgroups { // may not have an access to cgroup
```
Comment (AkihiroSuda) [inline libcontainer/container_linux.go:391]: "RootlessCgroups" is misnomer, as this is set to false on modern rootless environments (cgroup v2 + systemd).

Should be renamed to something else in a separate PR.

File: libcontainer/container_linux.go [hunk 2]
```diff
@@ -388,11 +388,18 @@ func (c *Container) Signal(s os.Signal) error {
...
+				return c.signal(s)
```
[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply libcontainer/container_linux.go:392]: > signalAllProcesses has a cgroupv1-friendly fallback

No when lacking an access to the cgroup.
It just returns `ErrNotRunning` immediately :
https://github.com/opencontainers/runc/blob/961b8031f6614be300d3b10eec9d2f54323026d9/libcontainer/init_linux.go#L696-L701

[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply libcontainer/container_linux.go:392]: And it seems correct that `m.Exists()` returns false from the perspective of `m`, as the cgroup actually does not exist in this case

[the remark this answers is not in the document]
Comment (cyphar) [reply libcontainer/container_linux.go:392]: Right, but the function name implies that it's cgroup-specific and the fallback isn't technically cgroup-specific (though it does use the cgroup for freezing). Idk...

Comment (lifubang) [inline libcontainer/container_linux.go:392]: Another question, for a container with shared pid namespace, just only kill the init process can cause all other processes in this container killed? If not, these non-init processes will be leaked after we delete the container. Maybe these non-init processes are managed by downstream tools(containerd or rootlesskit)?

File: tests/integration/kill.bats [hunk 3]
```diff
@@ -133,3 +133,27 @@ test_host_pidns_kill() {
...
+
+	runc run -d --console-socket "$CONSOLE_SOCKET" target_ctr
+	[ "$status" -eq 0 ]
+	testcontainer target_ctr running
+	target_pid="$(__runc state target_ctr | jq .pid)"
+	update_config '.linux.namespaces |= map(if .type == "user" or .type == "pid" then (.path = "/proc/'"$target_pid"'/ns/" + .type) else . end) | del(.linux.uidMappings) | del(.linux.gidMappings)'
+
+	runc run -d --console-socket "$CONSOLE_SOCKET" attached_ctr
+	[ "$status" -eq 0 ]
+	testcontainer attached_ctr running
```
Comment (lifubang) [inline tests/integration/kill.bats:149]: Could you please exec another process to this container? For example:
```
runc exec -d attached_ctr sleep infinity
```

But I think it's hard to simulate the situation that runc can't access the cgroup path.

Comment (lifubang) [reply tests/integration/kill.bats:149]: And should detect whether the second process has been killed or not after we kill the container.

**Comment by lifubang** [comment]
> `signalAllProcesses()` depends on the cgroup and is expected to fail when runc is running in rootless without an access to the cgroup.

Maybe `runc kill -a container_id KILL` can't kill this type container either in version `v1.1.*`?

File: tests/integration/kill.bats (hunk 3 above)
Comment (AkihiroSuda) [reply tests/integration/kill.bats:149]: The second process is just leaked when cgroup is not delegated, as in v1.1.

The scope of the PR is limited to just fix the regression #4394.

It is still quite hard to handle the leaked processes in a robust way, and it should be discussed in a separate issue.
(Probably we should walk the procfs tree to track descendants of the container init process)

**Comment by AkihiroSuda** [comment]
> > `signalAllProcesses()` depends on the cgroup and is expected to fail when runc is running in rootless without an access to the cgroup.
> 
> Maybe `runc kill -a container_id KILL` can't kill this type container either in version `v1.1.*`?

Seems so.

File: libcontainer/state_linux.go [hunk 4]
```diff
@@ -44,6 +44,7 @@ func destroy(c *Container) error {
 	// and destroy is supposed to remove all the container resources, we need
 	// to kill those processes here.
 	if !c.config.Namespaces.IsPrivate(configs.NEWPID) {
+		// Likely to fail when c.config.RootlessCgroups is true
 		_ = signalAllProcesses(c.cgroupManager, unix.SIGKILL)
 	}
 	if err := c.cgroupManager.Destroy(); err != nil {
```
Comment (lifubang) [inline libcontainer/state_linux.go:50]: Another question, if runc has no access to the cgroup path, this cgroup destroy call will throw the error either.

Comment (AkihiroSuda) [reply libcontainer/state_linux.go:50]: `Destroy` seems to ignore `ENOENT`

File: libcontainer/container_linux.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (kolyshkin) [reply libcontainer/container_linux.go:392]: signalAllProcesses is only called when shared pid ns is used (as otherwise it's enough to kill pid 1), and to know all the PIDs we need a dedicated cgroup. Meaning, that rootless container with shared pidns won't work, as there is no way to find all PIDs (well, theoretically, we can find all the children of container init in this case, but I  am not sure it's a good idea).

Not sure how it works in runc 1.1 -- most probably it just doesn't (i.e. we leak processes).

File: tests/integration/kill.bats (hunk 3 above)
Comment (kolyshkin) [reply tests/integration/kill.bats:149]: The container init might be already gone (see https://github.com/opencontainers/runc/pull/4102).

**Review by kolyshkin — CHANGES_REQUESTED** [review]
Related: 
 - #4040
 - #4047
 - #4102

I think this is adequate given the circumstances, but the commit message and the code needs to be amended to explain that in this case we leak processes (maybe add a warning, too).

I will open a separate PR to warn about such configuration.

**Comment by AkihiroSuda** [comment]
> I think this is adequate given the circumstances, but the commit message and the code needs to be amended to explain that in this case we leak processes (maybe add a warning, too).


Done. Added a warning too.

**Review by rata — APPROVED** [review]
LGTM, thanks!

@kolyshkin thanks for all the related issues/PRs, it really helps to review this :)

**Review by kolyshkin — APPROVED** [review]
LGTM

File: libcontainer/container_linux.go [hunk 5]
```diff
@@ -388,11 +388,21 @@ func (c *Container) Signal(s os.Signal) error {
 	// leftover processes. Handle this special case here.
 	if s == unix.SIGKILL && !c.config.Namespaces.IsPrivate(configs.NEWPID) {
 		if err := signalAllProcesses(c.cgroupManager, unix.SIGKILL); err != nil {
+			if c.config.RootlessCgroups { // may not have an access to cgroup
+				logrus.WithError(err).Warn("failed to kill all processes, possibly due to lack of cgroup (Hint: enable cgroup v2 delegation)")
```
[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply libcontainer/container_linux.go:392]: For other types of errors it still makes sense to print the err?

[the remark this answers is not in the document]
Comment (lifubang) [reply libcontainer/container_linux.go:392]: #4410
