### PR TITLE
Set rlimits using prlimit in parent

### LINKED ISSUE #680: Raising rlimits higher than current hard limit fails in unprivileged containers
This may or may not be 'working-as-intended', but it seems worth discussing (and possibly specifying). 

As stands, creating a container that sets rlimits always works if the container is privileged, but fails if the container is unprivileged *unless* the current rlimits in the host are already as high or higher than the requested rlimit. This makes sense: the container root user does not have permissions to raise the rlimits higher than the current hard limit.

But the creator of the container (i.e. real root) _does_ have those permissions, and _did_ request it (via config.json). Imo we should move the rlimit setting earlier (before the creation of the user namespace) so that it succeeds for both cases, or use `prlimit` to set the limits as host root after spawning the process. I'd be happy to PR that change if people agree it's the correct behaviour? (or alternatively I'll PR the specs to note that an unprivileged container cannot request an rlimit higher than the current limit)

### PR DESCRIPTION
**Pull request by julz**
Fixes #680

This changes setupRlimit to use the Prlimit syscall (rather than
Setrlimit) and moves the call to the parent process. This is necessary
because Setrlimit would affect the libcontainer consumer if called in
the parent, and would fail if called from the child if the
child process is in a user namespace and the requested rlimit is higher
than that in the parent.

Signed-off-by: Julian Friedman <julz.friedman@uk.ibm.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

nice one!

File: libcontainer/system/linux.go [hunk 1]
```diff
@@ -53,6 +53,14 @@ func Execv(cmd string, args []string, env []string) error {
 	return syscall.Exec(name, args, env)
 }
 
+func Prlimit(pid, resource int, limit syscall.Rlimit) error {
+	_, _, err := syscall.RawSyscall6(syscall.SYS_PRLIMIT64, uintptr(pid), uintptr(resource), uintptr(unsafe.Pointer(&limit)), uintptr(unsafe.Pointer(&limit)), 0, 0)
```
Comment (mrunalp) [inline libcontainer/system/linux.go]: Is there a version that works for both 32/64 bit?

Comment (marcosnils) [inline libcontainer/system/linux.go]: @mrunalp seems like golang 386 package uses the same call also for 386 architectures (https://golang.org/src/syscall/zsyscall_linux_386.go?h=prlimit#L766)

Comment (mrunalp) [inline libcontainer/system/linux.go]: Thanks!

**Comment by mrunalp** [comment]
LGTM
