### PR TITLE
libct/int: TestFdLeaks: deflake

### LINKED ISSUE #5010: TestFdLeaksSystemd failure with criu-dev
TestFdLeaksSystemd starts failing frequently when running with criu-dev.

```
=== RUN   TestFdLeaksSystemd
    exec_test.go:1750: extra fd 9 -> /12224/task/13831/fd
    exec_test.go:1753: found 1 extra fds after container.Run
--- FAIL: TestFdLeaksSystemd (0.10s)
```

### PR DESCRIPTION
**Pull request by kolyshkin**
Since the recent CVE fixes, TestFdLeaksSystemd sometimes fails:

	=== RUN   TestFdLeaksSystemd
	    exec_test.go:1750: extra fd 9 -> /12224/task/13831/fd
	    exec_test.go:1753: found 1 extra fds after container.Run
	--- FAIL: TestFdLeaksSystemd (0.10s)

It might have been caused by the change to the test code in commit ff6fe13 ("utils: use safe procfs for /proc/self/fd loop code") -- we are now opening a file descriptor during the logic to get a list of file descriptors. If the file descriptor happens to be allocated to a different number, you'll get an error.

Let's try to filter out the fd used to read a directory.

May fix #5010

### CODE REVIEW

File: libcontainer/integration/exec_test.go [hunk 1]
```diff
@@ -1694,6 +1695,11 @@ func fdList(t *testing.T) []string {
 	fds, err := fdDir.Readdirnames(-1)
 	ok(t, err)
 
+	// Remove the fdDir fd.
+	extraFd := strconv.Itoa(int(fdDir.Fd()))
+	idx := slices.Index(fds, extraFd)
+	fds = slices.Delete(fds, idx, idx+1)
```
Comment (cyphar) [inline libcontainer/integration/exec_test.go]: I feel like `slices.DeleteFunc` is easier to read but it doesn't really matter.

Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: fixed
