### PR TITLE
fix(libcontainer): preserve rootfs slave propagation for rslave containers

### LINKED ISSUE #5192: rootfs mount propagation cannot be restored to rslave after being made private in prepareRootfs
### Description

While testing mount propagation with runc, I noticed that rootfs propagation behaves incorrectly when the intended propagation is rslave.

During container setup, prepareRootfs() first changes the rootfs mount propagation to MS_PRIVATE | MS_REC, and after pivot_root, it attempts to restore the user-specified propagation.

Relevant code:
https://github.com/opencontainers/runc/blob/main/libcontainer/rootfs_linux.go#L1052

This works correctly when the intended propagation is rshared, but does not work for rslave.

### Steps to reproduce the issue

1. create a container with rootfsPropagation=rslave
1.1 nerdctl run -d --mount type=bind,src=/mnt,dst=/app,bind-propagation=rslave --entrypoint sleep <image> 600
1.2 verify container spec is rootfsPropagation=rslave
Image
2.  exec into container check if rootfs mount propagation is rslave
Image
3. we expect to see the mount propagation is rslave which is rprivate

### Describe the results you received and expected

we expect to see the mount propagation is rslave, which should be same if mount propagation is rshared

Image

### What version of runc are you using?

affect version from 1.3.1 to 1.5.1-rc

### Host OS information

_No response_

### Host kernel information

_No response_

### PR DESCRIPTION
**Pull request by xujihui1985**
When rootfsPropagation is set to rslave, prepareRoot() was forcing the rootfs parent mount to MS_PRIVATE before bind-mounting and pivoting into the rootfs. That breaks the slave relationship needed for HostToContainer propagation, so later unmount/remount events on host mountpoints under the rootfs are not reflected inside the running container.

Fix this by keeping the rootfs parent mount as MS_SLAVE for slave-like rootfs propagation settings, while leaving the final root propagation remount in place.

Fixes: #5192

### CODE REVIEW

**Comment by xujihui1985** [comment]
@lifubang Please take look at this PR that fix issue #5192

**Comment by lifubang** [comment]
Thanks, I'll take a look next week. One small request: please use `git rebase main` instead of `git merge main`.

File: libcontainer/rootfs_linux.go [hunk 1]
```diff
@@ -231,7 +231,7 @@ func prepareRootfs(pipe *syncSocket, iConfig *initConfig) (err error) {
 	// to the current root ("/"), and not to the old rootfs before it becomes "/". Applying the
 	// flag in prepareRoot would affect the host mount namespace if the container's
 	// root mount is shared.
-	// MS_PRIVATE is skipped as rootfsParentMountPrivate() is already called.
+	// MS_PRIVATE is skipped as rootfsParentMountPropagation() is already called.
```
Comment (lifubang) [inline libcontainer/rootfs_linux.go]: After your patch, I think `MS_SLAVE` can also be skipped here to save a mount syscall!

File: libcontainer/rootfs_linux_test.go [hunk 2]
```diff
@@ -208,3 +208,56 @@ func TestNeedsSetupDevStrangeSourceDest(t *testing.T) {
 		t.Fatal("expected needsSetupDev to be true, got false")
 	}
 }
+
+func TestRootfsParentMountPropagationFlags(t *testing.T) {
```
Comment (lifubang) [inline libcontainer/rootfs_linux_test.go]: Nice, thanks for the detailed test cases.

File: libcontainer/integration/exec_test.go [hunk 3]
```diff
@@ -1230,6 +1230,172 @@ func TestRootfsPropagationSlaveMount(t *testing.T) {
...
+		_ = container.Run(pconfig)
+		_ = stdinR.Close()
+		defer stdinW.Close()
+
+		_ = stdinW.Close()
+		_, _ = pconfig.Wait()
+		return strings.TrimSpace(stdout.String()), strings.TrimSpace(stderr.String())
+	}
+
+	parseMountinfo := func(mountinfo string) (rootIsSlave, mountExists bool) {
```
Comment (lifubang) [inline libcontainer/integration/exec_test.go]: Maybe you can use `mountinfo.GetMounts` in `github.com/moby/sys/mountinfo`.

File: libcontainer/integration/exec_test.go [hunk 4]
```diff
@@ -1230,6 +1230,172 @@ func TestRootfsPropagationSlaveMount(t *testing.T) {
 	}
 }
 
+// Launch a container with rootfsPropagation in rslave mode and mount a host
+// path directly under the host rootfs tree at /mnt1cont. This verifies that
+// the container root mount remains slave after setup, and that unmounting and
+// remounting that host mountpoint itself is reflected at the same path inside
+// the running container.
+func TestRootfsPropagationSlaveRootfs(t *testing.T) {
```
Comment (lifubang) [inline libcontainer/integration/exec_test.go]: This is a nice integration test. It would be better if you could move it to `tests/integration/mounts_propagation.bats`, but you would need to write some `Bats` scripts for it. Either approach works for me, so I'll leave the decision to you.

**Review by lifubang — COMMENTED** [review]
Thanks!
The patch looks correct, though I've left a few comments. Also, could you move the integration test to a separate commit? It would make it easier for maintainers to review the changes step-by-step.

File: libcontainer/integration/exec_test.go (hunk 3 above)
Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: Thanks for the suggestion. I looked into mountinfo.GetMounts from github.com/moby/sys/mountinfo, but I do not think it fits this case well, since it reads mount information from procfs. In this test, we need to parse mountinfo from the container output returned via stdout, so I would suggest keeping the current implementation for now.

That said, it might be worth extracting a test helper for reading mountinfo, as there are several places in exec_test that do this.

File: libcontainer/integration/exec_test.go (hunk 4 above)
Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: sure, instead of move the test into mounts_propagation.bats, I add a new test under mounts_propagation.bats that test the rootfs mount propagation

Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: I have separated the PR into three commits: one for the code changes, one for the exec_test integration tests, and one for the BATS tests.

File: libcontainer/integration/exec_test.go (hunk 3 above)
Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: @xujihui1985 you need to use [mountinfo.GetMountsFromReader](https://pkg.go.dev/github.com/moby/sys/mountinfo#GetMountsFromReader).

Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: ... maybe with `ParentsFilter(dirCont)` to simplify the code (so you'll need to see if it returns 2 entries and then check the rootfs propagation).

Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: or use a custom filter

File: libcontainer/integration/exec_test.go (hunk 4 above)
Comment (kolyshkin) [reply libcontainer/integration/exec_test.go]: Maybe just leave the bats test and drop the Go one, as bats one is way simpler?

Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: ok, I'm investigating the failure in the bats tests, the reason for the failure is because some of the test pollute the environment that make the rootfs from host private, I'm trying to find out why

Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: The problem is in host-mntns.bats. In this test, the container is created in the same mount namespace as the host. During prepareRootfs, the container rootfs propagation is recursively changed to private up to /. This ends up changing the host rootfs propagation to private as well, which breaks the slave mount test. It also exposes a dangerous side effect of running a container in the host mount namespace: the container setup can unintentionally alter the host’s mount propagation settings.

Comment (lifubang) [reply libcontainer/integration/exec_test.go]: Great catch -- this is a pre-existing issue with running containers in the host mount namespace. Would you be interested in opening a PR to fix it?

Comment (xujihui1985) [reply libcontainer/integration/exec_test.go]: ok, let me try after this PR finished, by now I would reset host mount to shared in host-mntns.bats when test tear down, so that it will not break other tests

Comment (lifubang) [reply libcontainer/integration/exec_test.go]: > Maybe just leave the bats test and drop the Go one

BTW, I agree with kir's suggestion. The Go integration test is a bit overkill -- it tests kernel's slave propagation behavior, which isn't really runc's responsibility. The BATS test is the right scope: it just verifies that the `rootfsPropagation` option is correctly applied.

File: tests/integration/mounts_propagation.bats [hunk 5]
```diff
@@ -20,3 +20,16 @@ function teardown() {
 	[ "$status" -eq 0 ]
 	[ "$output" = "shared" ]
 }
+
+@test "runc run [rootfsPropagation slave]" {
+    # make sure the rootfs mount is slave before running the test
+    mount --make-rshared /
```
Comment (kolyshkin) [inline tests/integration/mounts_propagation.bats]: This probably needs `requires root` for the test case.

Yet better, skip the test entirely if root is not rshared.

Comment (kolyshkin) [reply tests/integration/mounts_propagation.bats]: > Yet better, skip the test entirely if root is not rshared.

(if there's an environments we have that already have such kind of propatation)

Or, if you really want this test, maybe add something like BATS_UNSAFE_TEST variable and only run this test if the variable is set, then set it for CI environments.

The reason is I don't really want to change my root mount propagation when running the tests on my local development machine -- I'd much rather skip this test.

Comment (xujihui1985) [reply tests/integration/mounts_propagation.bats]: make sense

**Comment by kolyshkin** [comment]
@xujihui1985 you also need to run `make shfmt` to fix bats formatting

File: tests/integration/mounts_propagation.bats (hunk 5 above)
Comment (xujihui1985) [reply tests/integration/mounts_propagation.bats]: > This probably needs `requires root` for the test case.
> 
> Yet better, skip the test entirely if root is not rshared.

the `requires root` has already been set in setup() phrase

> > Yet better, skip the test entirely if root is not rshared.
> 
> (if there's an environments we have that already have such kind of propatation)
> 
> Or, if you really want this test, maybe add something like BATS_UNSAFE_TEST variable and only run this test if the variable is set, then set it for CI environments.
> 
> The reason is I don't really want to change my root mount propagation when running the tests on my local development machine -- I'd much rather skip this test.

I have to run `mount --make-rshared /` here because host-mntns.bats unintentionally changes the root filesystem propagation to private, which pollute the CI env and makes this test impossible to pass. We probably will not need this workaround once that issue is fixed.

@kolyshkin  For now, I am going to add a BATS_UNSAFE_TEST environment variable for CI and skip this test when it is not running in CI.

File: tests/integration/mounts_propagation.bats [hunk 6]
```diff
@@ -20,3 +20,17 @@ function teardown() {
 	[ "$status" -eq 0 ]
 	[ "$output" = "shared" ]
 }
+
+@test "runc run [rootfsPropagation slave]" {
+	[ "${BATS_UNSAFE_TEST:-}" != "yes" ] && skip "disabled when BATS_UNSAFE_TEST=yes"
+
+	# make sure the rootfs mount is slave before running the test
+	mount --make-rshared /
```
Comment (kolyshkin) [inline tests/integration/mounts_propagation.bats]: Do we want to restore the old propagation? If yes, maybe it makes sense to move this into a separate file (say `mount_propagation_unsafe.bats`), and have `setup()` and `teardown()` to change it forth and back.

File: tests/integration/mounts_propagation.bats [hunk 7]
```diff
@@ -20,3 +20,17 @@ function teardown() {
 	[ "$status" -eq 0 ]
 	[ "$output" = "shared" ]
 }
+
+@test "runc run [rootfsPropagation slave]" {
+	[ "${BATS_UNSAFE_TEST:-}" != "yes" ] && skip "disabled when BATS_UNSAFE_TEST=yes"
```
Comment (kolyshkin) [inline tests/integration/mounts_propagation.bats]: I think you meant to say "disabled unless"

File: tests/integration/mounts_propagation.bats (hunk 6 above)
Comment (xujihui1985) [reply tests/integration/mounts_propagation.bats]: yes, that's a good idea

**Comment by kolyshkin** [comment]
The test in this PR (which modifies / propagation) should benefit from the feature from #5212, so if that one is approved and merged, the test here needs to add require unsafe.

File: tests/integration/mounts_propagation_unsafe.bats [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+		mount --make-rprivate /
+		;;
+	unbindable)
+		mount --make-runbindable /
+		;;
+	*)
+		echo "unknown rootfs propagation: $ORIGINAL_ROOTFS_PROPAGATION" >&2
+		return 1
+		;;
+	esac
```
Comment (kolyshkin) [inline tests/integration/mounts_propagation_unsafe.bats]: nit
```suggestion
	mount --make-r$ORIGINAL_ROOTFS_PROPAGATION /
```

Comment (kolyshkin) [reply tests/integration/mounts_propagation_unsafe.bats]: The biggest issue is, in `make_rootfs_shared` you don't just change the root mount propagation but also all of the other mounts, and here again you change *all* mounts propagation. In case any mount propagation was different from that of root, it will be not be restored to the original one.

For example, on my laptop root mount propagation is private, but `/run/netns` is shared. After this test it will become private.

Comment (xujihui1985) [reply tests/integration/mounts_propagation_unsafe.bats]: @kolyshkin  yes, the ORIGINAL_ROOTFS_PROPAGATION is the current state of the mountpoint, MS_REC is an operation flag for mount, not a persistent mount attribute, it's not possible to know if it is recursive or not. I'm think if I should make a isolate mountns and make-rshared in there, then run runc in that mountns?

Comment (xujihui1985) [reply tests/integration/mounts_propagation_unsafe.bats]: I also found that if the RootPropagation is shared, after prepareRoot, the mount is converted to private, causing it to lose its peer-group relationship. Running mount --make-shared / later only creates a new shared group for the container root, rather than reconnecting it to the original host peer group. As a result, remounting it as shared does not restore what was lost. This breaks the intended behavior of RootPropagation. **Although shared root propagation can be risky**, this still violates the original purpose of this field. Maybe we should document it to clarify it's purpose

Comment (xujihui1985) [reply tests/integration/mounts_propagation_unsafe.bats]: @kolyshkin what do you think of the idea to test under an isolated mountns?

Comment (xujihui1985) [reply tests/integration/mounts_propagation_unsafe.bats]: > The biggest issue is, in `make_rootfs_shared` you don't just change the root mount propagation but also all of the other mounts, and here again you change _all_ mounts propagation. In case any mount propagation was different from that of root, it will be not be restored to the original one.
> 
> For example, on my laptop root mount propagation is private, but `/run/netns` is shared. After this test it will become private.

I have updated the test to execute runc under an isolated mountns, so that will not pollute the host mount propagation.

Comment (kolyshkin) [reply tests/integration/mounts_propagation_unsafe.bats]: @xujihui1985 this is nice! So, we no longer need `require unsafe`?

Comment (xujihui1985) [reply tests/integration/mounts_propagation_unsafe.bats]: yes I think so, I will remove the unsafe requirement for this test case

File: libcontainer/rootfs_linux.go [hunk 9]
```diff
@@ -1061,19 +1061,27 @@ func mknodDevice(destDir *os.File, destName string, node *devices.Device) error
...
+	if rootPropagation&unix.MS_SLAVE != 0 {
+		return unix.MS_SLAVE
+	}
+	return unix.MS_PRIVATE
+}
+
+// rootfsParentMountPropagation ensures rootfs parent mount is not shared.
 // This is needed for two reasons:
 //   - pivot_root() will fail if parent mount is shared;
 //   - when we bind mount rootfs, if its parent is not private, the new mount
```
Comment (lifubang) [inline libcontainer/rootfs_linux.go]: nit:
//   - when we bind mount rootfs, if its parent is not private, the new mount

->

//   - when we bind mount rootfs, if its parent is (r)shared, the new mount

**Review by lifubang — APPROVED** [review]
LGTM with one nit.
Thanks!

File: libcontainer/rootfs_linux_test.go (hunk 2 above)
Comment (kolyshkin) [reply libcontainer/rootfs_linux_test.go]: OTOH I don't think this test makes sense. The code which it tests is:

```go
func rootfsParentMountPropagationFlags(rootPropagation int) uintptr {
	if rootPropagation&unix.MS_SLAVE != 0 {
		return unix.MS_SLAVE
	}
	return unix.MS_PRIVATE
}
```

and I don't think this code is that complicated to deserve a test case. You can "test" it by just reading it.

More to say, if we ever want to change it for whatever reason, it's more work now (as the test cases will fail).

So I'd rather remove the unit test. @lifubang WDYT?

Comment (lifubang) [reply libcontainer/rootfs_linux_test.go]: In fact, I originally wanted to keep this unit test to ensure we wouldn’t forget MS_SLAVE during future refactoring. However, now that we have an integration test covering this behavior -- and although the logic is simple yet critical -- I think we can safely remove the unit test.
@xujihui1985

Comment (xujihui1985) [reply libcontainer/rootfs_linux_test.go]: ok, unittest for this function has been removed

**Review by kolyshkin — APPROVED** [review]
LGTM, thank you

**Comment by xujihui1985** [comment]
@kolyshkin @lifubang Thanks for reviewing the MR. This was a great learning opportunity, and I learned a lot from this process.

**Comment by kolyshkin** [comment]
@lifubang you set 1.3.6 milestone for the issue this PR fixes (#5192); does that mean you want 1.3, 1.4 and 1.5 backports? When answering this, please consider whether it can bring some other regressions.

If the answer is yes, please add appropriate labels (feel free to open the backports, too).

**Comment by lifubang** [comment]
> you set 1.3.6 milestone for the issue this PR fixes (#5192); does that mean you want 1.3, 1.4 and 1.5 backports? When answering this, please consider whether it can bring some other regressions.
> 
> If the answer is yes, please add appropriate labels (feel free to open the backports, too).

I set the 1.3.6 milestone because this bug affects all releases from 1.3.x through 1.5.x, and the impact is broader than it appears:

1. Silent semantic regression: Users configuring `rootfsPropagation: rslave` get no error -- the container starts fine, but mount propagation silently falls back to `rprivate`. This is extremely hard to debug in production.

2. K8s 1.35 uses runc 1.3.x: Per containerd's release docs, K8s 1.35 recommends containerd 2.2.x/2.1.x/1.7.x, all of which bundle runc 1.3.4/1.3.5. Without a backport, this bug persists in current and upcoming Kubernetes deployments.

3. Docker 29.4.0 uses runc 1.3.5: The latest Docker release also carries this bug. Affecting both major container ecosystems justifies the backport effort.

4. Low regression risk: The fix is minimal and conservative -- only changes behavior when `rootPropagation & MS_SLAVE != 0`. All other paths remain identical.

@xujihui1985 WDYT?

**Comment by lifubang** [comment]
Oh, looking at the actual OCI spec generated by Kubernetes/docker, there's no `linux.rootfsPropagation` field set. So this bug only affects users who directly configure `rootfsPropagation: rslave` in `runc`. Given the limited impact, let's only backport to `release-1.5`.

**Comment by xujihui1985** [comment]
> Oh, looking at the actual OCI spec generated by Kubernetes/docker, there's no `linux.rootfsPropagation` field set. So this bug only affects users who directly configure `rootfsPropagation: rslave` in `runc`. Given the limited impact, let's only backport to `release-1.5`.

image
https://github.com/containerd/containerd/blob/f006ee06cabf52ee4a32429487b93d334c009589/internal/cri/opts/spec_linux_opts.go#L173
@lifubang I didn't test on the latest kubernetes and containerd, but from our internal version, the rootfsPropagation actually set on the bundle json, I'm not sure right now if this is a internal feature, I will check it later

**Comment by lifubang** [comment]
> I'm not sure right now if this is a internal feature, I will check it later

Have you had a chance to look into it yet?

**Comment by xujihui1985** [comment]
> > I'm not sure right now if this is a internal feature, I will check it later
> 
> Have you had a chance to look into it yet?

Hi, I check the current upstream version from internal codebase, it's from 1.5.4, and it's not an internal logic, https://github.com/containerd/containerd/blob/v1.5.4/pkg/cri/opts/spec_linux.go#L180-L197

**Comment by lifubang** [comment]
Thanks, this appears to be a long-standing bug. Do you think we should backport this to `release-1.3`? Since many of us are still running runc `1.3.x` in production, it seems worth fixing.
Feel free to open the backport PRs.
