### PR TITLE
never send procError to parent process after sent procReady

### LINKED ISSUE #4171: writing sync procError: write sync: file already closed
Build runc from the main branch in a amd64 host, and use a different architecture container entrypoint to start the container without runc-dmz, we will get an error:
```
root@iZj6cdnzj9sp96xf38htrnZ:~/ubuntutest# RUNC_DMZ=legacy /root/go/src/github.com/opencontainers/runc/runc run ctest
writing sync procError: write sync: file already closed
exec /runc.arm64: exec format error
root@iZj6cdnzj9sp96xf38htrnZ:~/ubuntutest# echo $?
1
root@iZj6cdnzj9sp96xf38htrnZ:~/ubuntutest# runc run ctest
exec /runc.arm64: exec format error
root@iZj6cdnzj9sp96xf38htrnZ:~/ubuntutest# echo $?
1
```

### PR DESCRIPTION
**Pull request by lifubang**
We have moved the error msg display position in #3385, I think it's reasonable to display the container init msg in one place, but in this PR, we changed an error ignore behavior in https://github.com/opencontainers/runc/blob/main/libcontainer/init_linux.go#L112-L113 .

Yes, we should display the error before `procReady` has sent, but we should ignore after that. So I think we can add a field to indicate whether we have sent `procReady` or not in child process. It's not needed for the parent process, but we can reuse it to remove a local var `seenProcReady`.

Fix #4171

### CODE REVIEW

**Comment by rata** [comment]
@lifubang can we add an integration test for this? So the next refactor doesn't regress on this.

**Comment by lifubang** [comment]
> can we add an integration test for this? So the next refactor doesn't regress on this.

Good idea, added two tests. Thanks.

File: libcontainer/sync_unix.go [hunk 1]
```diff
@@ -14,7 +14,8 @@ import (
 // which ends up making things like json.Decoder hang forever if the packet is
 // bigger than the internal read buffer.
 type syncSocket struct {
-	f *os.File
+	f         *os.File
+	procReady bool
```
Comment (cyphar) [inline libcontainer/sync_unix.go:18]: I don't like that this is put inside `syncSocket` because:

1. `procReady` only makes sense for one of our pipes, but we have multiple.
2. With this patch, `procReady` means two different things for `runc init` and the parent runc process. Combining the logic makes it far more confusing.

I think having a `closed bool` that is only be used for `runc init` might make some sense, though I don't like that access to the bool isn't protected by a mutex (then again, I suspect we wouldn't concurrently close it so :shrug:.)

File: libcontainer/process_linux.go [hunk 2]
```diff
@@ -772,7 +771,7 @@ func (p *initProcess) start() (retErr error) {
 	if err := p.comm.syncSockParent.Shutdown(unix.SHUT_WR); err != nil && ierr == nil {
 		return err
 	}
-	if !seenProcReady && ierr == nil {
+	if !p.comm.syncSockParent.procReady && ierr == nil {
```
Comment (cyphar) [inline libcontainer/process_linux.go:774]: Replacing a simple boolean with something that modifies a struct's internal fields makes this logic seem more complicated (the only thing that reads this bool is this code -- why make it seem like other things might read it?).

**Review by cyphar — CHANGES_REQUESTED** [review]

File: libcontainer/standard_init_linux.go [hunk 3]
```diff
@@ -241,6 +241,7 @@ func (l *linuxStandardInit) Init() error {
 	// Close the pipe to signal that we have completed our init.
 	logrus.Debugf("init: closing the pipe to signal completion")
 	_ = l.pipe.Close()
+	l.pipe.procReady = true
```
Comment (cyphar) [inline libcontainer/standard_init_linux.go:244]: If change this to `l.pipe.closed`, this should be set inside `Close()` and there probably should be a helper method like `isClosed()` that is used by `startInitialization`.

File: libcontainer/sync_unix.go [hunk 4]
```diff
@@ -14,7 +15,9 @@ import (
 // which ends up making things like json.Decoder hang forever if the packet is
 // bigger than the internal read buffer.
 type syncSocket struct {
-	f *os.File
+	f      *os.File
+	closed bool
+	m      sync.Mutex
```
Comment (cyphar) [inline libcontainer/sync_unix.go:20]:
```suggestion
	closed atomic.Bool
```

This might make things a bit nicer...

File: libcontainer/sync_unix.go [hunk 5]
```diff
@@ -26,9 +29,23 @@ func (s *syncSocket) File() *os.File {
...
 
+func (s *syncSocket) IsNomalClosed() bool {
+	s.m.Lock()
+	defer s.m.Unlock()
+
+	// We need to know that whether the sync socket is normally closed or not.
+	// If the sync socket is closed by accident, we don't care about it.
+	return s.closed
+}
+
```
Comment (cyphar) [inline libcontainer/sync_unix.go:48]:
```suggestion
	// Even with errors from Close(), we have to assume the pipe was closed.
	s.closed.Store(true)
	return s.f.Close()
}

func (s *syncSocket) isClosed() bool {
	return s.closed.Load()
}

```

File: libcontainer/init_linux.go [hunk 6]
```diff
@@ -108,13 +108,15 @@ func startInitialization() (retErr error) {
 	defer func() {
 		// If this defer is ever called, this means initialization has failed.
 		// Send the error back to the parent process in the form of an initError.
-		ierr := initError{Message: retErr.Error()}
-		if err := writeSyncArg(syncPipe, procError, ierr); err != nil {
-			fmt.Fprintln(os.Stderr, err)
-			return
+		if !syncPipe.IsNomalClosed() {
```
Comment (cyphar) [inline libcontainer/init_linux.go:111]:
```suggestion
		if !syncPipe.isClosed() {
```

File: libcontainer/sync_unix.go [hunk 7]
```diff
@@ -4,6 +4,7 @@ import (
 	"fmt"
 	"io"
 	"os"
+	"sync"
```
Comment (cyphar) [inline libcontainer/sync_unix.go:7]:
```suggestion
	"sync/atomic"
```

**Review by cyphar — COMMENTED** [review]
I think atomic.Bool is nicer for this than using mutexes, but I don't have a strong opinion.

File: tests/integration/exec.bats [hunk 8]
```diff
@@ -322,3 +322,16 @@ function check_exec_debug() {
 	runc exec --cgroup second test_busybox grep -w second /proc/self/cgroup
 	[ "$status" -eq 0 ]
 }
+
```
Comment (kolyshkin) [inline tests/integration/exec.bats:325]: nit: can you add a reference to issue?

File: libcontainer/sync_unix.go (hunk 5 above)
Comment (lifubang) [reply libcontainer/sync_unix.go:48]: I think the name `isClosed` here has some confuse for users, because we don't need to detect whether the socket is really closed or not. For example, if the socket fd is wrongly closed by some other code logic. We just only care about it is closed explicitly by us or not.

Comment (cyphar) [reply libcontainer/sync_unix.go:48]: I mean, the only way we can check if it is closed is if we intentionally closed it. There is no foolproof way on Linux to check if a file descriptor was closed (and a different file descriptor didn't replace it).

Also, to me `isClosed` also sounds like "was `Close` called on this handle" in this context. But if you really want to call it something else, call it something like `isFinished`. The main reasons for including the name change in my suggestion was that I didn't see why it should be exported and `IsNormalClosed` sounds very weird to my ears.

**Review by cyphar — APPROVED** [review]
LGTM, sorry for the nitpicks

File: libcontainer/init_linux.go [hunk 9]
```diff
@@ -108,13 +108,15 @@ func startInitialization() (retErr error) {
 	defer func() {
 		// If this defer is ever called, this means initialization has failed.
 		// Send the error back to the parent process in the form of an initError.
-		ierr := initError{Message: retErr.Error()}
-		if err := writeSyncArg(syncPipe, procError, ierr); err != nil {
-			fmt.Fprintln(os.Stderr, err)
-			return
+		if !syncPipe.isClosed() {
```
Comment (kolyshkin) [inline libcontainer/init_linux.go:111]: Perhaps it's better to add
```go
if syncPipe.isClosed() {
   return
}
to the very beginning of this function.

**Review by AkihiroSuda — APPROVED** [review]
