### PR TITLE
cgroup: devices: major cleanups and minimal transition rules

### LINKED ISSUE #2204: Update command causes 'Operation not permitted'
It's first seen in a kubernetes cluster with docker as container runtime. Our users reported that in some situation their bash script failed with message `can't create /dev/null: Operation not permitted`. But `/dev/null` is default device with permission `rwm`, After digging some logs, we found that it can be reproduced in runc by following steps.

1. Run a runc container like "busybox". Suppose this container is called A
2. run `while true;do echo >/dev/null;done` in container
3. runc update --cpu-share 1024 A
4. You will see `sh: can't create /dev/null: Operation not permitted`

The problem is located at https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/devices.go#L28. By default, if runc wants to allow some devices, it'll first deny all devices then allow specific devices. It's OK when launching a new container, but if you update   the resource of a container, it'll make a change that allowed devices becomes denied first, then allowed, during this period, user app will get `xxx Operation not permitted` error message.

### PR DESCRIPTION
**Pull request by cyphar**
#2366 is mostly fixed by this, though the patch is unfortunately a little more complicated than you might've first expected (it includes an emulator for the devices controller). Unfortunately this logic is necessary in order to be able to calculate and verify the minimal transition rules for a cgroup update.

A similar issue affects the cgroupv2 devices setup, but that is a topic for another time (as the solution is drastically different).

Fixes #2204
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
@mYmNeo does this PR fix the original issue for you?

**Comment by cyphar** [comment]
According to my testing, this does fix #2204.

File: libcontainer/cgroups/fs/devices.go [hunk 1]
```diff
@@ -31,44 +31,24 @@ func (s *DevicesGroup) Set(path string, cgroup *configs.Cgroup) error {
...
-			file := "devices.deny"
-			if dev.Allow {
-				file = "devices.allow"
-			}
-			if err := fscommon.WriteFile(path, file, dev.CgroupString()); err != nil {
-				return err
-			}
-		}
-		return nil
+	// The devices list is a blacklist, so we must first deny all devices.
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/devices.go]: do you mean `whitelist` here?

File: libcontainer/cgroups/fs2/devices.go [hunk 2]
```diff
@@ -3,35 +3,27 @@
...
-		case 'w':
-			w = true
-		case 'm':
-			m = true
-		}
-	}
+func isRWM(perm string) bool {
+	r := strings.Contains(perm, "r")
+	w := strings.Contains(perm, "w")
+	m := strings.Contains(perm, "m")
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs2/devices.go:18]: Looks like the old implementation is about 3x more efficient. Not that this is a critical part :smile: but I don't see a reason to replace it.

Comment (kolyshkin) [reply libcontainer/cgroups/fs2/devices.go:18]: I would do that for readability but to my mind both the old and the new one is fine.

File: libcontainer/configs/device.go [hunk 3]
```diff
@@ -35,23 +28,153 @@ type Device struct {
...
+	var set uint
+	if strings.Contains(string(p), "r") {
+		set |= deviceRead
+	}
+	if strings.Contains(string(p), "w") {
+		set |= deviceWrite
+	}
+	if strings.Contains(string(p), "m") {
+		set |= deviceMknod
+	}
```
Comment (kolyshkin) [inline libcontainer/configs/device.go:54]: 1. Is it OK to ignore unknown characters here?

2. I would rewrite it to do
```go
for _, c := range string(p) {
  switch c {
  case 'r':
    set |= deviceRead
  case 'w':
......
....
```

Comment (kolyshkin) [reply libcontainer/configs/device.go:54]: > Is it OK to ignore unknown characters here?

oh, I see you have `IsValid()` below, nice.

**Comment by AkihiroSuda** [comment]
Can we have integration tests?

File: libcontainer/configs/device.go [hunk 4]
```diff
@@ -35,23 +28,153 @@ type Device struct {
...
+	return fmt.Sprintf("%c %s:%s %s", d.Type, major, minor, d.Permissions)
 }
 
-// deviceNumberString converts the device number to a string return result.
-func deviceNumberString(number int64) string {
-	if number == Wildcard {
-		return "*"
+func (d *DeviceRule) Mkdev() (uint64, error) {
+	if d.Major == Wildcard || d.Minor == Wildcard {
+		return 0, fmt.Errorf("cannot mkdev() device with wildcards")
```
Comment (kolyshkin) [inline libcontainer/configs/device.go:177]: nit: no need to use formatting here since there's no arguments to format, so `errors.New()` is better.

File: libcontainer/configs/device.go [hunk 5]
```diff
@@ -35,23 +28,153 @@ type Device struct {
...
+	Permissions DevicePermissions `json:"permissions"`
+
+	// Allow specifies whether this rule is allowed.
+	Allow bool `json:"allow"`
+}
+
+func (d *DeviceRule) CgroupString() string {
+	var (
+		major = fmt.Sprint(d.Major)
+		minor = fmt.Sprint(d.Minor)
```
Comment (kolyshkin) [inline libcontainer/configs/device.go:164]: nit: better use `strconf.Itoa()` which doesn't have to reflect on the argument type and is faster.

File: libcontainer/cgroups/fs/devices.go [hunk 6]
```diff
@@ -26,29 +31,74 @@ func (s *DevicesGroup) Apply(d *cgroupData) error {
...
 		}
 	}
+
+	// Final safety check -- ensure that the resulting state is what was
+	// requested. This is only really correct for white-lists, but for
+	// black-lists we can at least check that the cgroup is in the right mode.
+	//
+	// This safety-check is skipped for the unit tests because we cannot
+	// currently mock devices.list correctly.
+	if !s.testingSkipFinalCheck {
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/devices.go:91]: nit:
```go
if s.testingSkipFinalCheck {
  return nil
}
....
```

**Comment by mYmNeo** [comment]
@cyphar I've tested these patches, it works well. Thank you very much. 👍

File: libcontainer/cgroups/fs/devices.go (hunk 1 above)
Comment (cyphar) [reply libcontainer/cgroups/fs/devices.go]: Yup, will fix.

File: libcontainer/cgroups/fs2/devices.go (hunk 2 above)
Comment (cyphar) [reply libcontainer/cgroups/fs2/devices.go:18]: Yeah, I'm not actually sure why I did this tbh. :thinking:

File: libcontainer/configs/device.go (hunk 3 above)
Comment (cyphar) [reply libcontainer/configs/device.go:54]: Yeah, I'll switch this to also use the iterator setup.

File: libcontainer/configs/device.go (hunk 4 above)
Comment (cyphar) [reply libcontainer/configs/device.go:177]: Sure, though I personally don't like mixing `fmt` and `errors` in the same file.

**Comment by cyphar** [comment]
@AkihiroSuda Working on it.

File: libcontainer/cgroups/fs/devices.go (hunk 6 above)
Comment (cyphar) [reply libcontainer/cgroups/fs/devices.go:91]: I disagree, I think that an early-return like that makes it harder to read.

**Comment by cyphar** [comment]
@crosbymichael I'd like to know if you're okay with the `/dev/console` rule removal as well as some of the core refactors. Quite a bit of this code predates even my involvement in `libcontainer`.

**Comment by cyphar** [comment]
@AkihiroSuda Integration test added.

File: tests/integration/update.bats [hunk 7]
```diff
@@ -312,3 +312,42 @@ EOF
...
+	mv config.json{.tmp,}
+
+	# Set up a temporary console socket and recvtty so we can get the stdio.
+	TMP_RECVTTY_DIR="$(mktemp -d "$BATS_TMPDIR/runc-tmp-recvtty.XXXXXX")"
+	TMP_RECVTTY_PID="$TMP_RECVTTY_DIR/recvtty.pid"
+	TMP_CONSOLE_SOCKET="$TMP_RECVTTY_DIR/console.sock"
+	CONTAINER_OUTPUT="$TMP_RECVTTY_DIR/output"
+	("$RECVTTY" --no-stdin --pid-file "$TMP_RECVTTY_PID" \
+				--mode single "$TMP_CONSOLE_SOCKET" &>"$CONTAINER_OUTPUT" &) &
+	sleep 0.5s
```
Comment (AkihiroSuda) [inline tests/integration/update.bats:330]: maybe too short, `sleep 1s` ?

File: tests/integration/update.bats [hunk 8]
```diff
@@ -312,3 +312,42 @@ EOF
...
+	# We trigger the update a few times to make sure we hit the race.
+	for _ in {1..12}
+	do
+		# TODO: Update "runc update" so we can change the device rules.
+		runc update --pids-limit 30 test_update_devices
+		[ "$status" -eq 0 ]
+	done
+
+	# Kill recvtty.
+	kill -9 "$(<"$TMP_RECVTTY_PID")"
```
Comment (AkihiroSuda) [inline tests/integration/update.bats:348]: Is SIGKILL needed?

Comment (cyphar) [reply tests/integration/update.bats:348]: We do `kill -9` for the regular `recvtty` setup, I just copied it.

File: libcontainer/cgroups/devices_emulator.go [hunk 9]
```diff
@@ -0,0 +1,351 @@
+// +build linux
+
+package cgroups
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/devices_emulator.go:3]: Maybe we want to create a dedicated package for `libcontainer/cgroups/devicesemulator`

File: libcontainer/cgroups/devices_emulator.go [hunk 10]
```diff
@@ -0,0 +1,351 @@
...
+		err = errors.Wrap(e.rmRule(*rule), "remove 'deny' exception")
+	} else {
+		err = errors.Wrap(e.addRule(*rule), "add 'allow' exception")
+	}
+	return err
+}
+
+func (e *DevicesEmulator) deny(rule *deviceRule) error {
+	// This cgroup is configured as a white-list. Reset the entire emulator,
+	// and put is into white-list mode.
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/devices_emulator.go:202]: put what?

Comment (cyphar) [reply libcontainer/cgroups/devices_emulator.go:202]: Typo, should be "put it".

File: libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go [hunk 11]
```diff
@@ -83,71 +83,69 @@ block-2:
         19: Exit
 block-3:
         20: JNEImm dst: r2 off: -1 imm: 2 <block-4>
-        21: JNEImm dst: r4 off: -1 imm: 5 <block-4>
-        22: JNEImm dst: r5 off: -1 imm: 1 <block-4>
+        21: JNEImm dst: r4 off: -1 imm: 1 <block-4>
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go:86]: How are these changes introduced?

Comment (cyphar) [reply libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go:86]: The removal of the `/dev/console` rule means that `5:1` is no longer in the default whitelist, which changes the code generated.

File: tests/integration/update.bats (hunk 7 above)
Comment (cyphar) [reply tests/integration/update.bats]: I didn't have issues with my testing, but sure I'll bump it up.

File: libcontainer/configs/device.go [hunk 12]
```diff
@@ -35,23 +29,154 @@ type Device struct {
...
+func (p DevicePermissions) Intersection(o DevicePermissions) DevicePermissions {
+	lhs := p.toSet()
+	rhs := o.toSet()
+	return fromSet(lhs & rhs)
+}
+
+// IsEmpty returns whether the set of permissions in a DevicePermissions is
+// empty.
+func (p DevicePermissions) IsEmpty() bool {
+	return p == DevicePermissions("")
```
Comment (AkihiroSuda) [inline libcontainer/configs/device.go:99]: Maybe needs `strings.TrimSpace` somewhere

Comment (cyphar) [reply libcontainer/configs/device.go:99]: We could add it, but there's no point where we parse `DevicePermissions` that would allow a space to be added -- there's `IsValid` checks everywhere relevant. Honestly this whole `DevicePermissions` thing is to work around the fact that we (stupidly) embedded the string representation into the libcontainer state format...

**Comment by cyphar** [comment]
The new integration test fails under the systemd cgroup driver. I'll need to figure out what's going on there.

File: libcontainer/cgroups/fs/devices.go (hunk 6 above)
Comment (kolyshkin) [reply libcontainer/cgroups/fs/devices.go:91]: To me earlier return is almost always more readable, but only marginally in this case so whatever works for you

File: tests/integration/update.bats [hunk 13]
```diff
@@ -312,3 +312,46 @@ EOF
...
+	jq '.process.args = ["sh", "-c", "while true; do echo >/dev/null; done"]' config.json > config.json.tmp
+	mv config.json{.tmp,}
+
+	# Set up a temporary console socket and recvtty so we can get the stdio.
+	TMP_RECVTTY_DIR="$(mktemp -d "$BATS_TMPDIR/runc-tmp-recvtty.XXXXXX")"
+	TMP_RECVTTY_PID="$TMP_RECVTTY_DIR/recvtty.pid"
+	TMP_CONSOLE_SOCKET="$TMP_RECVTTY_DIR/console.sock"
+	CONTAINER_OUTPUT="$TMP_RECVTTY_DIR/output"
+	("$RECVTTY" --no-stdin --pid-file "$TMP_RECVTTY_PID" \
+				--mode single "$TMP_CONSOLE_SOCKET" &>"$CONTAINER_OUTPUT" &) &
```
Comment (kolyshkin) [inline tests/integration/update.bats:333]: I know this comes from `helpers.bats` but the double `&` is not really needed here, you'll be fine with something like
```shell
("$RECVTTY" ... ) &
```

IOW inner `&` is not needed.

File: tests/integration/update.bats [hunk 14]
```diff
@@ -312,3 +312,46 @@ EOF
...
+	sleep 1s
```
Comment (kolyshkin) [inline tests/integration/update.bats:334]: I hate sleeps in the test code :( it always means we're not doing something right

In this case, I guess, there is no way to check that recvtty is ready.

Or can we maybe wait till "$TMP_CONSOLE_SOCKET" is created? Something like
```shell
retry 10 0.1 test -e "$TMP_CONSOLE_SOCKET"
```
?

File: tests/integration/update.bats [hunk 15]
```diff
@@ -312,3 +312,46 @@ EOF
...
+
+	# Run the container in the background.
+	runc run -d --console-socket "$TMP_CONSOLE_SOCKET" test_update
+	cat "$CONTAINER_OUTPUT"
+	[ "$status" -eq 0 ]
+
+	# Trigger an update. This update doesn't actually change the device rules,
+	# but it will trigger the devices cgroup code to reapply the current rules.
+	# We trigger the update a few times to make sure we hit the race.
```
Comment (kolyshkin) [inline tests/integration/update.bats:343]: Slow Saturday here... which race?

Comment (cyphar) [reply tests/integration/update.bats:343]: That the container will try to write to `/dev/null` during the window between `a *:* rwm` being denied and the rest of the white-list being applied.

File: tests/integration/update.bats (hunk 14 above)
Comment (cyphar) [reply tests/integration/update.bats:334]: Yeah that'd work.

File: libcontainer/cgroups/devices_emulator.go (hunk 9 above)
Comment (cyphar) [reply libcontainer/cgroups/devices_emulator.go]: I've put it in `libcontainer/cgroups/devices` so we can write `devices.Emulator`.

**Comment by cyphar** [comment]
Ah, I think I know what the issue is. We start a transient unit under systemd even when we do `runc update` -- so systemd clears all of the state. We'll need to do something different if the container is already started (does systemd support an "update" to a transient unit).

This is a little scary because during the race window, systemd actually switches the devices cgroup **to be allow-all** (since that's the default). Oops.

**Comment by cyphar** [comment]
Ah, I think I know what the issue is. We start a transient unit under systemd even when we do `runc update` -- so systemd clears all of the state. We'll need to do something different if the container is already started. In particular, we need to use `SetUnitProperties` if the container is already running.

This is quite scary because during the race window, systemd actually switches the devices cgroup **to be allow-all** (since that's the default). Which means that a container could theoretically get full access to any block or character device on the system. Oops. Yet another reason to not use the systemd cgroup manager I guess :wink:.

**Comment by cyphar** [comment]
I just implemented the above, but it turns out that systemd has the same bug outlined above (if you tell it to reset `DevicesAllow` and then give it a new allow list, it will always write a deny-all blacklist first). So we'll just need to disable this test for systemd cgroups, since this behaviour is coming from systemd.

**Comment by cyphar** [comment]
Since this PR solves a few actual security bugs, I might request a CVE. The systemd cgroup one is probably worth a CVE on its own because it means containers could do all sorts of worrying attacks...

**Comment by cyphar** [comment]
Ah, of course. `DevicesAllow` doesn't allow wildcards for `/dev/{char,block}`. This is going to be quite ugly...

**Comment by AkihiroSuda** [comment]
Can we use freezer to mitigate the systemd race?

**Comment by cyphar** [comment]
"I used the cgroups to manage the cgroups."

Yeah, that's not a bad idea. Working on it.

**Comment by cyphar** [comment]
Hurray, all green! :green_heart:

File: libcontainer/cgroups/systemd/v1.go [hunk 16]
```diff
@@ -394,6 +418,13 @@ func (m *legacyManager) Set(container *configs.Config) error {
 		return err
 	}
 
+	// Unfreeze the cgroup.
```
Comment (AkihiroSuda) [inline libcontainer/cgroups/systemd/v1.go:421]: Seems covered in `defer m.Freeze(configs.Thawed)`

File: tests/integration/update.bats (hunk 15 above)
Comment (AkihiroSuda) [reply tests/integration/update.bats:343]: Please add code comments for the race?

File: libcontainer/cgroups/systemd/v1.go (hunk 16 above)
Comment (cyphar) [reply libcontainer/cgroups/systemd/v1.go:421]: I wanted to make sure we unfroze the cgroup before we ran the fsManager (to limit the length the time the container remains frozen, as well as to avoid stepping on our toes with the fsManager also writing to the freezer cgroup).

However, thinking about this more the `defer` is incorrect (as is using `configs.Thawed` directly) because if you're dealing with a user-frozen container (or the user requested we create a frozen container) then we won't do what they're expecting. I'll fix that now.

File: tests/integration/update.bats [hunk 17]
```diff
@@ -312,3 +312,66 @@ EOF
     check_cgroup_value "cpu.rt_period_us" 900001
     check_cgroup_value "cpu.rt_runtime_us" 600001
 }
+
+@test "update devices [minimal transition rules]" {
+    [[ "$ROOTLESS" -ne 0 ]] && requires rootless_cgroup
+	# This test currently only makes sense on cgroupv1.
+    requires cgroups_v1
```
Comment (AkihiroSuda) [inline tests/integration/update.bats:319]: indentation is broken

(off-topic: we should have `shfmt` in CI)

File: tests/integration/update.bats [hunk 18]
```diff
@@ -312,3 +312,66 @@ EOF
...
+	# Kill recvtty.
+	kill -9 "$(<"$TMP_RECVTTY_PID")"
+
+	# There should've been no output from the container.
+	cat "$CONTAINER_OUTPUT"
+	[ -z "$(<"$CONTAINER_OUTPUT")" ]
+}
+
+@test "update paused container" {
+    [[ "$ROOTLESS" -ne 0 ]] && requires rootless_cgroup
```
Comment (AkihiroSuda) [inline tests/integration/update.bats:360]: indentation

**Comment by AkihiroSuda** [comment]
LGTM

shfmt issue can be handled in follow-up PR

**Comment by cyphar** [comment]
Hang on, I'm still working on fixing the tests -- the newest one is breaking (the auto-detection for the freezer cgroup isn't working). Should only take a moment to fix...

**Comment by cyphar** [comment]
Alright, this is ready for review. Tests are implemented for the changes, and I enabled the `runc pause` tests for rootless containers which was missed some time ago.

**Comment by kolyshkin** [comment]
LGTM

**Comment by cyphar** [comment]
Rebased, now that the `GetPaths` changes have been merged.

/cc @opencontainers/runc-maintainers

**Comment by AkihiroSuda** [comment]
LGTM

File: tests/integration/helpers.bash [hunk 19]
```diff
@@ -200,75 +207,85 @@ function fail() {
...
+				skip=1
 			fi
 			;;
 		*)
-			fail "BUG: Invalid requires ${var}."
+			fail "BUG: Invalid requires $var."
 			;;
 		esac
+		if [ -n "$skip" ]; then
+			skip "test requires $var"
```
Comment (AkihiroSuda) [inline tests/integration/helpers.bash:287]: nit: Can we avoid using the same identifier for the variable and the function. (Surprised to know they don't conflict)

Comment (cyphar) [reply tests/integration/helpers.bash:287]: Sure. The reason they don't conflict is that variables and functions are in different namespaces.

Comment (cyphar) [reply tests/integration/helpers.bash:287]: Done.

File: tests/integration/helpers.bash [hunk 20]
```diff
@@ -200,75 +207,85 @@ function fail() {
 # support it, the test is skipped with a message.
 function requires() {
 	for var in "$@"; do
+		SKIP_ME=
```
Comment (AkihiroSuda) [inline tests/integration/helpers.bash:210]: nit again: `local skip_me` (in lower characters)

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by cyphar** [comment]
I've rebased and cleaned up the commit message for the `DeviceAllow` commit to better clarify that it was a security issue but since no released version of runc included it, it didn't deserve a proper security advisory.

**Comment by kolyshkin** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by tao12345666333** [comment]
When I try to vendor runc library v1.0.0-rc91 into Docker/Moby,  I found an unexpected behavior: https://github.com/moby/moby/pull/41178#issuecomment-663813218

After debugging, I found that the problem was introduced since this PR.  PTAL, Thanks!  https://github.com/moby/moby/pull/41178

**Comment by AkihiroSuda** [comment]
Could you open a new issue?

**Comment by tao12345666333** [comment]
sure.
