### PR TITLE
tests/int: swap-related fixes

### LINKED ISSUE #4166: [ci] We should check `memory.swap.max` exists or not for cgroupv2
I think in some old kernel with cgroupv2 enabled, `memory.swap.max` is not exist. For example:
```
Linux iZj6cdnzj9sp96xf38htrnZ 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

root@iZj6cdnzj9sp96xf38htrnZ:~# ls /sys/fs/cgroup/user.slice/user-0.slice/session-1.scope/
cgroup.controllers      cgroup.stat             cpuset.cpus            cpu.uclamp.max   io.stat              memory.low        pids.current
cgroup.events           cgroup.subtree_control  cpuset.cpus.effective  cpu.uclamp.min   io.weight            memory.max        pids.events
cgroup.freeze           cgroup.threads          cpuset.cpus.partition  cpu.weight       memory.current       memory.min        pids.max
cgroup.max.depth        cgroup.type             cpuset.mems            cpu.weight.nice  memory.events        memory.oom.group  rdma.current
cgroup.max.descendants  cpu.max                 cpuset.mems.effective  io.max           memory.events.local  memory.pressure   rdma.max
cgroup.procs            cpu.pressure            cpu.stat               io.pressure      memory.high          memory.stat
```
Then we will get some errors when setting memory swap limit:
```
not ok 164 update cgroup v1/v2 common limits
# (in test file tests/integration/update.bats, line 103)
#   `[ "$status" -eq 0 ]' failed
# runc spec (status=0):
#
# runc run -d --console-socket /tmp/bats-run-YCqIW9/runc.6WEppA/tty/sock test_update (status=0):
#
# current 33554432 !? 33554432
# current 25165824 !? 25165824
# current 20 !? 20
# runc update test_update --cpuset-cpus 1 (status=0):
#
# current 1 !? 1
# runc update test_update --memory 67108864 (status=0):
#
# current 67108864 !? 67108864
# runc update test_update --memory 50M (status=0):
#
# current 52428800 !? 52428800
# runc update test_update --memory-reservation 33554432 (status=0):
#
# current 33554432 !? 33554432
# runc update test_update --memory-swap -1 (status=1):
# time="2024-01-08T11:36:37+08:00" level=warning msg="Setting back cgroup configs failed due to error: open /sys/fs/cgroup/runc-cgroups-integration-test/test-cgroup-12193/memory.swap.max: no such file or directory, your state.json and actual configs might be inconsistent."
# time="2024-01-08T11:36:37+08:00" level=error msg="open /sys/fs/cgroup/runc-cgroups-integration-test/test-cgroup-12193/memory.swap.max: no such file or directory"
```

### PR DESCRIPTION
**Pull request by kolyshkin**
- Fixes a few minor issues with integration tests.
- cgroup v2: do not set swap to 0 or unlimited when it's not available.

See individual commits for details.

Fixes #4166

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by lifubang — CHANGES_REQUESTED** [review]
Sorry, when we set memory to -1, it means set both memory and swap limit to max:
https://github.com/opencontainers/runc/blob/a837eebc087922effd0f34b792cd8dec4481579d/tests/integration/update.bats#L119-L121

**Comment by kolyshkin** [comment]
> Sorry, when we set memory to -1 in cgroupv2, it means set both memory and swap limit to max:

@lifubang I'm not sure why this comment is related to this PR. In here I am just fixing some issues with the test.

**Comment by kolyshkin** [comment]
> Sorry, when we set memory to -1 in cgroupv2, it means set both memory and swap limit to max:
> 
 https://github.com/opencontainers/runc/blob/a837eebc087922effd0f34b792cd8dec4481579d/tests/integration/update.bats#L119-L121

Indeed it does remove both memory and swap limits in v2, and the test is checking it (see commit commit 18ebc51b).

IOW it's not a bug, it's a feature.

(and I still don't understand how this question relates to this PR)

**Comment by kolyshkin** [comment]
> > and I still don't understand how this question relates to this PR
> 
> Because with your patch, I still can get an error when test this case.

Thanks, I think I understand it now. Added two more commits, untested locally, please give it a try @lifubang.

**Comment by kolyshkin** [comment]
> > > and I still don't understand how this question relates to this PR
> > 
> > 
> > Because with your patch, I still can get an error when test this case.
> 
> Thanks, I think I understand it now. Added two more commits, untested locally, please give it a try @lifubang.

@lifubang PTAL

**Comment by lifubang** [comment]
> PTAL

I'll check it later, once I'm sitting in the front of my PC with an old kernel.

File: libcontainer/cgroups/fs2/memory.go [hunk 1]
```diff
@@ -57,7 +57,10 @@ func setMemory(dirPath string, r *configs.Resources) error {
 	// never write empty string to `memory.swap.max`, it means set to 0.
 	if swapStr != "" {
 		if err := cgroups.WriteFile(dirPath, "memory.swap.max", swapStr); err != nil {
-			return err
+			// If swap is not enabled, silently ignore setting to max or disabling it.
+			if !(errors.Is(err, os.ErrNotExist) && (swapStr == "max" || swapStr == "0")) {
```
Comment (lifubang) [inline libcontainer/cgroups/fs2/memory.go:61]: Your PR has indeed fixed the issue, but I think we should change the behavior according to what's doing in cgroup v1: https://github.com/opencontainers/runc/blob/59ca3a818c41087ecab64286caac80df9257161e/libcontainer/cgroups/fs/memory.go#L72-L77

**Review by lifubang — CHANGES_REQUESTED** [review]

File: libcontainer/cgroups/fs2/memory.go (hunk 1 above)
Comment (kolyshkin) [reply libcontainer/cgroups/fs2/memory.go:61]: Thanks! This is essentially what my code is doing, except
 - no extra syscalls, so a tad faster;
 - not dependent on memory setting (in fact it is, but this is done earlier)
 
 What aspect of it do you think needs to be changed?

Comment (lifubang) [reply libcontainer/cgroups/fs2/memory.go:61]: > What aspect of it do you think needs to be changed?

In cgroup v1, we check whether the `memory.memsw.limit_in_bytes` exists or not; but in cgroup v2, we always write `memory.swap.max` once the `swapStr` is no empty. I think we should change it to check the exist of `memory.swap.max`, if it is not exist, set the `swapStr` to empty, instead of check the write error type of `memory.swap.max`.

Comment (kolyshkin) [reply libcontainer/cgroups/fs2/memory.go:61]: This was done that way in cgroup v1 because cgroup management for swap was added later, and for quite some time the default expectation was "we don't have cgroup swap management".

For cgroup v2, the default expectation is "we have swap management", so we assume that `memory.swap.max` is available. If not, no big deal.

The (very slight) difference between the two implementations is what do we expect by default. The end result is the same in both cases.

The way this is implemented in cgroup v1 should not be seen as the "golden standard". Systems are evolving, defaults are changing, etc. More to say, at some point we're going to remove cgroup v1 code entirely (I very much hope to see that day).

Comment (lifubang) [reply libcontainer/cgroups/fs2/memory.go:61]: Ok

**Review by lifubang — APPROVED** [review]

**Comment by lifubang** [comment]
Maybe the forth commit(4209439b5f55e18bd901054f41df2f9470033832) should be backported to release-1.1?
