### PR TITLE
Remove panic from init

### LINKED ISSUE #1103: too many levels of symbolic links crash.
yes, its an error in my Dockerfile, but I presume you don't want to panic.

Docker version 1.12.2-rc3, build cb0ca64, experimental

my Dockerfile had:

```
RUN ln -s /sbin/getty /sbin/agetty
...
COPY agetty /sbin/agetty
```

but it didn't crash until the `RUN` line after the `COPY`.

```
Step 8 : RUN addgroup -g 1100 rancher &&     addgroup -g 1101 docker &&     addgroup -S sudo &&     adduser -D -u 1100 -g rancher -G docker -G sudo -s /bin/bash rancher &&     adduser -D -u 1101 -g docker -G docker -G sudo -s /bin/bash docker &&     echo ClientAliveInterval 180 >> /etc/ssh/sshd_config &&     echo '## allow password less for rancher user' >> /etc/sudoers &&     echo 'rancher ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&     echo '## allow password less for docker user' >> /etc/sudoers &&     echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&     echo '%sudo ALL=(ALL) ALL%sudo ALL=(ALL) ALL'  >> /etc/sudoers &&     ln -sf /usr/bin/docker.dist /usr/bin/docker &&     ln -sf /usr/bin/docker-containerd.dist /usr/bin/docker-containerd &&     ln -sf /usr/bin/docker-containerd-shim.dist /usr/bin/docker-containerd-shim &&     ln -sf /usr/bin/docker-runc.dist /usr/bin/docker-runc     echo 'ssh-keygen -A' >> /usr/sbin/update-ssh-keys
 ---> Running in 8250d0d1b6f3
panic: standard_init_linux.go:175: exec user process caused "too many levels of symbolic links" [recovered]
    panic: standard_init_linux.go:175: exec user process caused "too many levels of symbolic links"

goroutine 1 [running, locked to thread]:
panic(0x7eacc0, 0xc8201372d0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201092e8)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7eacc0, 0xc8201372d0)
    /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820108bf8, 0xc82001e0d0, 0xc820108d08)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820069630, 0x7f589e560728, 0xc8201372d0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820086a00, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74f5c0, 0x900fe8, 0x13, 0x847308, 0x4, 0xc820109268, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74f5c0, 0x900fe8, 0x13, 0xc820109268, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74f5c0, 0x900fe8, 0xc820086a00, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x84a1c8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e02a0, 0x51, 0x0, ...)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
    /go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

### PR DESCRIPTION
**Pull request by crosbymichael**
Print the error message to stderr if we are unable to return it back via
the pipe to the parent process.  Also, don't panic here as it is most
likely a system or user error and not a programmer error.

Fixes #1103

Signed-off-by: Michael Crosby crosbymichael@gmail.com

### CODE REVIEW

**Comment by cyphar** [comment]
Isn't the idea that this code will catch the `panic`:

```
defer func() {
 		if e := recover(); e != nil {
 			err = fmt.Errorf("panic from initialization: %v, %v", e, string(debug.Stack()))
 		}
}()
```

So that we get all of the panics? Though I'm not sure how a `panic` inside `defer` with a subsequent `defer`d `recover` is meant to work.

File: libcontainer/factory_linux.go [hunk 1]
```diff
@@ -256,11 +256,13 @@ func (l *LinuxFactory) StartInitialization() (err error) {
 		if _, ok := i.(*linuxStandardInit); ok {
```
Comment (cyphar) [inline libcontainer/factory_linux.go]: I just tried adding an `fmt.Fprintln(os.Stderr, "some text")` here to see what happens. It looks like there's still a lot of console tomfoolery going on -- because we set `cmd.Process.Std{in,out,err} = nil` before running `runc init`. So the container bootstrap doesn't write to the *actual* stdio (it writes to `/dev/null`). The reason I went with `panic`s here is because of that issue.

Comment (crosbymichael) [inline libcontainer/factory_linux.go]: Then what is panic writing to?

Comment (cyphar) [inline libcontainer/factory_linux.go]: I'm actually not sure. If the `recover` code is doing what I think it's doing then we are effectively just `exit(1)`-ing (if you look at `main_unix.go` for runC).

**Comment by hqhq** [comment]
So we probably should fix the issue that https://github.com/opencontainers/runc/pull/1071 tried to fix. And that's waiting for #1018 .

I agree we shouldn't panic here, though I'm still curious in what circumstance would the pipe closed before we write error messages.

File: libcontainer/factory_linux.go (hunk 1 above)
Comment (crosbymichael) [inline libcontainer/factory_linux.go]: Its just writing to stderr and exit(-1) so this change only makes this a single print of the error on stderr and the exit is the same without doing a panic, that is it.

**Comment by hqhq** [comment]
LGTM

**Comment by justincormack** [comment]
Here is an example that hits the panic https://github.com/docker/docker/issues/27983

**Comment by cyphar** [comment]
LGTM. I completely forgot that the `return` was inside a defer and so we're not losing the actual error.
