### PR TITLE
fix path error in systemd when stopped

### LINKED ISSUE #2337: systemd: ps/kill can't work when container is in stopped state
How to reproduce:
```
[root@bogon systemdtest]# runc --systemd-cgroup run -d test
[root@bogon systemdtest]# runc --systemd-cgroup list
ID          PID         STATUS      BUNDLE             CREATED                          OWNER
test        177063      running     /opt/systemdtest   2020-04-21T10:40:55.998063538Z   root
[root@bogon systemdtest]# runc --systemd-cgroup ps test
UID          PID    PPID  C STIME TTY          TIME CMD
root      177063       1  0 18:40 ?        00:00:00 sleep 20
[root@bogon systemdtest]# runc --systemd-cgroup list
ID          PID         STATUS      BUNDLE             CREATED                          OWNER
test        0           stopped     /opt/systemdtest   2020-04-21T10:40:55.998063538Z   root
[root@bogon systemdtest]# runc --systemd-cgroup kill -a test 0
WARN[0000] freezer not supported: open /sys/fs/cgroup/system.slice/runc-test.scope/cgroup.freeze: no such file or directory
ERRO[0000] lstat /sys/fs/cgroup/system.slice/runc-test.scope: no such file or directory
lstat /sys/fs/cgroup/system.slice/runc-test.scope: no such file or directory
[root@bogon systemdtest]# runc --systemd-cgroup ps test
ERRO[0000] container_linux.go:169: getting all container pids from cgroups caused "lstat /sys/fs/cgroup/system.slice/runc-test.scope: no such file or directory"
container_linux.go:169: getting all container pids from cgroups caused "lstat /sys/fs/cgroup/system.slice/runc-test.scope: no such file or directory"
[root@bogon systemdtest]#
```

### PR DESCRIPTION
**Pull request by lifubang**
fix #2337 

Because when the container is in stopped state, the cgroup path has been deleted by systemd driver.

Signed-off-by: lifubang <lifubang@acmcoder.com>

### CODE REVIEW

**Comment by lifubang** [comment]
This pr just fix cgroup v2.
For cgroup v1, it also has this problem, shall we need to fix it in cgroup v1?

File: libcontainer/cgroups/systemd/v2.go [hunk 1]
```diff
@@ -198,6 +198,9 @@ func (m *unifiedManager) GetUnifiedPath() (string, error) {
 	m.mu.Lock()
 	defer m.mu.Unlock()
 	if m.path != "" {
+		if !cgroups.PathExists(m.path) {
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/v2.go:201]: I would not do this in this function, but rather modify the callers to check that path exists.

Comment (kolyshkin) [reply libcontainer/cgroups/systemd/v2.go:201]: as this is a hot path and doing stat might not always be required.

**Comment by lifubang** [comment]
> I'd rather check if path exists in callers

Force pushed.
And the label is "area/systemd", not "area/cgroupv2". @kolyshkin

**Comment by lifubang** [comment]
travis-ci green now!

File: libcontainer/container_linux.go [hunk 2]
```diff
@@ -163,8 +163,39 @@ func (c *linuxContainer) OCIState() (*specs.State, error) {
...
 func (c *linuxContainer) Processes() ([]int, error) {
-	pids, err := c.cgroupManager.GetAllPids()
+	var pids []int
+	status, err := c.currentStatus()
+	if err != nil {
+		return pids, err
+	}
+	if status == Stopped {
+		// for systemd cgroup, the unit's cgroup path will be auto removed if container's all processes exited
+		if check := c.cgroupPathNotExist(); check {
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:193]:
```suggestion
		if c.cgroupPathNotExist() {
```

File: libcontainer/container_linux.go [hunk 3]
```diff
@@ -380,13 +411,19 @@ func (c *linuxContainer) start(process *Process) error {
...
-		return signalAllProcesses(c.cgroupManager, s)
-	}
 	status, err := c.currentStatus()
 	if err != nil {
 		return err
 	}
+	if all {
+		// for systemd cgroup, the unit's cgroup path will be auto removed if container's all processes exited
+		if status == Stopped {
+			if check := c.cgroupPathNotExist(); check {
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:421]: ditto

File: libcontainer/container_linux.go [hunk 4]
```diff
@@ -163,8 +163,39 @@ func (c *linuxContainer) OCIState() (*specs.State, error) {
 	return c.currentOCIState()
 }
 
+func (c *linuxContainer) cgroupPathNotExist() bool {
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:166]: Actually, what about adding `Exists()` method to cgroupManager instead?

File: libcontainer/container_linux.go [hunk 5]
```diff
@@ -163,8 +163,39 @@ func (c *linuxContainer) OCIState() (*specs.State, error) {
...
+		return pids, err
+	}
+	if status == Stopped {
+		// for systemd cgroup, the unit's cgroup path will be auto removed if container's all processes exited
+		if check := c.cgroupPathNotExist(); check {
+			return pids, err
+		}
+	}
+
+	pids, err = c.cgroupManager.GetAllPids()
```
Comment (thaJeztah) [inline libcontainer/container_linux.go:198]: wouldn't this already be able to have a check for `os.IsNotExist(err)` ? (Also wondering if `c.cgroupManager.GetAllPids()` should ignore `os.IsNotExist(err)` by default (if the path doesn't exist, just return an empty list of pids ?

Comment (lifubang) [reply libcontainer/container_linux.go:198]: > wouldn't this already be able to have a check for `os.IsNotExist(err)` ?

Yes, but in fs cgroup driver, there is no error when the container is in `stopped` state. And I think we should not ignore `IsNotExist` error when it is not in `stopped` state or it has joined a new pid namespace without path.

> (Also wondering if `c.cgroupManager.GetAllPids()` should ignore `os.IsNotExist(err)` by default (if the path doesn't exist, just return an empty list of pids ?

I think we should not ignore `IsNotExist` error when it is not in `stopped` state or it has joined a new pid namespace without path.

**Comment by kolyshkin** [comment]
@lifubang needs a rebase

File: libcontainer/container_linux_test.go [hunk 6]
```diff
@@ -134,11 +143,27 @@ func (m *mockProcess) forwardChildLogs() {
 }
 
 func TestGetContainerPids(t *testing.T) {
+	pid := 1
+	stat, err := system.Stat(pid)
+	if err != nil {
+		t.Fatalf("can't state pid %d", pid)
```
Comment (kolyshkin) [inline libcontainer/container_linux_test.go:149]: nit: `s/state/stat/`
nit: include the actual error as well

File: libcontainer/container_linux_test.go [hunk 7]
```diff
@@ -134,11 +143,27 @@ func (m *mockProcess) forwardChildLogs() {
...
 	container := &linuxContainer{
-		id:            "myid",
-		config:        &configs.Config{},
-		cgroupManager: &mockCgroupManager{allPids: []int{1, 2, 3}},
+		id:     "myid",
+		config: &configs.Config{},
+		cgroupManager: &mockCgroupManager{
+			allPids: []int{1, 2, 3},
+			paths: map[string]string{
+				"device": "/proc/self/cgroups",
```
Comment (kolyshkin) [inline libcontainer/container_linux_test.go:157]: this looks kind of weird.

File: libcontainer/cgroups/fs/apply_raw.go [hunk 8]
```diff
@@ -425,3 +425,8 @@ func (m *manager) GetFreezerState() (configs.FreezerState, error) {
 	}
 	return freezer.(*FreezerGroup).GetState(dir)
 }
+
+func (m *manager) Exists() bool {
+	paths := m.GetPaths()
+	return cgroups.PathExists(paths["devices"])
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/apply_raw.go:431]: I think you can just do
```go
return cgroups.PathExists(m.Path("devices"))
```

File: libcontainer/cgroups/systemd/v1.go [hunk 9]
```diff
@@ -485,3 +485,11 @@ func (m *legacyManager) GetFreezerState() (configs.FreezerState, error) {
 	}
 	return freezer.(*fs.FreezerGroup).GetState(path)
 }
+
+func (m *legacyManager) Exists() bool {
+	path, err := getSubsystemPath(m.cgroups, "devices")
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/v1.go:490]: `getSubsystemPath` is super expensive, it parses the whole `/proc/self/mountinfo`.

I think you should be using `m.Path("devices")` here.

**Comment by AkihiroSuda** [comment]
@lifubang PTAL. Also, can we have a test?

File: libcontainer/container_linux_test.go (hunk 6 above)
Comment (lifubang) [reply libcontainer/container_linux_test.go]: done

File: libcontainer/cgroups/fs/apply_raw.go (hunk 8 above)
Comment (lifubang) [reply libcontainer/cgroups/fs/apply_raw.go]: done

File: libcontainer/cgroups/systemd/v1.go (hunk 9 above)
Comment (lifubang) [reply libcontainer/cgroups/systemd/v1.go]: done

File: libcontainer/container_linux_test.go (hunk 7 above)
Comment (lifubang) [reply libcontainer/container_linux_test.go:157]: It's a mock data, I don't have any idea to improve it.

**Comment by lifubang** [comment]
> @lifubang PTAL at Kir's comments. Also, can we have an integration test?

finished now, PTAL.

File: tests/integration/ps.bats [hunk 10]
```diff
@@ -60,3 +60,28 @@ function teardown() {
   [[ ${lines[0]} =~ \ +PID\ +TTY\ +STAT\ +TIME\ +COMMAND+ ]]
   [[ "${lines[1]}" =~ [0-9]+ ]]
 }
+
+@test "ps after the container stopped" {
+  # ps is not supported, it requires cgroups
+  requires root
```
Comment (AkihiroSuda) [inline tests/integration/ps.bats:66]: should suppprt rootless cgroup

**Comment by AkihiroSuda** [comment]
CI failing

File: libcontainer/container_linux_test.go [hunk 11]
```diff
@@ -50,6 +50,15 @@ func (m *mockCgroupManager) Destroy() error {
 	return nil
 }
 
+func (m *mockCgroupManager) Exists() bool {
+	paths := m.GetPaths()
+	if paths != nil {
+		_, err := os.Lstat(paths["devices"])
```
Comment (kolyshkin) [inline libcontainer/container_linux_test.go:56]: While it is technically OK to use `m.GetPaths()` here, and it's a mock code so it doesn't really matter, I'd still like to have `m.Path("devices")` used here, because since commit 714c91e9f73a1512808476eb532b4aa36bbb7530 we're not supposed to use GetPaths() for anything other than state save/restore.

File: libcontainer/cgroups/fs/apply_raw.go [hunk 12]
```diff
@@ -392,3 +392,7 @@ func (m *manager) GetFreezerState() (configs.FreezerState, error) {
 	}
 	return freezer.(*FreezerGroup).GetState(dir)
 }
+
+func (m *manager) Exists() bool {
+	return cgroups.PathExists(m.paths["devices"])
```
Comment (kolyshkin) [inline libcontainer/cgroups/fs/apply_raw.go:397]: It probably doesn't matter in practice, but we're not supposed to access a map without holding a lock. This is why I have suggested using `m.Path("devices")` earlier -- it takes a lock before accessing m.paths.

Alternatively, you can leave this code as is but add taking a lock (same as `Path()`).

File: libcontainer/cgroups/systemd/v1.go [hunk 13]
```diff
@@ -481,3 +481,7 @@ func (m *legacyManager) GetFreezerState() (configs.FreezerState, error) {
 	}
 	return freezer.(*fs.FreezerGroup).GetState(path)
 }
+
+func (m *legacyManager) Exists() bool {
+	return cgroups.PathExists(m.paths["devices"])
```
Comment (kolyshkin) [inline libcontainer/cgroups/systemd/v1.go:486]: ditto

File: libcontainer/container_linux.go [hunk 14]
```diff
@@ -169,7 +169,17 @@ func (c *linuxContainer) OCIState() (*specs.State, error) {
...
 
 func (c *linuxContainer) Processes() ([]int, error) {
-	pids, err := c.cgroupManager.GetAllPids()
+	var pids []int
+	status, err := c.currentStatus()
+	if err != nil {
+		return pids, err
+	}
+	// for systemd cgroup, the unit's cgroup path will be auto removed if container's all processes exited
+	if status == Stopped && !c.cgroupManager.Exists() {
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:178]: Does it make sense to check for "Created" here as well? Or should it return an error in such case?

Comment (kolyshkin) [reply libcontainer/container_linux.go:178]: No it does not ("created" container has a `runc init` process running so everything works as expected.

Also, "paused" container also has a process running.

So, it seems that the check for "stopped" here is sufficient.

**Comment by mrunalp** [comment]
@lifubang could you update the PR?

**Comment by AkihiroSuda** [comment]
@kolyshkin @mrunalp 
Let's merge this as-is and cover the nits in a follow-up PR.

**Comment by mrunalp** [comment]
I am fine with that.

**Comment by AkihiroSuda** [comment]
@kolyshkin WDYT?
