### PR TITLE
fix runc events error in cgroup v2

### LINKED ISSUE #2351: cgroupv2: runc events is broken
How to reproduce:
```
[root@localhost ~]# runc events test
ERRO[0000] open /sys/fs/cgroup/user.slice/user-a.slice/aa-bb.scope/memory.oom_control: no such file or directory
open /sys/fs/cgroup/user.slice/user-a.slice/aa-bb.scope/memory.oom_control: no such file or directory
```

### PR DESCRIPTION
**Pull request by lifubang**
fix #2351 

Because there is no `oom notifier` in `cgroup v2` now.
I think we should use `Inotify` to watch `OOM` in `memory.events`.

Signed-off-by: lifubang <lifubang@acmcoder.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, please update https://github.com/opencontainers/runc/blob/master/tests/integration/events.bats as well

File: libcontainer/notify_linux_v2.go [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+	"path/filepath"
+	"strings"
+
+	"github.com/fsnotify/fsnotify"
+	"github.com/sirupsen/logrus"
+)
+
+func checkOOM(path string) (bool, error) {
+	file, err := os.Open(path)
+	defer file.Close()
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:19]: move defer to after the `err != nil` check

File: libcontainer/notify_linux_v2.go [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+				}
+			}
+		}
+	}()
+	return ch, nil
+}
+
+// notifyOnOOMV2 returns channel on which you can expect event about OOM,
+// if process died without OOM this channel will be closed.
+func notifyOnOOMV2(paths map[string]string) (<-chan struct{}, error) {
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:85]: We should not use `paths` for cgroupv2 code. in cgroupv2 there is only one path.

File: libcontainer/notify_linux_v2.go [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+	if err != nil {
+		return false, err
+	}
+	buff := bufio.NewReader(file)
+	for {
+		line, err := buff.ReadString('\n')
+		if err == io.EOF {
+			break
+		}
+		arr := strings.Fields(line)
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:29]: So, you are only analyzing the last line (which on my system starts with `oom_kill`).

What you should do (I think) is
1 read/parse the file
2 get the counters for `oom` and `oom_kill` lines
3 compare these with the previous readings (or `0` if there are none)
4 save the counters (to be used later on step 3)
5 if counters are increased, return `true`

File: libcontainer/container_linux.go [hunk 4]
```diff
@@ -648,6 +648,9 @@ func (c *linuxContainer) NotifyOOM() (<-chan struct{}, error) {
 	if c.config.RootlessCgroups {
 		logrus.Warn("getting OOM notifications may fail if you don't have the full access to cgroups")
 	}
+	if cgroups.IsCgroup2UnifiedMode() {
+		return notifyOnOOMV2(c.cgroupManager.GetPaths())
```
Comment (kolyshkin) [inline libcontainer/container_linux.go:652]: use `GetUnifiedPath()`

File: libcontainer/notify_linux_v2.go [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+
+import (
+	"bufio"
+	"fmt"
+	"io"
+	"os"
+	"path/filepath"
+	"strings"
+
+	"github.com/fsnotify/fsnotify"
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:13]: This package is not well maintained, and tries to work for all systems, sacrificing linux-specific features.

I havent't checked it, but can you take a look at how hard it would be to use `Inotify*` functions from `golang.org/x/sys/unix` directly?

**Comment by lifubang** [comment]
> please update https://github.com/opencontainers/runc/blob/master/tests/integration/events.bats as well

enable cgroup v2 tests in events.bats now.

File: libcontainer/notify_linux_v2.go [hunk 6]
```diff
@@ -0,0 +1,127 @@
...
+
+	content, err := ioutil.ReadFile(path)
+	if err != nil {
+		return 0, err
+	}
+
+	oomCount := 0
+	lines := strings.Split(string(content), "\n")
+	for _, line := range lines {
+		arr := strings.Fields(line)
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:30]: `strings.Split(line, " ")` is 2x faster, if your input is standard (no extra spaces etc.), and in this case the input is standard.

**Comment by AkihiroSuda** [comment]
LGTM

File: libcontainer/notify_linux_v2.go [hunk 7]
```diff
@@ -0,0 +1,127 @@
...
+	}
+	return 0, nil
+}
+
+func registerMemoryEventV2(cgDir string, evName string, cgEvName string) (<-chan struct{}, error) {
+	eventControlPath := filepath.Join(cgDir, evName)
+	cgEvPath := filepath.Join(cgDir, cgEvName)
+	fd, err := unix.InotifyInit()
+	if err != nil {
+		return nil, err
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:65]: I'm afraid the error you get is very basic so you need to wrap it
```go
return errors.Wrap("unable to init inotify: %v", err)
```
or something like that

File: libcontainer/notify_linux_v2.go [hunk 8]
```diff
@@ -0,0 +1,127 @@
...
+	}
+	// watching oom kill
+	_, err = unix.InotifyAddWatch(fd, eventControlPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, err
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:71]: same here

File: libcontainer/notify_linux_v2.go [hunk 9]
```diff
@@ -0,0 +1,127 @@
...
+			}
+		}
+	}
+	return oomCount, nil
+}
+
+func getPopulated(path string) (int, error) {
+	if _, err := os.Lstat(path); err != nil {
+		return 0, err
+	}
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:44]: Looks like if you remove the `os.Lstat()` code the functionality won't change -- you will get the same error from `ioutil.ReadFile` below.

File: libcontainer/notify_linux_v2.go [hunk 10]
```diff
@@ -0,0 +1,127 @@
...
+	for _, line := range lines {
+		arr := strings.Split(line, " ")
+		if len(arr) == 2 && arr[0] == "populated" {
+			return strconv.Atoi(arr[1])
+		}
+	}
+	return 0, nil
+}
+
+func registerMemoryEventV2(cgDir string, evName string, cgEvName string) (<-chan struct{}, error) {
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:60]: nit: `(cgDir, evName, cgEvName string)`

File: libcontainer/notify_linux_v2.go [hunk 11]
```diff
@@ -0,0 +1,127 @@
...
+	_, err = unix.InotifyAddWatch(fd, eventControlPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, err
+	}
+	// Because no `unix.IN_DELETE|unix.IN_DELETE_SELF` event for cgroup file system, so watching all process exited
+	_, err = unix.InotifyAddWatch(fd, cgEvPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, err
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:77]: same here

File: libcontainer/notify_linux_v2.go [hunk 12]
```diff
@@ -0,0 +1,127 @@
...
+		)
+		defer func() {
+			unix.Close(fd)
+			close(ch)
+		}()
+
+		for {
+			n, err := unix.Read(fd, buffer[:])
+			if err != nil {
+				logrus.Warn(err)
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:93]: Same here. The error you'll get is something like "interruped system call" with no context whatsoever. Please add some context.

File: libcontainer/notify_linux_v2.go [hunk 13]
```diff
@@ -0,0 +1,127 @@
...
+				return
+			}
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:95]: You probably need to check if enough bytes are read
```go
if n < unix.SizeofInotifyEvent {
	logrus.Warn("short read from inotify")
	return
}
```

File: libcontainer/notify_linux_v2.go [hunk 14]
```diff
@@ -0,0 +1,127 @@
...
+			offset = 0
+			for offset <= uint32(n-unix.SizeofInotifyEvent) {
+				rawEvent := (*unix.InotifyEvent)(unsafe.Pointer(&buffer[offset]))
+				bytes := (*[unix.PathMax]byte)(unsafe.Pointer(&buffer[unix.SizeofInotifyEvent]))
+				eventName := strings.TrimRight(string(bytes[0:rawEvent.Len]), "\000")
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:100]: 1. This is actually a file name, not an event name.

2. It might be easier to just save the two fds returned by `InotifyAddWatch` above and check if `rawEvent.Wd` is one of them. Let me take a look...

File: libcontainer/notify_linux_v2.go [hunk 15]
```diff
@@ -0,0 +1,127 @@
...
+				offset += unix.SizeofInotifyEvent + uint32(rawEvent.Len)
+				if rawEvent.Mask&unix.IN_MODIFY == unix.IN_MODIFY {
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:102]: I'd rather have it as
```go
rawEvent := (*unix.InotifyEvent)(unsafe.Pointer(&buffer[offset]))
if rawEvent.Mask&unix.IN_MODIFY != unix.IN_MODIFY {
	continue
}
bytes := (*[unix.PathMax]byte)(unsafe.Pointer(&buffer[unix.SizeofInotifyEvent]))
eventName := strings.TrimRight(string(bytes[0:rawEvent.Len]), "\000")
switch eventName {
....
```

It's less indentation and better readability that way

File: libcontainer/notify_linux_v2.go (hunk 14 above)
Comment (kolyshkin) [reply libcontainer/notify_linux_v2.go:100]: That's right. You can just check the fd, no need to check the file name. Simpler code and faster checks.

```go
evFd, err := unix.InotifyAddWatch(fd, eventControlPath, unix.IN_MODIFY)
...
cgFd, err := unix.InotifyAddWatch(fd, cgEvPath, unix.IN_MODIFY)
...
for offset <= uint32(n-unix.SizeofInotifyEvent) {
  event := (*unix.InotifyEvent)(unsafe.Pointer(&buffer[offset]))
  offset += unix.SizeofInotifyEvent + uint32(event.Len)
  if event.Mask&unix.IN_MODIFY != unix.IN_MODIFY {
    continue
  }
  switch int(event.Wd) {
    case evFd:
      oom, err := getOOMCount(eventControlPath)
      ...
    case cgFd:
      pids, err := getPopulated(cgEvPath)
...
```

File: libcontainer/notify_linux_v2.go [hunk 16]
```diff
@@ -0,0 +1,127 @@
...
+	// Because no `unix.IN_DELETE|unix.IN_DELETE_SELF` event for cgroup file system, so watching all process exited
+	_, err = unix.InotifyAddWatch(fd, cgEvPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, err
+	}
+	ch := make(chan struct{})
+	go func() {
+		var (
+			buffer [unix.SizeofInotifyEvent + unix.PathMax]byte
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:82]: inotify(7) man page says
> Specifying a buffer of size
> `           sizeof(struct inotify_event) + NAME_MAX + 1`
> will be sufficient to read at least one event.

Yours is 1 byte short.

File: libcontainer/notify_linux_v2.go [hunk 17]
```diff
@@ -0,0 +1,127 @@
...
+	content, err := ioutil.ReadFile(path)
+	if err != nil {
+		return 0, err
+	}
+
+	oomCount := 0
+	lines := strings.Split(string(content), "\n")
+	for _, line := range lines {
+		arr := strings.Split(line, " ")
+		if len(arr) == 2 && (arr[0] == "oom" || arr[0] == "oom_kill") {
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:31]: Most probably you only need `"oom_kill"` here, since `"oom"' event means the cgroup was out of memory but wasn't necessarily killed.

**Comment by kolyshkin** [comment]
Ideally I'd like to add a test case for OOM event, since currently we only test for those periodical stats.

Can you add a separate patch testing for OOM event? It's pretty easy: run a memory hog inside a container and wait for OOM event.

A memory hog can be created in sh like this:
`sh -c 'VAR=$(seq 1 100000000)'`

**Comment by lifubang** [comment]
> Can you add a separate patch testing for OOM event? It's pretty easy:

I have add a test now, but not easy, we should disable memory swap, or else it’s very hard to cause oom.
And the meaning of swap value now is different in v1 and v2, it’s quite inconvenient to use. So I have post an issue.

File: libcontainer/notify_linux_v2.go [hunk 18]
```diff
@@ -0,0 +1,102 @@
...
+	cgEvPath := filepath.Join(cgDir, cgEvName)
+	fd, err := unix.InotifyInit()
+	if err != nil {
+		return nil, errors.Wrap(err, "unable to init inotify")
+	}
+	// watching oom kill
+	evFd, err := unix.InotifyAddWatch(fd, eventControlPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, errors.Wrap(err, "unable to add watch inotify")
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:44]: `s/watch inotify/inotify watch/`

File: libcontainer/notify_linux_v2.go [hunk 19]
```diff
@@ -0,0 +1,102 @@
...
+	}
+	// Because no `unix.IN_DELETE|unix.IN_DELETE_SELF` event for cgroup file system, so watching all process exited
+	cgFd, err := unix.InotifyAddWatch(fd, cgEvPath, unix.IN_MODIFY)
+	if err != nil {
+		unix.Close(fd)
+		return nil, errors.Wrap(err, "unable to add watch inotify")
```
Comment (kolyshkin) [inline libcontainer/notify_linux_v2.go:50]: ditto

File: tests/integration/events.bats [hunk 20]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
+  # XXX: currently cgroups require root containers.
+  requires root
+  init_cgroup_paths
+
+  # Set some initial known values
+  if [ "$CGROUP_UNIFIED" == "yes" ]; then
+  DATA=$(cat <<EOF
+  "memory": {
+    "limit": 33554433,
+    "kernel": 33554433,
```
Comment (kolyshkin) [inline tests/integration/events.bats:125]: No need to specify kernel limit here, it serves no purpose (and is ignored for v2 anyway)

File: tests/integration/events.bats [hunk 21]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
+    "swappiness": 0,
```
Comment (kolyshkin) [inline tests/integration/events.bats:126]: same for swappiness

File: tests/integration/events.bats [hunk 22]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
   [ "$status" -eq 0 ]
 }
+
+@test "events oom " {
+  # XXX: currently cgroups require root containers.
+  requires root
+  init_cgroup_paths
+
+  # Set some initial known values
+  if [ "$CGROUP_UNIFIED" == "yes" ]; then
```
Comment (kolyshkin) [inline tests/integration/events.bats:121]: Let's merge https://github.com/opencontainers/runc/pull/2370 first so we won't have to have this switch here.

File: tests/integration/events.bats [hunk 23]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
+  # spawn two sub processes (shells)
+  # the first sub process is an event logger that sends stats events to events.log
+  # the second sub process exec a memory hog process to cause a oom condition
+  # and waits for an oom event that includes test_busybox
+  # then kills the test_busybox container which causes the event logger to exit
+  (__runc events test_busybox > events.log) &
+  (
+    retry 10 1 eval "grep -q 'test_busybox' events.log"
+    __runc exec -d test_busybox sh -c 'VAR=$(seq 1 100000000)'
+    retry 10 1 eval "grep -q 'oom' events.log"
```
Comment (kolyshkin) [inline tests/integration/events.bats:158]: maybe `grep -qF '"type":"oom"'` to be more strict about what we're looking for here.

File: tests/integration/events.bats [hunk 24]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
+    __runc delete -f test_busybox
+  ) &
+  wait # wait for the above sub shells to finish
```
Comment (kolyshkin) [inline tests/integration/events.bats:161]: Maybe add a small timeout in case runc won't ever exit?
`timeout 10 wait`

Comment (lifubang) [reply tests/integration/events.bats:161]: Once  #2370 merged, I'll update it together with some other changes.

File: tests/integration/events.bats (hunk 20 above)
Comment (lifubang) [reply tests/integration/events.bats:125]: Yes, I just copy from v1, I'll remove `kernel` and `swappiness`.

File: tests/integration/events.bats [hunk 25]
```diff
@@ -111,3 +111,56 @@ function teardown() {
...
+
+  [ -e events.log ]
```
Comment (kolyshkin) [inline tests/integration/events.bats:163]: this check is redundant, grep below will print a message and return a non-zero exit code if the file is not found

File: tests/integration/events.bats (hunk 24 above)
Comment (kolyshkin) [reply tests/integration/events.bats:161]: @lifubang #2370 is merged

Comment (lifubang) [reply tests/integration/events.bats:148]: @kolyshkin `timeout` and `wait` can't be used together.

File: tests/integration/events.bats [hunk 26]
```diff
@@ -111,3 +111,40 @@ function teardown() {
   run eval "grep -q 'test_busybox' events.log"
   [ "$status" -eq 0 ]
 }
+
+@test "events oom " {
```
Comment (kolyshkin) [inline tests/integration/events.bats:115]: nit: extra space before `"`

File: tests/integration/events.bats [hunk 27]
```diff
@@ -111,3 +111,40 @@ function teardown() {
...
+  # XXX: currently cgroups require root containers.
+  requires root
+  init_cgroup_paths
+
+  # Set some initial known values
```
Comment (kolyshkin) [inline tests/integration/events.bats:120]: Maybe replace this by
```go
# we need the container to hit OOM, so disable swap
# ("swap" here is actually memory+swap)
```

or something like that

File: tests/integration/events.bats (hunk 24 above)
Comment (kolyshkin) [reply tests/integration/events.bats:147]: Yes, you're right.

I am still concerned that this case might hang forever. Maybe we can run both `__runc` invocations with a timeout then. Something big, say 1 minute. Obviously, if OOM has not happened within a minute, the test has failed.

Comment (lifubang) [reply tests/integration/events.bats:147]: Travis CI will return an error if there is no output after 150 seconds.
I met this error before I disable swap.

If you worry about this, I can write simple C program to ensure causing oom kill.

Comment (lifubang) [reply tests/integration/events.bats:147]: @kolyshkin use `sh -c 'test=$(dd if=/dev/urandom ibs=5120k)'` to ensure oom kill.
Because the memory limit is 4M.

**Comment by kolyshkin** [comment]
LGTM, thanks!

**Comment by AkihiroSuda** [comment]
LGTM
