### PR TITLE
libcontainer: remove "pausing" state

### LINKED ISSUE #3343: remove Pausing state, update docs
This needs to be done after merging #3316.

The "Pausing" state of container is not used, and the Pause() docs incorrectly says that it works asynchronously.

Need to
 - remove Pausing state entirely;
 - update the docs (make them conform to golang style)

Ref: https://github.com/opencontainers/runc/pull/3316#discussion_r787643478

### PR DESCRIPTION
**Pull request by danishprakash**
Upon running tests via `make test`, I encountered flaky failures, I'll look into those and see if they have something to do with my host because I noticed the same behavior on `main` too.

Addresses #3343

### CODE REVIEW

File: libcontainer/container_linux.go [hunk 1]
```diff
@@ -100,7 +100,7 @@ type Container interface {
 	// Restore restores the checkpointed container to a running state using the criu(8) utility.
 	Restore(process *Process, criuOpts *CriuOpts) error
 
-	// If the Container state is RUNNING or CREATED, sets the Container state to PAUSING and pauses
+	// If the Container state is RUNNING or CREATED, sets the Container state to PAUSED and pauses
```
Comment (danishprakash) [inline libcontainer/container_linux.go:103]: Although the actual state that `Pause` internally sets is `FROZEN`, I hope this should be okay as an externally exposed func doc? cc/ @kolyshkin

Comment (kolyshkin) [reply libcontainer/container_linux.go:103]: Yes, it's "frozen" in cgroup lingo, and "paused" in libcontainer lingo.

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
> Closes #3343

That issue also says to convert docs to golang style, so we can't close it just yet.

Surely this needs to be a separate PR.

So, replace `Closes:` with `Addresses:` or something.

**Comment by danishprakash** [comment]
Yes, that can be a separate PR of its own. Updated.

**Comment by kolyshkin** [comment]
@thaJeztah PTAL

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks for contributing!
