### PR TITLE
Change netclassid json tag

### LINKED ISSUE #999: runc list gives JSON unmarshaling error
While running the runc list
gave the following error
./runc list
json: cannot unmarshal string into Go value of type uint32

Though /run/runc had state.json for the container.
This came only once. I'll try to reproduce again and report back

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #999

This allows older state files to be loaded without the unmarshal error
of the string to int conversion.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM. As an aside, we need to make `runc list` more resilient to issues (it will always exit on an error rather than printing every entry it can). I've done some of that work in #774 and probably can pull it out and put it into a separate PR.

File: libcontainer/configs/cgroup_unix.go [hunk 1]
```diff
@@ -120,5 +120,5 @@ type Resources struct {
 	NetPrioIfpriomap []*IfPrioMap `json:"net_prio_ifpriomap"`
 
 	// Set class identifier for container's network packets
-	NetClsClassid uint32 `json:"net_cls_classid"`
+	NetClsClassid uint32 `json:"net_cls_classidu"`
```
Comment (mrunalp) [inline libcontainer/configs/cgroup_unix.go]: nit: Maybe name it net_cls_classid_u?

**Comment by crosbymichael** [comment]
@mrunalp updated

**Comment by cyphar** [comment]
LGTM.

**Comment by mrunalp** [comment]
LGTM
