### PR TITLE
cgroups: ebpf: use link.Anchor to check for BPF_F_REPLACE support

### LINKED ISSUE #3008: "failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown" (master, kernel 5.4, cgroup2)
`docker run` does not work at all with runc 4d6b9297 , cgroup v2, and kernel 5.4, due to the `failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown.` error.

```console
$ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to call BPF_PROG_ATTACH (BPF_CGROUP_DEVICE, BPF_F_ALLOW_MULTI): can't attach program: invalid argument: unknown.
ERRO[0000] error waiting for container: context canceled 
```

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95+dev
  GitCommit:        v1.0.0-rc95-89-g4d6b9297
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: v1.0.0-rc95-89-g4d6b9297
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.4.0-74-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.941GiB
 Name: ubuntu-focal
 ID: IXOP:CWWS:M7ET:LOFO:QI2Q:7KE6:BEMB:3SYU:WFTP:GHJF:RUID:YA53
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Found in https://github.com/moby/moby/pull/42450 , discussed in https://github.com/opencontainers/runc/pull/2986

### PR DESCRIPTION
**Pull request by cyphar**
In v0.13.0, cilium/ebpf stopped supporting setting BPF_F_REPLACE as an
explicit flag and instead requires us to use link.Anchor to specify
where the program should be attached.

Commit https://github.com/opencontainers/runc/commit/216175a9ca84cac30a570049a98e948f60c5f1a4 ("Upgrade Cilium's eBPF library version to 0.16")
did update this correctly for the actual attaching logic, but when
checking for kernel support we still passed BPF_F_REPLACE. This would
result in a generic error being returned, which our feature-support
checking logic would treat as being an error the indicates that
BPF_F_REPLACE *is* supported, resulting in a regression on pre-5.6
kernels.

It turns out that our debug logging saying that this unexpected error
was happening was being output as a result of this change, but nobody
noticed...

Fixes: https://github.com/opencontainers/runc/commit/216175a9ca84cac30a570049a98e948f60c5f1a4 ("Upgrade Cilium's eBPF library version to 0.16")
Fixes #3008
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
It turns out we've had this debug logging message since #4397 was merged (which indicated that we had a regression on #3008), but nobody noticed:

```
DEBU[0000]libcontainer/cgroups/devices/ebpf_linux.go:139 libcontainer/cgroups/devices.haveBpfProgReplace.func1() checking for BPF_F_REPLACE: got unexpected (not EBADF or EINVAL) error: disallowed flags: use Anchor to specify attach target
```

**Comment by rafaelroquetto** [comment]
Nice catch, thanks for spotting this. If there's anything in particular I can do to help let me know.

File: libcontainer/cgroups/devices/ebpf_linux.go [hunk 1]
```diff
@@ -133,11 +133,10 @@ func haveBpfProgReplace() bool {
...
 			Flags:   unix.BPF_F_ALLOW_MULTI,
 		})
-		if errors.Is(err, unix.EINVAL) {
+		if errors.Is(err, ebpf.ErrNotSupported) || errors.Is(err, unix.EINVAL) {
 			// not supported
 			return
 		}
-		// attach_flags test succeeded.
 		if !errors.Is(err, unix.EBADF) {
 			logrus.Debugf("checking for BPF_F_REPLACE: got unexpected (not EBADF or EINVAL) error: %v", err)
```
Comment (kolyshkin) [inline libcontainer/cgroups/devices/ebpf_linux.go]: nit: the message is not entirely correct now (I guess we can just drop the `(not EBADF or EINVAL)` part).

**Review by kolyshkin — APPROVED** [review]
LGTM except a minor nit

**Comment by kolyshkin** [comment]
Looks like in order to catch this in CI we'd need a combination of kernel < v5.6 and cgroup v2? This is why it went unnoticed -- we don't have that (and it's hard to get in CI -- something like Ubuntu 20.04 with an explicit switch to cgroup v2  and kernel **not** upgraded to HWE one).

**Comment by cyphar** [comment]
Yeah, though we would've caught that *something* was going wrong if the debug messages had been warnings (because all systems were returning the wrong error since the update patch).

**Review by thaJeztah — APPROVED** [review]
LGTM
